var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(a){return a instanceof e?a:new e(function(b,h){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})}this.batch_.push(a)};var d=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){d(a,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];a[b]=null;try{c()}catch(m){this.asyncThrow_(m)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var e=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(k){b.reject(k)}};e.prototype.createResolveAndReject_=function(){function a(a){return function(h){c||(c=!0,a.call(b,h))}}var b=this,c=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};e.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof e)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};e.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(k){this.reject_(k);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};e.prototype.reject_=function(a){this.settle_(2,a)};e.prototype.fulfill_=function(a){this.settle_(1,a)};e.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)f.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var f=new b;e.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};e.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(m){c.reject(m)}};e.prototype.then=function(a,b){function c(a,b){return"function"==typeof a?function(b){try{d(a(b))}catch(u){f(u)}}:b}var d,f,h=new e(function(a,b){d=a;f=b});this.callWhenSettled_(c(a,d),c(b,f));return h};
e.prototype["catch"]=function(a){return this.then(void 0,a)};e.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?f.asyncExecute(c):this.onSettledCallbacks_.push(c)};e.resolve=c;e.reject=function(a){return new e(function(b,c){c(a)})};e.race=function(a){return new e(function(b,d){for(var f=$jscomp.makeIterator(a),e=f.next();!e.done;e=
f.next())c(e.value).callWhenSettled_(b,d)})};e.all=function(a){var b=$jscomp.makeIterator(a),d=b.next();return d.done?c([]):new e(function(a,e){function f(b){return function(c){h[b]=c;k--;0==k&&a(h)}}var h=[],k=0;do h.push(void 0),k++,c(d.value).callWhenSettled_(f(h.length-1),e),d=b.next();while(!d.done)})};return e},"es6","es3");
$jscomp.polyfill("Promise.prototype.finally",function(a){return a?a:function(a){return this.then(function(b){return Promise.resolve(a()).then(function(){return b})},function(b){return Promise.resolve(a()).then(function(){throw b;})})}},"es9","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(c||"")+"_"+b++,c)}var b=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype["return"]=function(a){this.abruptCompletion_={"return":a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){var c=$jscomp.makeIterator(a),d=c.next();$jscomp.generator.ensureIteratorResultIsObject_(d);if(d.done)this.yieldResult=d.value,this.nextAddress=b;else return this.yieldAllIterator_=c,this.yield(d.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){var c=this.finallyContexts_.splice(b||0)[0];if(c=this.abruptCompletion_=this.abruptCompletion_||c){if(c.isException)return this.jumpToErrorHandler_();void 0!=c.jumpTo&&this.finallyAddress_<c.jumpTo?(this.nextAddress=c.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(a){return{value:a,done:!0}},a,this.context_["return"]);this.context_["return"](a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var d=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(d);if(!d.done)return this.context_.stop_(),d;var e=d.value}catch(f){return this.context_.yieldAllIterator_=null,this.context_.throw_(f),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a["return"],done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this["throw"]=function(b){return a.throw_(b)};this["return"]=function(b){return a.return_(b)};$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){var c=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&$jscomp.setPrototypeOf(c,a.prototype);return c};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(b){return a.next(b)}function c(b){return a["throw"](b)}return new Promise(function(d,e){function f(a){a.done?d(a.value):Promise.resolve(a.value).then(b,c).then(f,e)}f(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
var ABILITY_MASTER,STYLE_MASTER,tree;$(document).on("click",".abilityName",function(){var a=$(this).attr("abid");$("#abilty_label").text(ABILITY_MASTER[a].Name);displayAbilityHolder(ABILITY_MASTER[a]);scrollStyleList()});$(document).on("click",".switch .toggle",function(){$(this).toggleClass("accordionActive").next().slideToggle(300)});$(function(){$(".container").on("click",function(){});init()});var ABILITY_TREE;
function init(){var a,b,c,d;return $jscomp.asyncExecutePromiseGeneratorProgram(function(e){if(1==e.nextAddress)return a=readFile("Ability",function(a){ABILITY_MASTER=a}),b=readAnalyzeFile("ABILITY_TREE",function(a){ABILITY_TREE=a}),c=readFile("Style",function(a){STYLE_MASTER=a}),d=[],d.push(a),d.push(b),d.push(c),e.yield(Promise.all(d),2);initial(ABILITY_TREE);firebase.database().goOffline();firebase.database(appUsers).goOffline();e.jumpToEnd()})}
function scrollStyleList(){$("html,body").animate({scrollTop:$("#abilty_label").offset().top})}
var ABILITY_ICON_LIST={"\u81ea\u8eab\u5f37\u5316(\u30d0\u30d5)\u8155\u529b":"icon_buff_str","\u81ea\u8eab\u5f37\u5316(\u30d0\u30d5)\u4f53\u529b":"icon_buff_vit","\u81ea\u8eab\u5f37\u5316(\u30d0\u30d5)\u5668\u7528\u3055":"icon_buff_dex","\u81ea\u8eab\u5f37\u5316(\u30d0\u30d5)\u7d20\u65e9\u3055":"icon_buff_agi","\u81ea\u8eab\u5f37\u5316(\u30d0\u30d5)\u77e5\u529b":"icon_buff_int","\u81ea\u8eab\u5f37\u5316(\u30d0\u30d5)\u7cbe\u795e":"icon_buff_mnd","\u81ea\u8eab\u5f37\u5316(\u30d0\u30d5)\u611b":"icon_buff_ai",
"\u81ea\u8eab\u5f37\u5316(\u30d0\u30d5)\u9b45\u529b":"icon_buff_mi","\u6575\u5f31\u4f53\u5316(\u30c7\u30d0\u30d5)\u8155\u529b":"icon_debuff_str","\u6575\u5f31\u4f53\u5316(\u30c7\u30d0\u30d5)\u4f53\u529b":"icon_debuff_vit","\u6575\u5f31\u4f53\u5316(\u30c7\u30d0\u30d5)\u5668\u7528\u3055":"icon_debuff_dex","\u6575\u5f31\u4f53\u5316(\u30c7\u30d0\u30d5)\u7d20\u65e9\u3055":"icon_debuff_agi","\u6575\u5f31\u4f53\u5316(\u30c7\u30d0\u30d5)\u77e5\u529b":"icon_debuff_int","\u6575\u5f31\u4f53\u5316(\u30c7\u30d0\u30d5)\u7cbe\u795e":"icon_debuff_mnd",
"\u6575\u5f31\u4f53\u5316(\u30c7\u30d0\u30d5)\u611b":"icon_debuff_ai","\u6575\u5f31\u4f53\u5316(\u30c7\u30d0\u30d5)\u9b45\u529b":"icon_debuff_mi","\u6bd2":"icon_doku","\u6697\u95c7":"icon_kurayami","\u30b9\u30bf\u30f3":"icon_stan","\u30de\u30d2":"icon_mahi","\u7720\u308a":"icon_zzz","\u77f3\u5316":"icon_sekika","\u6df7\u4e71":"icon_konran","\u9b45\u4e86":"icon_miryo","\u72c2\u6226\u58eb":"icon_kyosenshi","\u6c17\u7d76":"icon_kizetsu"};
function initial(a){a=$jscomp.makeIterator(a);for(var b=a.next();!b.done;b=a.next()){b=b.value;var c=$("<li>");c.append('<a class="toggle menu parent">'+b.name+"</a>");for(var d=$('<ul class="inner child child01">'),e=$jscomp.makeIterator(b.list),f=e.next();!f.done;f=e.next()){var h=f.value;if(""!=h.name){f="";void 0!==ABILITY_ICON_LIST[b.name+h.name]?f=ABILITY_ICON_LIST[b.name+h.name]:void 0!==ABILITY_ICON_LIST[h.name]?f=ABILITY_ICON_LIST[h.name]:void 0!==ABILITY_ICON_LIST[h.name.replace("\u8010\u6027",
"")]&&(f=ABILITY_ICON_LIST[h.name.replace("\u8010\u6027","")]);if(""!==f){f=$("<span>").addClass("icon_xs_zokusei").addClass(f).addClass("text-nowrap").attr("style","padding-left:30px;").text(h.name);var l=$("<a>").addClass("toggle menu").append(f)}else l='<a class="toggle menu">'+h.name+"</a>";f=$("<li>");f.append(l);l=$('<ul class="inner child child02">');var k=0;h=$jscomp.makeIterator(h.list);for(var m=h.next();!m.done;m=h.next()){m=$jscomp.makeIterator(m.value.list);for(var n=m.next();!n.done;n=
m.next()){var p=n.value,q=void 0!==p.time&&""!==p.time&&null!==p.time?" "+getTime(p.time):"",r=void 0!==p.size&&""!==p.size&&null!==p.size?" "+p.size:"",t=" ("+p.Holders.length+")";n='<li class="abilityName" style="'+(0===k++%2?"background-color:aliceblue;":"")+'" abid="'+p.Id+'">';n+='<p style="text-align:left;float: left; margin-bottom:0px;">'+p.Name+t+"</p>";n+="<p style='text-align:right; margin-bottom:0px;'><small>"+p.when+q+r+"</small></p>";p=$jscomp.makeIterator(p.Holders);for(q=p.next();!q.done;q=
p.next())r=q.value,q=STYLE_MASTER[r],r=$("<button>").addClass(getStyleIconClass(q.Rarity)).attr("style",getImgUrl("style_icon/"+r+".png")+"width:40px; height:40px; background-size: 40px !important;"),q=$("<span>").addClass(getStyleIconBgClass(q.Rarity)).append(r),n+=q.html();n+="</li>";l.append(n)}}f.append(l);d.append(f)}else for(f=$jscomp.makeIterator(h.list),m=f.next();!m.done;m=f.next())for(l=$jscomp.makeIterator(m.value.list),n=l.next();!n.done;n=l.next())k=n.value,h=void 0!==k.time&&""!==k.time&&
null!==k.time?" "+getTime(k.time):"",d.append('<li class="abilityName" abid="'+k.Id+'"><p style="text-align:left;float: left;">'+k.Name+(" ("+k.Holders.length+")")+"</p><p style='text-align:right;'><small>"+k.when+h+(void 0!==k.size&&""!==k.size&&null!==k.size?" "+k.size:"")+"</small></p></li>")}c.append(d);$("#sp_skill_tree > ul").append(c)}}
function initialSkillTree(a){for(var b in a){var c={name:b,children:[]},d;for(d in a[b]){var e={name:d,children:[]},f;for(f in a[b][d]){for(var h={name:f,children:[]},l=$jscomp.makeIterator(a[b][d][f]),k=l.next();!k.done;k=l.next()){k=k.value;var m=k.time,n=k.Name+"("+k.when;void 0!==k.time&&""!==m&&(n+="/"+m+"("+getTime(m)+")");n+=")";h.children.push({name:n,id:k.Id})}e.children.push(h)}c.children.push(e)}data.children.push(c)}a=document.querySelector("svg").clientWidth;b=document.querySelector("svg").clientHeight;
root=d3.hierarchy(data);root.x0=b/2;root.y0=0;tree=d3.tree().size([b,a-160]);g=d3.select("svg").append("g").attr("transform","translate(80,0)");update(root);$(".node").each(function(a,b){0<a&&16>=a&&(toggle(b.__data__),update(b.__data__))})}
function displayAbilityHolder(a){$("#ability_holder_table").html("");$("#ability_holder_list").html("");for(key in a.Holders){var b=a.Holders[key],c=STYLE_MASTER[b];if(void 0!==c){var d=$("<div>").addClass("col-12 col-md-6 col-lg-4 style-bgcolor"),e=$("<div>").addClass("darkButton"),f=$("<small>").addClass("text-nowrap").append(c.Name+c.AnotherName);e.append(f.clone());f=$("<div>").addClass("style-skill-window small").attr("style","display:inline-block; padding: 10px 20px !important; width:200px; margin:0px;");
for(var h in c.StyleAbilityIds){var l=ABILITY_MASTER[c.StyleAbilityIds[h]];l=$("<span>").append(h+":"+l.Name).attr("data-toggle","tooltip").attr("data-placement","right").attr("data-html","true").attr("title",l.FlavorText.replace("\u3000","<br>"));f.append(l.clone());30!==h&&f.append("<br>")}l=$("<span>").addClass("icon_rare_large float-left").attr("style",getImgUrl("icon/icon_"+c.Rarity+".png")+"width:30px; height:30px; background-size:cover; position:absolute; z-index:3;");b=$("<button>").addClass(getStyleIconClass(c.Rarity)).attr("style",
getImgUrl("style_icon/"+b+".png"));c=$("<span>").addClass(getStyleIconBgClass(c.Rarity)).append(b);b=$("<div>").attr("style","display:inline-block;").append(l).append(c.clone());d.append(e);d.append(f);d.append(b);$("#ability_holder_table").append(d);$("#ability_holder_list").append(c.clone());$('[data-toggle="tooltip"]').tooltip()}}};