var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return c?c.call(a):$jscomp.arrayIterator(a)};
var NORMAL_ATTACK={Name:"\u901a\u5e38\u653b\u6483",AttackArea:"\u6575\u5358\u4f53",ConsumeBp:0,AutoUseBp:0,UseBp:0,isNotUseAuto:!1,UseCount:0,isKeisho:0,SkillIryoku:7},BASE_SKILL_LIST=[],USE_SKILL_LIST=[],NOW_CHAR={},NOW_STYLE={};
$(document).ready(function(a){function c(b){a("#skillAreaParent").show();a(".skillChoiceArea").show();a("#culcStart").show();1<NOW_CHAR.Holders.length&&a("#keishoKaijo").show();a(".skillChoice").html("");a("table#skillArea > tbody *").remove();a("table#skillArea > tfoot *").remove();a("table#culcSummary tbody *").remove();NOW_STYLE=STYLE_MASTER[b];for(var d={S:"STR",D:"DEX",A:"AGI",I:"INT"},c=$jscomp.makeIterator(["S","D","A","I"]),e=c.next();!e.done;e=c.next()){e=e.value;NOW_STYLE["L"+e]=99===NOW_STYLE["L"+
e]?0:NOW_STYLE["L"+e];var f=Math.floor((NOW_STYLE["L"+e]+LIMIT_BASE)*(1+NOW_STYLE["Lv50"+e].Per/100))+NOW_STYLE["Lv50"+e].Bonus;a("#char"+d[e]).val(f)}displaySkillTable(b)}dispChar(CHAR_MASTER,device);readFile("Enemy",function(b){ENEMY_DATA=b;for(var d in ENEMY_DATA)b=ENEMY_DATA[d],$option=a("<option>",{value:d,text:b.quest+" "+b.name+" \u4f53:"+b.vit+" \u7cbe:"+b.mnd}),a("#enemy_vit").append($option)});initialHide();setSlider();a(".filterList").click(function(){a(".weaponList").addClass("d-none");
var b=a(this).attr("href").substr(1);a(this).parent().hasClass("filterActive")?(a(".sp-slides-container").removeClass("d-none"),a(".filterList").each(function(){a(this).parent().removeClass("filterActive")})):(a(".sp-slides-container").addClass("d-none"),a("#_"+b).removeClass("d-none"),a(".filterList").each(function(){a(this).parent().removeClass("filterActive")}),a(this).parent().toggleClass("filterActive"))});a(document).on("click","#OPTION_BUTTON",function(){a("#OPTION_BODY").slideToggle(200)});
a(document).on("click",".char",function(){a("#styleLabel").show();var b=a(this).attr("data-id");NOW_CHAR=CHAR_MASTER[b];a("#CHAR_NAME").text(NOW_CHAR.Name);a("html,body").animate({scrollTop:a("#styleLabel").offset().top},500,"swing");a("#skillAreaParent").hide();a("#culcStart").hide();a("#keishoKaijo").hide();a(".skillChoice").html("");a("table#skillArea > tbody *").remove();a("table#skillArea > tfoot *").remove();a("#keisyoSkill").html("");a(".culcAfter").hide();a("table#culcSummary tbody *").remove();
a("#culcDetail").html("");a(".char-selected").each(function(b,c){a(this).removeClass("char-winner");a(this).addClass("char-aruku")});a(this).removeClass("char-aruku");a(this).addClass("char-winner").addClass("char-selected").addClass("dot");displayStyleList(b);c(NOW_CHAR.Holders[0]);gtag("event","clickChar",{event_category:"auto",event_label:NOW_CHAR.Name,value:1})});a(document).on("click",".style",function(){var b=a(this).attr("data-id");c(b);gtag("event","clickStyle",{event_category:"auto",event_label:NOW_STYLE.Name+
NOW_STYLE.AnotherName,value:1})});a(document).on("click","#keishoKaijo",function(){a("#noKeisho").show();a("table#skillArea > tfoot").html("");USE_SKILL_LIST=BASE_SKILL_LIST.slice()});a(document).on("click",".keishoSkill",function(){a("#x").remove();a(this).children(".floatLeft").append("<span id='x' class='icon_keisho_e'></span>");a("#noKeisho").hide();a("table#skillArea > tfoot").html("");var b=Object.assign({},SKILL_MASTER[a(this).attr("data-id")]);b.isKeisho=!0;b.UseBp=b.ConsumeBp;addSkillArea(b,
"table#skillArea tfoot");USE_SKILL_LIST=BASE_SKILL_LIST.slice();USE_SKILL_LIST.push(b)});a("#showJoken").click(function(){gtag("event","showJoken",{event_category:"auto",event_label:"none",value:1})});a("#culcStart").click(function(){gtag("event","clickCalc",{event_category:"auto",event_label:NOW_STYLE.Name+NOW_STYLE.AnotherName,value:1});var b=displayResult();a("html,body").animate({scrollTop:a("#culcStart").offset().top},500,"swing");var d=NOW_STYLE.Name+" "+NOW_STYLE.Rarity+" "+NOW_STYLE.AnotherName+
"%0D%0A";d+=""+a("#avgDamage").text()+"%0D%0A";b=$jscomp.makeIterator(b);for(var c=b.next();!c.done;c=b.next())if(c=c.value,"0"!=c.Id){var e=Number(c.ConsumeBp)-Number(c.AutoUseBp),f=c.UseCount,l="";c.isKeisho&&(l="[\u7d99\u627f]");d+="\u30fb"+c.Name+l+" \u899a\u9192:"+e+" \u767a\u52d5:"+f+"%0D%0A"}d="https://twitter.com/intent/tweet?text="+d+"&url=https://nao-romasaga.github.io/auto.html&hashtags=\u5168\u529b\u30aa\u30fc\u30c8\u30b7\u30df\u30e5\u30ec\u30fc\u30bf";a(".my-twitter-share-button").attr("href",
d)});a(".switch .toggle").click(function(){a(this).toggleClass("accordionActive").next().slideToggle(300)});a("#enemy_vit").change(function(){var b=a("#enemy_vit").val();if("x"===b){var d=$jscomp.makeIterator("zan da totsu netsu rei rai in you".split(" "));for(b=d.next();!b.done;b=d.next())setTaisei(a("#taisei_"+b.value),0)}else{d=ENEMY_DATA[b];type=a("#type").val();-1<a.inArray(type,"hi mizu tsuchi kaze hikari yami".split(" "))?a("#vit").val(d.mnd):a("#vit").val(d.vit);var c=$jscomp.makeIterator("zan da totsu netsu rei rai in you".split(" "));
for(b=c.next();!b.done;b=c.next())b=b.value,setTaisei(a("#taisei_"+b),d[b])}})});
function displayStyleList(a){$(".styleChoiceArea").show();$("#styleChoice").html("");a=$jscomp.makeIterator(CHAR_MASTER[a].Holders);for(var c=a.next();!c.done;c=a.next()){var b=c.value;c=STYLE_MASTER[b];console.log(c);var d=Object.assign({},c);d.StyleBonusLv50STR=d.L5S;d.StyleBonusLv50STR=d.L5S;d.StyleBonusLv50DEX=d.L5D;d.StyleBonusLv50AGI=d.L5A;d.StyleBonusLv50INT=d.L5I;d.StyleBonusLv1STR=0;d.StyleBonusLv1DEX=0;d.StyleBonusLv1AGI=0;d.StyleBonusLv1INT=0;addStatus=culcStyleAddintional(d);c.Lv50S=addStatus["\u8155\u529b"][50];
c.Lv50D=addStatus["\u5668\u7528\u3055"][50];c.Lv50A=addStatus["\u7d20\u65e9\u3055"][50];c.Lv50I=addStatus["\u77e5\u529b"][50];c.hasRenki=!1;for(var g in c.StyleAbilityIds)-1<["ID29e0d388","ID29dc40a0"].indexOf(c.StyleAbilityIds[g])&&(c.hasRenki=!0);b=$("<button>").addClass("style").addClass(getStyleIconClass(c.Rarity)).attr("style",getImgUrl("style_icon/"+b+".png")).attr("data-id",b);c=$("<span>").addClass(getStyleIconBgClass(c.Rarity)).append(b);$("#styleChoice").append(c)}}
var noKeishoTr="<tr class='keishoSkillTr' id='noKeisho'><td colspan=5 class='text-center'>\u7d99\u627f\u6280\u672a\u8a2d\u5b9a</td></tr>",noKeishoTd="<td colspan=5 class='text-center'>\u7d99\u627f\u6280\u672a\u8a2d\u5b9a</td>";
function displaySkillTable(a){$(".skillChoice").html("");$("table#skillArea > tbody *").remove();$("#keisyoSkill").html("");BASE_SKILL_LIST=[];kakuseiData={};var c=STYLE_MASTER[a],b=getImgUrl("style_cutin/"+a+".png");b=$("<span>").addClass("cutin").attr("style",b+" width: 250px; height:62px;");$("#skillCutin").append(b);c=$jscomp.makeIterator(c.SkillIds);for(b=c.next();!b.done;b=c.next())b=Object.assign({},SKILL_MASTER[b.value]),b.isKeisho=!1,addSkillArea(b,"table#skillArea tbody"),b.UseBp=b.ConsumeBp,
BASE_SKILL_LIST.push(b);$("table#skillArea tbody").append(noKeishoTr);USE_SKILL_LIST=BASE_SKILL_LIST.slice();var d=[];$(".style").each(function(){var b=$(this).attr("data-id");console.log(b);$(this).parent().addClass("opacity_nocheck");if(a===b)$(this).parent().removeClass("opacity_nocheck");else{b=STYLE_MASTER[b];for(var c=$jscomp.makeIterator(b.SkillIds),f=c.next();!f.done;f=c.next())if(f=f.value,!(-1<d.indexOf(f))){d.push(f);var l=SKILL_MASTER[f];console.log(b.AnotherName,l);0===$(".kakusei"+f).length&&
(f=kakuseiLabel(l),$("#keisyoSkill").append(f))}}})}
function kakuseiLabel(a){var c=$("<button>").addClass("skill").addClass("keishoSkill");c.removeAttr("id").attr("data-id",a.Id);var b=$("<p>").addClass("floatLeft"),d=ICON_LIST[a.BattleType],g=$("<span>").addClass("icon_xs").text("\u3000");g.attr("style",getImgUrl("icon/"+d+".png"));$(b).append(g);a.AttackAttributes.split(",").forEach(function(a){var c=$("<span>").addClass("icon_xs").text("\u3000");c.attr("style",getImgUrl("icon/"+ICON_LIST[a]+".png"));$(b).append(c)});$(b).append(a.Name);$(b).append("(");
d=[];for(g=1;g<=a.Kakusei;g++)d.push("\u25c7");$(b).append(d.join(" "));$(b).append(")");d=$("<p>").addClass("floatRight");$(d).append(" \u899a\u9192:"+a.Kakusei);$(d).append(" BP:"+a.ConsumeBp);$(d).append(" "+a.PowerGrade+"("+a.SkillIryoku+")");c.append(b).append(d);return c}var kakuseiData={};
$(document).on("click",".kakuseiCheck",function(){var a=$(this).attr("data-id"),c=Number($(this).attr("data-kakusei"));kakuseiData[a]===c&&(c=0);kakuseiData[a]=c;var b=$(".nowBP"+a).attr("data-bp");b-=c;$(".nowBP"+a).html(b);$(".kakusei"+a).each(function(){$(this).attr("data-kakusei")<=c?$(this).html("\u25c6"):$(this).html("\u25c7")});for(var d in USE_SKILL_LIST)a=USE_SKILL_LIST[d],a.UseBp=Number($(".nowBP"+a.Id).text())});
function addSkillArea(a,c){for(var b=$("<span>").addClass("skill").attr("data-id",a.Id).html(a.Name),d=[],g=1;g<=a.Kakusei;g++){var e=$("<button>").addClass("kakuseiCheck").addClass("floatLeft").addClass("kakusei"+a.Id).attr("data-id",a.Id).attr("data-kakusei",g);$(e).html("\u25c7");d.push(e)}g=$("<span>").addClass("icon_xs").text("\u3000").attr("style",getImgUrl("icon/"+ICON_LIST[a.BattleType]+".png"));var f=$("<td>").append(g);a.AttackAttributes.split(",").forEach(function(a){a=$("<span>").addClass("icon_xs").text("\u3000").attr("style",
getImgUrl("icon/"+ICON_LIST[a]+".png"));f.append(a)});b=$("<td>").append(b);g=$("<td>");d=$jscomp.makeIterator(d);for(e=d.next();!e.done;e=d.next())g.append(e.value);d='<span class="nowBP'+a.Id+'" data-id="'+a.Id+'" data-bp="'+a.ConsumeBp+'" >'+a.ConsumeBp+"</span>";d+="<br>";d=$("<td>").append(d);e=$("<td>").append(a.PowerGrade+"("+a.SkillIryoku+")");b=$("<tr>").append(f).append(b).append(g).append(d).append(e);$(c).append(b)}
function displayResult(){var a=USE_SKILL_LIST.slice();a.unshift(Object.assign({},NORMAL_ATTACK));rewriteBP(a);setSkillDamage(a);culcAutoMode(a);return a}var dummy={Id:0,AttackArea:"\u81ea\u8eab",UseBp:99,AutoUseBp:99};
function rewriteBP(a){""===$("table#skillArea > tfoot").html()&&a.push(Object.assign({},dummy));var c=a[1],b=a[2],d=a[3],g=a[4];c.isNotUseAuto=isNotUseAuto(c);b.isNotUseAuto=isNotUseAuto(b);d.isNotUseAuto=isNotUseAuto(d);g.isNotUseAuto=isNotUseAuto(g);c.AutoUseBp=c.isNotUseAuto?99:c.UseBp;b.AutoUseBp=b.isNotUseAuto?99:b.UseBp;d.AutoUseBp=d.isNotUseAuto?99:d.UseBp;g.AutoUseBp=g.isNotUseAuto?99:g.UseBp;g.AutoUseBp===d.AutoUseBp&&(d.AutoUseBp=99);g.AutoUseBp===b.AutoUseBp&&(b.AutoUseBp=99);g.AutoUseBp===
c.AutoUseBp&&(c.AutoUseBp=99);c.AutoUseBp===b.AutoUseBp?b.AutoUseBp=99:b.AutoUseBp===d.AutoUseBp&&(d.AutoUseBp=99);c.UseCount=0;b.UseCount=0;d.UseCount=0;g.UseCount=0;a.sort(function(a,b){return a.UseBp>b.UseBp||a.UseBp===b.UseBp&&a.isKeisho>b.isKeisho?-1:1})}function isNotUseAuto(a){return"\u5473\u65b9\u5358\u4f53"===a.AttackArea||"\u81ea\u8eab"===a.AttackArea||"ID77973c5"===a.Id||"ID777ed23"===a.Id?!0:!1}var CULC_DAMAGE_PARAM={};
function setSkillDamage(a){$("#JOKEN_LIST").html("");var c=0;for(g in NOW_STYLE.StyleAbilityIds){var b=NOW_STYLE.StyleAbilityIds[g];-1<["ID29d93221","ID29d9322e"].indexOf(b)?c+=15:-1<["ID29d93222","ID29d9322f"].indexOf(b)?c+=10:-1<["ID29d93223","ID29d93230"].indexOf(b)?c+=5:"ID29d93224"===b&&(c+=2)}var d=85;var g=99;var e=b=0,f={"\u65ac":"zan","\u6253":"da","\u7a81":"totsu","\u71b1":"netsu","\u51b7":"rei","\u96f7":"rai","\u9670":"in","\u967d":"you"},l=$("<li>").html("\u25bc\u5171\u901a\u6761\u4ef6\u25bc");
e=$("<li>").html("\u6b66\u5668\u5a01\u529b/30 \u6280\u30e9\u30f3\u30af/"+g+" \u30de\u30b9\u30bf\u30fc\u30ec\u30d9\u30eb Lv27-Lv28/7% \u30a2\u30d3\u30ea\u30c6\u30a3\u88dc\u6b63/"+c+"%");var h=$("<li>").html("\u25bc\u5404\u6280\u500b\u5225\u6761\u4ef6\u25bc");$("#JOKEN_LIST").append(l).append(e).append(h);l={};a=$jscomp.makeIterator(a);for(e=a.next();!e.done;l={$jscomp$loop$prop$row$19:l.$jscomp$loop$prop$row$19},e=a.next()){h=e.value;"\u901a\u5e38\u653b\u6483"===h.Name&&(h.BattleType=NOW_CHAR.WeaponType,
h.AttackAttributes=WEPON_ATTR[NOW_CHAR.WeaponType],g=1);var q=h.BattleType,m="",n="\u4f53\u529b";"\u4f53\u8853"===q?(type="tai",e=$("#charSTR").val(),b=$("#charAGI").val(),m="\u8155/"+e+", \u901f/"+b):"\u9283"===q?(type="ju",e=$("#charDEX").val(),m="\u5668/"+e):(type="other","\u8853"===h.SkillType?(console.log("use int"),e=$("#charINT").val(),m="\u77e5/"+e,n="\u7cbe\u795e"):-1<["\u5c0f\u5263","\u5f13"].indexOf(q)?(console.log("use dex"),e=$("#charDEX").val(),m="\u5668/"+e):(console.log("use str"),
e=$("#charSTR").val(),m="\u8155/"+e));var p=h.AttackAttributes,r=999;d=$("#enemy_vit").val();void 0===p&&console.log(h);var t=p;"x"!==d&&void 0!==p?(l.$jscomp$loop$prop$row$19=ENEMY_DATA[d],d="\u8853"===h.SkillType?l.$jscomp$loop$prop$row$19.mnd:l.$jscomp$loop$prop$row$19.vit,console.log(p,p.split(","),h),p.split(",").forEach(function(a){return function(b){console.log(p,b,f[b],a.$jscomp$loop$prop$row$19[f[b]]);r>a.$jscomp$loop$prop$row$19[f[b]]&&(r=a.$jscomp$loop$prop$row$19[f[b]],t=b)}}(l))):(d=
85,r=0);n+="/"+d;0<h.SkillIryoku?(h.culcDamage=damage(type,e,b,30,h.SkillIryoku,g,d,7,c,r,6),console.log(h.Name,q,h.SkillType,"culc",type,"STR:",e,b,30,h.SkillIryoku,g,d,7,c,r,6)):h.culcDamage=0;e=$("<li>").html("\n        ["+h.AttackAttributes+"]\n        "+h.Name+"\n        \u5a01\u529b("+h.SkillIryoku+")\n        "+m+"\n        \u6575"+n+"\n        \u6575\u8010\u6027 "+t+"/"+r+"\n        ");void 0!==h.Name&&$("#JOKEN_LIST").append(e)}}
function culcAutoMode(a){var c=NOW_CHAR.WeaponType;$(".culcAfter").show();$("table#culcSummary tbody *").remove();$("#culcDetail").html("");var b=$("table#culcSummary tbody");0===a[0].Id&&(a=a.slice(1));var d=$("#culcDetail"),g="\u30b7\u30df\u30e5\u30ec\u30fc\u30b7\u30e7\u30f3\u7d50\u679c",e=0;NOW_STYLE.hasRenki&&(g+="<br>\u7df4\u6c17\u9ad8\u63da/\u547c\u5438(25%)\u767a\u52d5\u6642\u306fBP\u306b(+1)\u3068\u8868\u793a\u3055\u308c\u307e\u3059",e=1);d.append('<label class="badge badge-pill badge-light" style="width:90%">'+
g+"</label>");var f=7;g=$("#SET_TURN").val();var l=0;e=[0,0,0,e];for(var h={},q=1;q<=g;h={$jscomp$loop$prop$left$21:h.$jscomp$loop$prop$left$21},q++){var m=$("<div>").addClass("darkButton").addClass("keishoSkillArea");h.$jscomp$loop$prop$left$21=$("<p>").addClass("floatLeft");for(var n=$("<p>").addClass("floatRight"),p=Math.floor(Math.random()*e.length),r=f+=3,t="",v=99,w={},u=$jscomp.makeIterator(a),k=u.next();!k.done;k=u.next())k=k.value,-1<["ID77afa6a","ID7766685","ID7766685"].indexOf(k.Id)&&(v=
k.UseBp,w=k);u=!1;var x=$jscomp.makeIterator(a);for(k=x.next();!k.done;k=x.next())if(k=k.value,k!==w&&(f>=v&&!u?(t=" <small>("+w.Name+")</small>",w.UseCount++,u=!0):k.isNotUseAuto&&f>=k.UseBp&&(t=" <small>("+k.Name+")</small>",k.UseCount++),f>=k.AutoUseBp)){f-=k.AutoUseBp;h.$jscomp$loop$prop$left$21.append(q+'<span class="d-md-none">T</span><span class="d-none d-md-inline">Turn</span>');"sp"!==device&&(void 0===k.AttackAttributes&&(k.BattleType=c,k.AttackAttributes=WEPON_ATTR[c]),v=$("<span>").addClass("icon_xs").text("\u3000").attr("style",
getImgUrl("icon/"+ICON_LIST[k.BattleType]+".png")),h.$jscomp$loop$prop$left$21.append(v),k.AttackAttributes.split(",").forEach(function(a){return function(b){b=$("<span>").addClass("icon_xs").text("\u3000").attr("style",getImgUrl("icon/"+ICON_LIST[b]+".png"));a.$jscomp$loop$prop$left$21.append(b)}}(h)));h.$jscomp$loop$prop$left$21.append(" "+k.Name);"sp"!==device&&h.$jscomp$loop$prop$left$21.append(" <span class='d-none d-md-inline'>\u6d88\u8cbb</span>BP:"+k.AutoUseBp);h.$jscomp$loop$prop$left$21.append(t);
n.append("<small>\u30c0\u30e1\u30fc\u30b8:"+k.culcDamage.toLocaleString()+"</small>");n.append(" BP:"+r+" > ");k.UseCount++;break}0<e[p]?(l++,f++,n.append(f+"(+1)"),m.removeClass("darkButton").addClass("darkButtonShine")):n.append(f);m.append(h.$jscomp$loop$prop$left$21).append(n);d.append(m)}c=0;d={};a=$jscomp.makeIterator(a);for(k=a.next();!k.done;d={$jscomp$loop$prop$td$23:d.$jscomp$loop$prop$td$23},k=a.next())f=k.value,b.append("<tr>"),d.$jscomp$loop$prop$td$23=$("<td>").addClass("text-nowrap"),
"sp"!==device&&void 0!==f.AttackAttributes&&(e=$("<span>").addClass("icon_xs").text("\u3000").attr("style",getImgUrl("icon/"+ICON_LIST[f.BattleType]+".png")),d.$jscomp$loop$prop$td$23.append(e),f.AttackAttributes.split(",").forEach(function(a){return function(b){b=$("<span>").addClass("icon_xs").text("\u3000").attr("style",getImgUrl("icon/"+ICON_LIST[b]+".png"));a.$jscomp$loop$prop$td$23.append(b)}}(d))),d.$jscomp$loop$prop$td$23.append(f.Name),b.append(d.$jscomp$loop$prop$td$23),b.append("<td>"+
f.UseBp+"</td>"),b.append("<td>"+f.UseCount+"</td>"),b.append('<td class="d-none d-md-inline">'+f.SkillIryoku+"</td>"),b.append("<td>"+number_format(f.culcDamage,0)+"</td>"),99!==f.AutoUseBp&&(c+=f.culcDamage*Number(f.UseCount)),b.append("</tr>");b.append("<tr>");b.append("<td colspan=5 class='text-center' id='avgDamage' style='font-size:200%'>\u5e73\u5747\u30c0\u30e1\u30fc\u30b8 "+Math.round(c/g).toLocaleString()+"</td>");b.append("</tr>");NOW_STYLE.hasRenki&&(b.append("<tr>"),b.append("<td colspan=5 class='text-center'>\u7df4\u6c17\u9ad8\u63da/\u547c\u5438 \u767a\u52d5\u56de\u6570 = "+
l+"\u56de</td>"),b.append("</tr>"));b.append("<tr style='border-top: 1px solid'>");b.append("<td colspan=5 class='text-center'>\u5408\u8a08\u30c0\u30e1\u30fc\u30b8 = "+c+"</td>");b.append("</tr>")}function initialHide(){$(".culcAfter").hide();$("#keishoKaijo").hide();$("#skillAreaParent").hide();$("#culcStart").hide();$(".styleChoiceArea").hide();$(".skillChoiceArea").hide()};