var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return c?c.call(a):$jscomp.arrayIterator(a)};
var NORMAL_ATTACK={Name:"\u901a\u5e38\u653b\u6483",AttackArea:"\u6575\u5358\u4f53",ConsumeBp:0,AutoUseBp:0,UseBp:0,isNotUseAuto:!1,UseCount:0,isKeisho:0,SkillIryoku:7},BASE_SKILL_LIST=[],USE_SKILL_LIST=[],NOW_CHAR={},NOW_STYLE={};
$(document).ready(function(a){dispChar(CHAR_MASTER,device);readFile("Enemy",function(b){ENEMY_DATA=b;for(var c in ENEMY_DATA)b=ENEMY_DATA[c],$option=a("<option>",{value:c,text:b.quest+" "+b.name+" \u4f53:"+b.vit+" \u7cbe:"+b.mnd}),a("#enemy_vit").append($option)});initialHide();setSlider();if(""!==location.search){var c=location.search.substr(3);if(void 0!==STYLE_MASTER[c]){var d=STYLE_MASTER[c].cId;document.title="\u3010\u30ed\u30de\u30b5\u30acRS\u3011"+STYLE_MASTER[c].Name+"["+STYLE_MASTER[c].Rarity+
"]\u306e\u5168\u529bAUTO\u30b7\u30df\u30e5\u30ec\u30fc\u30bf\u30fc";var b=STYLE_MASTER[c].Name+" "+STYLE_MASTER[c].Rarity+" "+STYLE_MASTER[c].AnotherName+" \u306e\u5168\u529b\u30aa\u30fc\u30c8\u30b7\u30df\u30e5\u30ec\u30fc\u30bf\u30fc\u3067\u3059\u3002\u6280\u306e\u899a\u9192\u3084\u7d99\u627f\u306b\u3054\u5229\u7528\u304f\u3060\u3055\u3044\u3002\u30c0\u30e1\u30fc\u30b8\u8a08\u7b97\u3082\u3067\u304d\u307e\u3059\u3002";a("meta[name='description']").attr("content",b);clickChar(d,c)}}a(".filterList").click(function(){a(".weaponList").addClass("d-none");
var b=a(this).attr("href").substr(1);a(this).parent().hasClass("filterActive")?(a(".sp-slides-container").removeClass("d-none"),a(".filterList").each(function(){a(this).parent().removeClass("filterActive")})):(a(".sp-slides-container").addClass("d-none"),a("#_"+b).removeClass("d-none"),a(".filterList").each(function(){a(this).parent().removeClass("filterActive")}),a(this).parent().toggleClass("filterActive"))});a(document).on("click","#OPTION_BUTTON",function(){a("#OPTION_BODY").slideToggle(200)});
a(document).on("click",".char",function(){var b=a(this).attr("data-id");clickChar(b);gtag("event","clickChar",{event_category:"auto",event_label:NOW_CHAR.Name,value:1})});a(document).on("click",".style",function(){var b=a(this).attr("data-id");clickStyle(b);gtag("event","clickStyle",{event_category:"auto",event_label:NOW_STYLE.Name+NOW_STYLE.AnotherName,value:1})});a(document).on("click","#keishoKaijo",function(){a("#noKeisho").show();a("table#skillArea > tfoot").html("");USE_SKILL_LIST=BASE_SKILL_LIST.slice()});
a(document).on("click",".keishoSkill",function(){a("#x").remove();a(this).children(".floatLeft").append("<span id='x' class='icon_keisho_e'></span>");a("#noKeisho").hide();a("table#skillArea > tfoot").html("");var b=Object.assign({},SKILL_MASTER[a(this).attr("data-id")]);b.isKeisho=!0;b.UseBp=b.ConsumeBp;addSkillArea(b,"table#skillArea tfoot");USE_SKILL_LIST=BASE_SKILL_LIST.slice();USE_SKILL_LIST.push(b)});a("#showJoken").click(function(){gtag("event","showJoken",{event_category:"auto",event_label:"none",
value:1})});a("#culcStart").click(function(){gtag("event","clickCalc",{event_category:"auto",event_label:NOW_STYLE.Name+NOW_STYLE.AnotherName,value:1});var b=displayResult();a("html,body").animate({scrollTop:a("#culcStart").offset().top},500,"swing");var c=NOW_STYLE.Name+" "+NOW_STYLE.Rarity+" "+NOW_STYLE.AnotherName+"%0D%0A";c+=""+a("#avgDamage").text()+"%0D%0A";b=$jscomp.makeIterator(b);for(var d=b.next();!d.done;d=b.next())if(d=d.value,"0"!=d.Id){var l=Number(d.ConsumeBp)-Number(d.AutoUseBp),g=
d.UseCount,m="";d.isKeisho&&(m="[\u7d99\u627f]");c+="\u30fb"+d.Name+m+" \u899a\u9192:"+l+" \u767a\u52d5:"+g+"%0D%0A"}c="https://twitter.com/intent/tweet?text="+c+"&url=https://nao-romasaga.github.io/auto.html&hashtags=\u5168\u529b\u30aa\u30fc\u30c8\u30b7\u30df\u30e5\u30ec\u30fc\u30bf";a(".my-twitter-share-button").attr("href",c)});a(".switch .toggle").click(function(){a(this).toggleClass("accordionActive").next().slideToggle(300)});a("#enemy_vit").change(function(){var b=a("#enemy_vit").val();if("x"===
b){var c=$jscomp.makeIterator("zan da totsu netsu rei rai in you".split(" "));for(b=c.next();!b.done;b=c.next())setTaisei(a("#taisei_"+b.value),0)}else{c=ENEMY_DATA[b];type=a("#type").val();-1<a.inArray(type,"hi mizu tsuchi kaze hikari yami".split(" "))?a("#vit").val(c.mnd):a("#vit").val(c.vit);var d=$jscomp.makeIterator("zan da totsu netsu rei rai in you".split(" "));for(b=d.next();!b.done;b=d.next())b=b.value,setTaisei(a("#taisei_"+b),c[b])}})});
function clickChar(a,c){c=void 0===c?"":c;$("#styleLabel").show();NOW_CHAR=CHAR_MASTER[a];$("#RANK_LINK").attr("href","./ourchar.html?c="+a);$(".CHAR_NAME").text(NOW_CHAR.Name);$("html,body").animate({scrollTop:$("#styleLabel").offset().top},500,"swing");$("#skillAreaParent").hide();$("#culcStart").hide();$("#keishoKaijo").hide();$(".skillChoice").html("");$("table#skillArea > tbody *").remove();$("table#skillArea > tfoot *").remove();$("#keisyoSkill").html("");$(".culcAfter").hide();$("table#culcSummary tbody *").remove();
$("#culcDetail").html("");$(".char-selected").each(function(a,b){$(this).removeClass("char-winner");$(this).addClass("char-aruku")});$(this).removeClass("char-aruku");$(this).addClass("char-winner").addClass("char-selected").addClass("dot");displayStyleList(a);c=""!==c?c:NOW_CHAR.Holders[0];clickStyle(c)}
function clickStyle(a){NOW_STYLE=STYLE_MASTER[a];$("#skillAreaParent").show();$(".skillChoiceArea").show();$("#STYLE_LINK").attr("href","./style.html?s="+a);$("#culcStart").show();1<NOW_CHAR.Holders.length&&$("#keishoKaijo").show();$(".skillChoice").html("");$("table#skillArea > tbody *").remove();$("table#skillArea > tfoot *").remove();$("table#culcSummary tbody *").remove();for(var c={S:"STR",D:"DEX",A:"AGI",I:"INT"},d=$jscomp.makeIterator(["S","D","A","I"]),b=d.next();!b.done;b=d.next()){b=b.value;
NOW_STYLE["L"+b]=99===NOW_STYLE["L"+b]?0:NOW_STYLE["L"+b];var e=Math.floor((NOW_STYLE["L"+b]+LIMIT_BASE)*(1+NOW_STYLE["Lv50"+b].Per/100))+NOW_STYLE["Lv50"+b].Bonus;$("#char"+c[b]).val(e)}displaySkillTable(a)}
function displayStyleList(a){$(".styleChoiceArea").show();$("#styleChoice").html("");a=$jscomp.makeIterator(CHAR_MASTER[a].Holders);for(var c=a.next();!c.done;c=a.next()){var d=c.value;c=STYLE_MASTER[d];var b=Object.assign({},c);b.StyleBonusLv50STR=b.L5S;b.StyleBonusLv50STR=b.L5S;b.StyleBonusLv50DEX=b.L5D;b.StyleBonusLv50AGI=b.L5A;b.StyleBonusLv50INT=b.L5I;b.StyleBonusLv1STR=0;b.StyleBonusLv1DEX=0;b.StyleBonusLv1AGI=0;b.StyleBonusLv1INT=0;addStatus=culcStyleAddintional(b);c.Lv50S=addStatus["\u8155\u529b"][50];
c.Lv50D=addStatus["\u5668\u7528\u3055"][50];c.Lv50A=addStatus["\u7d20\u65e9\u3055"][50];c.Lv50I=addStatus["\u77e5\u529b"][50];c.hasRenki=!1;for(var e in c.StyleAbilityIds)-1<["ID29e0d388","ID29dc40a0"].indexOf(c.StyleAbilityIds[e])&&(c.hasRenki=!0);d=$("<button>").addClass("style").addClass(getStyleIconClass(c.Rarity)).attr("style",getImgUrl("style_icon/"+d+".png")).attr("data-id",d);c=$("<span>").addClass(getStyleIconBgClass(c.Rarity)).append(d);$("#styleChoice").append(c)}}
var noKeishoTr="<tr class='keishoSkillTr' id='noKeisho'><td colspan=5 class='text-center'>\u7d99\u627f\u6280\u672a\u8a2d\u5b9a</td></tr>",noKeishoTd="<td colspan=5 class='text-center'>\u7d99\u627f\u6280\u672a\u8a2d\u5b9a</td>";
function displaySkillTable(a){$(".skillChoice").html("");$("table#skillArea > tbody *").remove();$("#keisyoSkill").html("");BASE_SKILL_LIST=[];kakuseiData={};var c=STYLE_MASTER[a],d=getImgUrl("style_cutin/"+a+".png");d=$("<span>").addClass("cutin").attr("style",d+" width: 250px; height:62px;");$("#skillCutin").append(d);c=$jscomp.makeIterator(c.SkillIds);for(d=c.next();!d.done;d=c.next())d=Object.assign({},SKILL_MASTER[d.value]),d.isKeisho=!1,addSkillArea(d,"table#skillArea tbody"),d.UseBp=d.ConsumeBp,
BASE_SKILL_LIST.push(d);$("table#skillArea tbody").append(noKeishoTr);USE_SKILL_LIST=BASE_SKILL_LIST.slice();var b=[];$(".style").each(function(){var c=$(this).attr("data-id");$(this).parent().addClass("opacity_nocheck");if(a===c)$(this).parent().removeClass("opacity_nocheck");else{c=$jscomp.makeIterator(STYLE_MASTER[c].SkillIds);for(var d=c.next();!d.done;d=c.next())if(d=d.value,!(-1<b.indexOf(d))){b.push(d);var k=SKILL_MASTER[d];0===$(".kakusei"+d).length&&(d=kakuseiLabel(k),$("#keisyoSkill").append(d))}}})}
function kakuseiLabel(a){var c=$("<button>").addClass("skill").addClass("keishoSkill");c.removeAttr("id").attr("data-id",a.Id);var d=$("<p>").addClass("floatLeft"),b=ICON_LIST[a.BattleType],e=$("<span>").addClass("icon_xs").text("\u3000");e.attr("style",getImgUrl("icon/"+b+".png"));$(d).append(e);a.AttackAttributes.split(",").forEach(function(a){var b=$("<span>").addClass("icon_xs").text("\u3000");b.attr("style",getImgUrl("icon/"+ICON_LIST[a]+".png"));$(d).append(b)});$(d).append(a.Name);$(d).append("(");
b=[];for(e=1;e<=a.Kakusei;e++)b.push("\u25c7");$(d).append(b.join(" "));$(d).append(")");b=$("<p>").addClass("floatRight");$(b).append(" \u899a\u9192:"+a.Kakusei);$(b).append(" BP:"+a.ConsumeBp);$(b).append(" "+a.PowerGrade+"("+a.SkillIryoku+")");c.append(d).append(b);return c}var kakuseiData={};
$(document).on("click",".kakuseiCheck",function(){var a=$(this).attr("data-id"),c=Number($(this).attr("data-kakusei"));kakuseiData[a]===c&&(c=0);kakuseiData[a]=c;var d=$(".nowBP"+a).attr("data-bp");d-=c;$(".nowBP"+a).html(d);$(".kakusei"+a).each(function(){$(this).attr("data-kakusei")<=c?$(this).html("\u25c6"):$(this).html("\u25c7")});for(var b in USE_SKILL_LIST)a=USE_SKILL_LIST[b],a.UseBp=Number($(".nowBP"+a.Id).text())});
function addSkillArea(a,c){for(var d=$("<span>").addClass("skill").attr("data-id",a.Id).html(a.Name),b=[],e=1;e<=a.Kakusei;e++){var f=$("<button>").addClass("kakuseiCheck").addClass("floatLeft").addClass("kakusei"+a.Id).attr("data-id",a.Id).attr("data-kakusei",e);$(f).html("\u25c7");b.push(f)}e=$("<span>").addClass("icon_xs").text("\u3000").attr("style",getImgUrl("icon/"+ICON_LIST[a.BattleType]+".png"));var k=$("<td>").append(e);a.AttackAttributes.split(",").forEach(function(a){a=$("<span>").addClass("icon_xs").text("\u3000").attr("style",
getImgUrl("icon/"+ICON_LIST[a]+".png"));k.append(a)});d=$("<td>").append(d);e=$("<td>");b=$jscomp.makeIterator(b);for(f=b.next();!f.done;f=b.next())e.append(f.value);b='<span class="nowBP'+a.Id+'" data-id="'+a.Id+'" data-bp="'+a.ConsumeBp+'" >'+a.ConsumeBp+"</span>";b+="<br>";b=$("<td>").append(b);f=$("<td>").append(a.PowerGrade+"("+a.SkillIryoku+")");d=$("<tr>").append(k).append(d).append(e).append(b).append(f);$(c).append(d)}
function displayResult(){var a=USE_SKILL_LIST.slice();a.unshift(Object.assign({},NORMAL_ATTACK));rewriteBP(a);setSkillDamage(a);culcAutoMode(a);return a}var dummy={Id:0,AttackArea:"\u81ea\u8eab",UseBp:99,AutoUseBp:99};
function rewriteBP(a){""===$("table#skillArea > tfoot").html()&&a.push(Object.assign({},dummy));var c=a[1],d=a[2],b=a[3],e=a[4];c.isNotUseAuto=isNotUseAuto(c);d.isNotUseAuto=isNotUseAuto(d);b.isNotUseAuto=isNotUseAuto(b);e.isNotUseAuto=isNotUseAuto(e);c.AutoUseBp=c.isNotUseAuto?99:c.UseBp;d.AutoUseBp=d.isNotUseAuto?99:d.UseBp;b.AutoUseBp=b.isNotUseAuto?99:b.UseBp;e.AutoUseBp=e.isNotUseAuto?99:e.UseBp;e.AutoUseBp===b.AutoUseBp&&(b.AutoUseBp=99);e.AutoUseBp===d.AutoUseBp&&(d.AutoUseBp=99);e.AutoUseBp===
c.AutoUseBp&&(c.AutoUseBp=99);c.AutoUseBp===d.AutoUseBp?d.AutoUseBp=99:d.AutoUseBp===b.AutoUseBp&&(b.AutoUseBp=99);c.UseCount=0;d.UseCount=0;b.UseCount=0;e.UseCount=0;a.sort(function(a,b){return a.UseBp>b.UseBp||a.UseBp===b.UseBp&&a.isKeisho>b.isKeisho?-1:1})}function isNotUseAuto(a){return"\u5473\u65b9\u5358\u4f53"===a.AttackArea||"\u81ea\u8eab"===a.AttackArea||"ID77973c5"===a.Id||"ID777ed23"===a.Id?!0:!1}var CULC_DAMAGE_PARAM={};
function setSkillDamage(a){$("#JOKEN_LIST").html("");var c=0;for(e in NOW_STYLE.StyleAbilityIds){var d=NOW_STYLE.StyleAbilityIds[e];-1<["ID29d93221","ID29d9322e"].indexOf(d)?c+=15:-1<["ID29d93222","ID29d9322f"].indexOf(d)?c+=10:-1<["ID29d93223","ID29d93230"].indexOf(d)?c+=5:"ID29d93224"===d&&(c+=2)}var b=85;var e=99;var f=d=0,k={"\u65ac":"zan","\u6253":"da","\u7a81":"totsu","\u71b1":"netsu","\u51b7":"rei","\u96f7":"rai","\u9670":"in","\u967d":"you"},l=$("<li>").html("\u25bc\u5171\u901a\u6761\u4ef6\u25bc"),
g=$("<li>").html("\u6b66\u5668\u5a01\u529b/30 \u6280\u30e9\u30f3\u30af/"+e+" \u30de\u30b9\u30bf\u30fc\u30ec\u30d9\u30eb Lv27-Lv28/7% \u30a2\u30d3\u30ea\u30c6\u30a3\u88dc\u6b63/"+c+"%");f=$("<li>").html("\u25bc\u5404\u6280\u500b\u5225\u6761\u4ef6\u25bc");$("#JOKEN_LIST").append(l).append(g).append(f);l={};a=$jscomp.makeIterator(a);for(g=a.next();!g.done;l={$jscomp$loop$prop$row$19:l.$jscomp$loop$prop$row$19},g=a.next()){g=g.value;"\u901a\u5e38\u653b\u6483"===g.Name&&(g.BattleType=NOW_CHAR.WeaponType,
g.AttackAttributes=WEPON_ATTR[NOW_CHAR.WeaponType],e=1);f=g.BattleType;var m="",p="\u4f53\u529b";"\u4f53\u8853"===f?(type="tai",f=$("#charSTR").val(),d=$("#charAGI").val(),m="\u8155/"+f+", \u901f/"+d):"\u9283"===f?(type="ju",f=$("#charDEX").val(),m="\u5668/"+f):(type="other","\u8853"===g.SkillType?(f=$("#charINT").val(),m="\u77e5/"+f,p="\u7cbe\u795e"):-1<["\u5c0f\u5263","\u5f13"].indexOf(f)?(f=$("#charDEX").val(),m="\u5668/"+f):(f=$("#charSTR").val(),m="\u8155/"+f));var n=g.AttackAttributes,q=999;
b=$("#enemy_vit").val();var t=n;"x"!==b&&void 0!==n?(l.$jscomp$loop$prop$row$19=ENEMY_DATA[b],b="\u8853"===g.SkillType?l.$jscomp$loop$prop$row$19.mnd:l.$jscomp$loop$prop$row$19.vit,n.split(",").forEach(function(a){return function(b){q>a.$jscomp$loop$prop$row$19[k[b]]&&(q=a.$jscomp$loop$prop$row$19[k[b]],t=b)}}(l))):(b=85,q=0);p+="/"+b;g.culcDamage=0<g.SkillIryoku?damage(type,f,d,30,g.SkillIryoku,e,b,7,c,q,6):0;f=$("<li>").html("\n        ["+g.AttackAttributes+"]\n        "+g.Name+"\n        \u5a01\u529b("+
g.SkillIryoku+")\n        "+m+"\n        \u6575"+p+"\n        \u6575\u8010\u6027 "+t+"/"+q+"\n        ");void 0!==g.Name&&$("#JOKEN_LIST").append(f)}}
function culcAutoMode(a){var c=NOW_CHAR.WeaponType;$(".culcAfter").show();$("table#culcSummary tbody *").remove();$("#culcDetail").html("");var d=$("table#culcSummary tbody");0===a[0].Id&&(a=a.slice(1));var b=$("#culcDetail"),e="\u30b7\u30df\u30e5\u30ec\u30fc\u30b7\u30e7\u30f3\u7d50\u679c",f=0;NOW_STYLE.hasRenki&&(e+="<br>\u7df4\u6c17\u9ad8\u63da/\u547c\u5438(25%)\u767a\u52d5\u6642\u306fBP\u306b(+1)\u3068\u8868\u793a\u3055\u308c\u307e\u3059",f=1);b.append('<label class="badge badge-pill badge-light" style="width:90%">'+
e+"</label>");var k=7;e=$("#SET_TURN").val();var l=0;f=[0,0,0,f];for(var g={},m=1;m<=e;g={$jscomp$loop$prop$left$21:g.$jscomp$loop$prop$left$21},m++){var p=$("<div>").addClass("darkButton").addClass("keishoSkillArea");g.$jscomp$loop$prop$left$21=$("<p>").addClass("floatLeft");for(var n=$("<p>").addClass("floatRight"),q=Math.floor(Math.random()*f.length),t=k+=3,w="",u=99,v={},r=$jscomp.makeIterator(a),h=r.next();!h.done;h=r.next())h=h.value,-1<["ID77afa6a","ID7766685","ID7766685"].indexOf(h.Id)&&(u=
h.UseBp,v=h);r=!1;var x=$jscomp.makeIterator(a);for(h=x.next();!h.done;h=x.next())if(h=h.value,h!==v&&(k>=u&&!r?(w=" <small>("+v.Name+")</small>",v.UseCount++,r=!0):h.isNotUseAuto&&k>=h.UseBp&&(w=" <small>("+h.Name+")</small>",h.UseCount++),k>=h.AutoUseBp)){k-=h.AutoUseBp;g.$jscomp$loop$prop$left$21.append(m+'<span class="d-md-none">T</span><span class="d-none d-md-inline">Turn</span>');"sp"!==device&&(void 0===h.AttackAttributes&&(h.BattleType=c,h.AttackAttributes=WEPON_ATTR[c]),u=$("<span>").addClass("icon_xs").text("\u3000").attr("style",
getImgUrl("icon/"+ICON_LIST[h.BattleType]+".png")),g.$jscomp$loop$prop$left$21.append(u),h.AttackAttributes.split(",").forEach(function(a){return function(b){b=$("<span>").addClass("icon_xs").text("\u3000").attr("style",getImgUrl("icon/"+ICON_LIST[b]+".png"));a.$jscomp$loop$prop$left$21.append(b)}}(g)));g.$jscomp$loop$prop$left$21.append(" "+h.Name);"sp"!==device&&g.$jscomp$loop$prop$left$21.append(" <span class='d-none d-md-inline'>\u6d88\u8cbb</span>BP:"+h.AutoUseBp);g.$jscomp$loop$prop$left$21.append(w);
n.append("<small>\u30c0\u30e1\u30fc\u30b8:"+h.culcDamage.toLocaleString()+"</small>");n.append(" BP:"+t+" > ");h.UseCount++;break}0<f[q]?(l++,k++,n.append(k+"(+1)"),p.removeClass("darkButton").addClass("darkButtonShine")):n.append(k);p.append(g.$jscomp$loop$prop$left$21).append(n);b.append(p)}c=0;b={};a=$jscomp.makeIterator(a);for(h=a.next();!h.done;b={$jscomp$loop$prop$td$23:b.$jscomp$loop$prop$td$23},h=a.next())k=h.value,d.append("<tr>"),b.$jscomp$loop$prop$td$23=$("<td>").addClass("text-nowrap"),
"sp"!==device&&void 0!==k.AttackAttributes&&(f=$("<span>").addClass("icon_xs").text("\u3000").attr("style",getImgUrl("icon/"+ICON_LIST[k.BattleType]+".png")),b.$jscomp$loop$prop$td$23.append(f),k.AttackAttributes.split(",").forEach(function(a){return function(b){b=$("<span>").addClass("icon_xs").text("\u3000").attr("style",getImgUrl("icon/"+ICON_LIST[b]+".png"));a.$jscomp$loop$prop$td$23.append(b)}}(b))),b.$jscomp$loop$prop$td$23.append(k.Name),d.append(b.$jscomp$loop$prop$td$23),d.append("<td>"+
k.UseBp+"</td>"),d.append("<td>"+k.UseCount+"</td>"),d.append('<td class="d-none d-md-inline">'+k.SkillIryoku+"</td>"),d.append("<td>"+number_format(k.culcDamage,0)+"</td>"),99!==k.AutoUseBp&&(c+=k.culcDamage*Number(k.UseCount)),d.append("</tr>");d.append("<tr>");d.append("<td colspan=5 class='text-center' id='avgDamage' style='font-size:200%'>\u5e73\u5747\u30c0\u30e1\u30fc\u30b8 "+Math.round(c/e).toLocaleString()+"</td>");d.append("</tr>");NOW_STYLE.hasRenki&&(d.append("<tr>"),d.append("<td colspan=5 class='text-center'>\u7df4\u6c17\u9ad8\u63da/\u547c\u5438 \u767a\u52d5\u56de\u6570 = "+
l+"\u56de</td>"),d.append("</tr>"));d.append("<tr style='border-top: 1px solid'>");d.append("<td colspan=5 class='text-center'>\u5408\u8a08\u30c0\u30e1\u30fc\u30b8 = "+c+"</td>");d.append("</tr>")}function initialHide(){$(".culcAfter").hide();$("#keishoKaijo").hide();$("#skillAreaParent").hide();$("#culcStart").hide();$(".styleChoiceArea").hide();$(".skillChoiceArea").hide()};