var ENEMY_DATA = [{
    "quest": "スコアバトル道場",
    "name": "木人",
    "zan": -35,
    "da": -35,
    "totsu": -35,
    "netsu": -35,
    "rei": -35,
    "rai": -35,
    "you": -35,
    "in": -35,
    "vit": 10,
    "mnd": 10
},
    {
    "quest": "討伐",
    "name": "穢れし聖獣(Romancing)",
    "zan": 0,
    "da": 0,
    "totsu": 0,
    "netsu": 300,
    "rei": -35,
    "rai": -35,
    "you": 50,
    "in": 50,
    "vit": 231,
    "mnd": 234
}, {
    "quest": "討伐",
    "name": "穢れし聖獣(1)",
    "zan": 0,
    "da": 0,
    "totsu": 0,
    "netsu": 300,
    "rei": -35,
    "rai": -35,
    "you": 50,
    "in": 50,
    "vit": 60,
    "mnd": 72
}]