var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
$jscomp.polyfill=function(a,b,c,e){if(b){c=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var d=a[e];d in c||(c[d]={});c=c[d]}a=a[a.length-1];e=c[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(a){return a instanceof d?a:new d(function(b,g){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})}this.batch_.push(a)};var e=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){e(a,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];a[b]=null;try{c()}catch(k){this.asyncThrow_(k)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var d=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(n){b.reject(n)}};d.prototype.createResolveAndReject_=function(){function a(a){return function(g){c||(c=!0,a.call(b,g))}}var b=this,c=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};d.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof d)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};d.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(n){this.reject_(n);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};d.prototype.reject_=function(a){this.settle_(2,a)};d.prototype.fulfill_=function(a){this.settle_(1,a)};d.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};d.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)f.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var f=new b;d.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};d.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(k){c.reject(k)}};d.prototype.then=function(a,b){function c(a,b){return"function"==typeof a?function(b){try{g(a(b))}catch(r){h(r)}}:b}var g,h,f=new d(function(a,b){g=a;h=b});this.callWhenSettled_(c(a,g),c(b,h));return f};
d.prototype["catch"]=function(a){return this.then(void 0,a)};d.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?f.asyncExecute(c):this.onSettledCallbacks_.push(c)};d.resolve=c;d.reject=function(a){return new d(function(b,c){c(a)})};d.race=function(a){return new d(function(b,d){for(var g=$jscomp.makeIterator(a),h=g.next();!h.done;h=
g.next())c(h.value).callWhenSettled_(b,d)})};d.all=function(a){var b=$jscomp.makeIterator(a),g=b.next();return g.done?c([]):new d(function(a,d){function h(b){return function(c){f[b]=c;e--;0==e&&a(f)}}var f=[],e=0;do f.push(void 0),e++,c(g.value).callWhenSettled_(h(f.length-1),d),g=b.next();while(!g.done)})};return d},"es6","es3");
$jscomp.polyfill("Promise.prototype.finally",function(a){return a?a:function(a){return this.then(function(b){return Promise.resolve(a()).then(function(){return b})},function(b){return Promise.resolve(a()).then(function(){throw b;})})}},"es9","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(c||"")+"_"+b++,c)}var b=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype["return"]=function(a){this.abruptCompletion_={"return":a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){var c=$jscomp.makeIterator(a),e=c.next();$jscomp.generator.ensureIteratorResultIsObject_(e);if(e.done)this.yieldResult=e.value,this.nextAddress=b;else return this.yieldAllIterator_=c,this.yield(e.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){var c=this.finallyContexts_.splice(b||0)[0];if(c=this.abruptCompletion_=this.abruptCompletion_||c){if(c.isException)return this.jumpToErrorHandler_();void 0!=c.jumpTo&&this.finallyAddress_<c.jumpTo?(this.nextAddress=c.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(a){return{value:a,done:!0}},a,this.context_["return"]);this.context_["return"](a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var e=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(e);if(!e.done)return this.context_.stop_(),e;var d=e.value}catch(f){return this.context_.yieldAllIterator_=null,this.context_.throw_(f),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,d);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a["return"],done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this["throw"]=function(b){return a.throw_(b)};this["return"]=function(b){return a.return_(b)};$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){var c=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&$jscomp.setPrototypeOf(c,a.prototype);return c};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(b){return a.next(b)}function c(b){return a["throw"](b)}return new Promise(function(e,d){function f(a){a.done?e(a.value):Promise.resolve(a.value).then(b,c).then(f,d)}f(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
var charGraphm,styleGraphA,styleGraphS,styleGraphSS,styleGraphT,styleRankA,styleRankS,styleRankSS,styleRankT,ALLUSER,CHAR_USER,STYLECHECK_USER,CHAR_RANK,CHAR_HP_RANK,CHAR_ST_RANK,PLAYER_RANK;
firebase.auth(appUsers).onAuthStateChanged(function(a){a?(OFUSE_FLG&&$(".premium").removeClass("d-none"),USER=a,UID=a.uid):(a={signInSuccessUrl:"https://nao-romasaga.github.io/home.html",signInOptions:[firebase.auth.TwitterAuthProvider.PROVIDER_ID]},(new firebaseui.auth.AuthUI(firebase.auth(appUsers))).start("#firebaseui-auth-container",a))});
readAnalyzeFile("HOME_DATA",function(a){ALLUSER=a.ALLUSER;CHAR_USER=a.CHAR;CHAR_RANK=a.CHAR_RANK;CHAR_HP_RANK=a.CHAR_HP_RANK;CHAR_ST_RANK=a.CHAR_ST_RANK;PLAYER_RANK=a.PLAYER_RANK;STYLECHECK_USER=a.STYLECHECK;$("#ALLUSER").text(ALLUSER);$("#CHAR_USER").text(CHAR_USER);$("#STYLECHECK_USER").text(STYLECHECK_USER);charGraph=a.CHAR_SUM;styleGraphA=a.STYLECHECK_SUM.A;styleGraphS=a.STYLECHECK_SUM.S;styleGraphSS=a.STYLECHECK_SUM.SS;styleGraphT=a.STYLECHECK_SUM.TOTAL;styleRankA=a.STYLECHECK_RANK.A;styleRankS=
a.STYLECHECK_RANK.S;styleRankSS=a.STYLECHECK_RANK.SS;styleRankT=a.STYLECHECK_RANK.TOTAL;void 0!==UID&&void 0!==ALLUSER&&initial()});
function _initial(){$(".noLogin").hide();$(".isLogin").removeClass("d-none");$("#loginInfo").hide();var a=$("<img>").attr("src",USER.photoURL).attr("style","width:80px; heidht:80px; border: 5px ridge rgb(246,236,100); border-radius: 10px; margin:0px 5px;"),b=$("<img>").attr("src",USER.photoURL).attr("style","width:120px; heidht:120px; border: 5px ridge rgb(246,236,100); border-radius: 10px; margin:0px 5px;");$("#MYICON").append(a);$("#MYICON2").append(b);$("#NAME").html(USER.displayName+"<br>"+UID);
void 0!==ALLUSER&&initial()}
function initial(){var a,b,c,e;return $jscomp.asyncExecutePromiseGeneratorProgram(function(d){if(1==d.nextAddress)return a=readUserData("RANK",function(a){if(null!==a){var b=Object.keys(a),c=b[b.length-1];$("#rank").val(Number(a[c]));$(".now_rank").text(Number(a[c]));for(c=0;5>c++;){var d=b[b.length-c];if(void 0===d)break;var e=d.substr(5).replace("-","/");$("#rankHistory").append(e+': <span class="fuchidori">'+a[d].toLocaleString()+"</span><br>")}b=[];c=0;for(var f in a)c=f.substr(5).replace("-",
"/"),b[c]=a[f],c=a[f];$(".MY_PLAYER_RANK").text(calcMyRank(PLAYER_RANK,c));renderChart(PLAYER_RANK,Number(c),"rgba(246,236,100,1)","rankGraph");renderDailyChart(b,"rgba(206,206,206,1)","rankHistoryChart")}}),b=readUserData("JEWEL",function(a){if(null!==a){var b=Object.keys(a),c=b[b.length-1];$("#jewel").val(Number(a[c]));$(".now_jewel").text(Number(a[c]));for(c=0;5>c++;){var d=b[b.length-c];if(void 0===d)break;var e=d.substr(5).replace("-","/");$("#jewelD"+c+"d").text(e);$("#jewelD"+c+"v").text(a[d].toLocaleString());
$("#jewelHistory").append(e+(': <img src="./img/icon/icon_jewel.png" width="25" height="25"><span class="fuchidoriJewel">'+a[d].toLocaleString()+"</span><br>"))}b=[];for(var f in a)c=f.substr(5).replace("-","/"),b[c]=a[f];renderDailyChart(b,"rgba(160,160,255,1)","jewelHistoryChart")}}),c=readStyleCheckData(UID,function(a){MY_STYLE=a;a=void 0!==MY_STYLE.A?MY_STYLE.A:[];var b=void 0!==MY_STYLE.S?MY_STYLE.S:[],c=void 0!==MY_STYLE.SS?MY_STYLE.SS:[],d=a.length+b.length+c.length;$(".MY_ASTYLE_CNT").text(a.length);
$(".MY_SSTYLE_CNT").text(b.length);$(".MY_SSSTYLE_CNT").text(c.length);$(".MY_STYLE_CNT").text(d);var e=calcMyRank(styleRankA,a.length),f=calcMyRank(styleRankS,b.length),t=calcMyRank(styleRankSS,c.length),p=calcMyRank(styleRankT,d);$(".MY_ASTYLE_RANK").text(e);$(".MY_SSTYLE_RANK").text(f);$(".MY_SSSTYLE_RANK").text(t);$(".MY_STYLE_RANK").text(p);renderChart(styleRankSS,c.length,"rgba(246,236,100,1)","styleRankSS");renderChart(styleRankS,b.length,"rgb(200,224,234)","styleRankS");renderChart(styleRankA,
a.length,"rgb(247,170,150)","styleRankA");renderChart(styleRankT,d,"rgba(206,206,206,1)","styleRankT")}),e=readUserData("CHAR",function(a){var b,c,d,e,f,t,p,A,B,r,I,C,w,D,J,l,E,F,m,K,G,u,x,v,q,H,L,M,y,z;return $jscomp.asyncExecutePromiseGeneratorProgram(function(g){MY_CHAR=a;b=Object.keys(MY_CHAR).length;d=c=0;for(e in MY_CHAR){MY_CHAR[e].charId=e;f=0;t=$jscomp.makeIterator(PARAM_KEY);for(p=t.next();!p.done;p=t.next())A=p.value,B=void 0!==MY_CHAR[e][A]?Number(MY_CHAR[e][A]):0,f+=B,d+=B;MY_CHAR[e].SUM=
f;c+=void 0!==MY_CHAR[e].HP?Number(MY_CHAR[e].HP):0;r=CHAR_MASTER[e];I="\u6756"===r.WeaponType?"\u6756":WEPON_ATTR[r.WeaponType];C=$jscomp.makeIterator(["DotId","Name","Id"]);for(w=C.next();!w.done;w=C.next())D=w.value,MY_CHAR[e][D]=CHAR_MASTER[e][D];MY_CHAR_RANK[I].push(MY_CHAR[e])}J='<i class="fas fa-crown" style="color: rgba(246,236,100,1);"></i>{<i class="fas fa-crown" style="color: rgba(200,224,234,1);"></i>{<i class="fas fa-crown" style="color: rgba(247,170,150,1);"></i>{{{{{{{{{{{'.split("{");
for(l in MY_CHAR_RANK){MY_CHAR_RANK[l].sort(function(a,b){return a.SUM>b.SUM?-1:1});E=$("<div>").addClass("col-12 col-md-6");F=$("<div>").addClass("col-6 d-none d-md-inline");for(m in MY_CHAR_RANK[l]){K=MY_CHAR_RANK[l][m].charId;G=Number(MY_CHAR_RANK[l][m].SUM);result=RANK_DETAIL[K].RANK;u=1;if(null!==result&&void 0!==result){x=Object.keys(result);for(v=x.length-1;0<v;v--)if(G<Number(x[v]))u+=result[x[v]];else break;u+="\u4f4d"}else u="\u96c6\u8a08\u4e2d";q='<a href="ourchar.html?c='+MY_CHAR_RANK[l][m].Id+
'" target="_blank">';q+='<span class="char dot_mid dot char-winner" style="background: url(./img/dot/'+MY_CHAR_RANK[l][m].DotId+'.png) no-repeat; padding-top: 50px;">';q+='<div class="series-button" style="font-size:11px !important;"><p style="margin-bottom: -5px;">'+J[m]+" "+G+"</p>"+u.toLocaleString()+"</div></span>";q+="</a><br>";if(4>=m)E.append(q);else if(9>=m)F.append(q);else break}$("#DIV_RANK_"+l).append(E);$("#DIV_RANK_"+l).append(F)}H=calcMyRank(CHAR_HP_RANK,c);L=calcMyRank(CHAR_ST_RANK,
d);M=calcMyRank(CHAR_RANK,b);$(".MY_CHAR_RANK").text(M.toLocaleString());$(".MY_CHAR_CNT").text(b.toLocaleString());$("#MY_HP_RANK").text(H);$("#MY_HP_SUM").text(c.toLocaleString());$("#MY_ST_SUM").text(d.toLocaleString());$("#MY_HP_RANK").text(H);$("#MY_ST_RANK").text(L);y={};if(10<b)for(z in CHAR_RANK)10<z&&(y[z]=CHAR_RANK[z]);else y=CHAR_RANK;renderChart(y,b,"rgba(206,206,206,1)","myCharRank");g.jumpToEnd()})}),d.yield(Promise.all([a,b,c,e]),2);firebase.database().goOffline();firebase.database(appUsers).goOffline();
d.jumpToEnd()})}$("#SAVE_RANK").click(function(){var a=$("#rank").val();if(0<a){var b={};updateData("RANK",(b[getYMD(0)]=a,b),!0);a=getYMD(0).substr(5).replace("-","/")+(' : <span class="fuchidori">'+a.toLocaleString()+"</span><br>");$("#rankHistory").prepend(a)}});
$("#SAVE_JEWEL").click(function(){var a=$("#jewel").val();a=""===a?0:a;var b={};updateData("JEWEL",(b[getYMD(0)]=Number(a),b),!0);a=getYMD(0).substr(5).replace("-","/")+(' : <img src="./img/icon/icon_jewel.png" width="25" height="25"><span class="fuchidoriJewel">'+a.toLocaleString()+"</span><br>");$("#jewelHistory").prepend(a)});function getYMD(a){var b=new Date;b.setDate(b.getDate()-a);a=b.getFullYear();var c=("00"+(b.getMonth()+1)).slice(-2);b=("00"+b.getDate()).slice(-2);return a+"-"+c+"-"+b}
function renderChart(a,b,c,e){var d=[],f=[],g=[],h=[],n=!1,k;for(k in a)d.push(k),f.push(k),g.push(a[k]),k>=b&&!n?(n=!0,h.push(a[k])):h.push(0);a={labels:d,datasets:[{label:"\u3042\u306a\u305f",data:h,backgroundColor:"rgba(255,100,100)"},{label:"\u5168\u4f53",data:g,backgroundColor:c,type:"line"}]};e=document.getElementById(e).getContext("2d");window.myBar=new Chart(e,{type:"bar",data:a,options:{responsive:!0,legend:{position:"top"},title:{display:!1,text:"Chart.js Bar Chart"},scales:{yAxes:[{ticks:{beginAtZero:!0}}],
xAxes:[{gridLines:{offsetGridLines:!0}}]}}})}function renderDailyChart(a,b,c){var e=[],d=[],f;for(f in a)e.push(f),d.push(a[f]);a={labels:e,datasets:[{label:"\u63a8\u79fb",data:d,backgroundColor:b}]};c=document.getElementById(c).getContext("2d");window.myBar=new Chart(c,{type:"line",data:a,options:{responsive:!0,legend:{position:"top"},title:{display:!1,text:"Chart.js Bar Chart"},scales:{yAxes:[{ticks:{}}],xAxes:[{gridLines:{offsetGridLines:!0}}]}}})}
function calcMyRank(a,b){var c=0,e=0,d;for(d in a)e+=Number(a[d]),Number(d)<=b&&(c+=Number(a[d]));return e-c+1}var MY_CHAR_RANK={"\u65ac":[],"\u6253":[],"\u7a81":[],"\u6756":[]};