var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function c(a){return a instanceof e?a:new e(function(b,g){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})}this.batch_.push(a)};var d=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){d(a,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];a[b]=null;try{c()}catch(u){this.asyncThrow_(u)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var e=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(x){b.reject(x)}};e.prototype.createResolveAndReject_=function(){function a(a){return function(d){c||(c=!0,a.call(b,d))}}var b=this,c=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};e.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof e)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};e.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(x){this.reject_(x);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};e.prototype.reject_=function(a){this.settle_(2,a)};e.prototype.fulfill_=function(a){this.settle_(1,a)};e.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)f.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var f=new b;e.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};e.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(u){c.reject(u)}};e.prototype.then=function(a,b){function c(a,b){return"function"==typeof a?function(b){try{d(a(b))}catch(q){g(q)}}:b}var d,g,f=new e(function(a,b){d=a;g=b});this.callWhenSettled_(c(a,d),c(b,g));return f};
e.prototype["catch"]=function(a){return this.then(void 0,a)};e.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?f.asyncExecute(c):this.onSettledCallbacks_.push(c)};e.resolve=c;e.reject=function(a){return new e(function(b,c){c(a)})};e.race=function(a){return new e(function(b,d){for(var e=$jscomp.makeIterator(a),g=e.next();!g.done;g=
e.next())c(g.value).callWhenSettled_(b,d)})};e.all=function(a){var b=$jscomp.makeIterator(a),d=b.next();return d.done?c([]):new e(function(a,e){function g(b){return function(c){f[b]=c;n--;0==n&&a(f)}}var f=[],n=0;do f.push(void 0),n++,c(d.value).callWhenSettled_(g(f.length-1),e),d=b.next();while(!d.done)})};return e},"es6","es3");
$jscomp.polyfill("Promise.prototype.finally",function(a){return a?a:function(a){return this.then(function(b){return Promise.resolve(a()).then(function(){return b})},function(b){return Promise.resolve(a()).then(function(){throw b;})})}},"es9","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(c||"")+"_"+b++,c)}var b=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(c){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype["return"]=function(a){this.abruptCompletion_={"return":a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){var c=$jscomp.makeIterator(a),d=c.next();$jscomp.generator.ensureIteratorResultIsObject_(d);if(d.done)this.yieldResult=d.value,this.nextAddress=b;else return this.yieldAllIterator_=c,this.yield(d.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,c){c?this.finallyContexts_[c]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){var c=this.finallyContexts_.splice(b||0)[0];if(c=this.abruptCompletion_=this.abruptCompletion_||c){if(c.isException)return this.jumpToErrorHandler_();void 0!=c.jumpTo&&this.finallyAddress_<c.jumpTo?(this.nextAddress=c.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(a){return{value:a,done:!0}},a,this.context_["return"]);this.context_["return"](a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,c){try{var d=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(d);if(!d.done)return this.context_.stop_(),d;var e=d.value}catch(f){return this.context_.yieldAllIterator_=null,this.context_.throw_(f),this.nextStep_()}this.context_.yieldAllIterator_=null;c.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a["return"],done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this["throw"]=function(b){return a.throw_(b)};this["return"]=function(b){return a.return_(b)};$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){var c=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&$jscomp.setPrototypeOf(c,a.prototype);return c};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(b){return a.next(b)}function c(b){return a["throw"](b)}return new Promise(function(d,e){function f(a){a.done?d(a.value):Promise.resolve(a.value).then(b,c).then(f,e)}f(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
var tableLimit=15,MY_DATA_LIST=[],CHAR_RANK,table,totalThreathold=0,login=!1;function _noLoginInitial(){var a={signInSuccessUrl:"https://nao-romasaga.github.io/ourchar.html",signInOptions:[firebase.auth.TwitterAuthProvider.PROVIDER_ID]};(new firebaseui.auth.AuthUI(firebase.auth(appUsers))).start("#firebaseui-auth-container",a);initialLoad()}
function _initial(){login=!0;$(".noLogin").hide();$(".isLogin").removeClass("d-none");$("#loginInfo").hide();var a=$("<img>").attr("src",USER.photoURL).attr("style","width:40px; heidht:40px;    border-radius: 50%;"),b=USER.displayName+" \u3055\u3093:\u30ed\u30b0\u30a4\u30f3\u4e2d";$("#firebaseui-auth-container").addClass("bg-white kadomaru").append(a).append(b);initialLoad()}
function initialLoad(){var a,b,c,d,e,f;return $jscomp.asyncExecutePromiseGeneratorProgram(function(g){CHAR_RANK=RANK_LIST.LIST;$("#UPDATE").text(RANK_LIST.UPDATE);$("#CHAR_COUNT").text(CHAR_RANK.length);a=99999;b=1;for(c in CHAR_RANK)d=CHAR_RANK[c].Id,void 0!==CHAR_MASTER[d]&&(CHAR_RANK[c].DotId="Dot"+CHAR_MASTER[d].DotId,CHAR_RANK[c].Name=CHAR_MASTER[d].Name,CHAR_RANK[c].Series=CHAR_MASTER[d].Series,CHAR_RANK[c].WeaponType=ICON_LIST[CHAR_MASTER[d].WeaponType],CHAR_RANK[c].SeriesFilter=CHAR_MASTER[d].Series,
CHAR_RANK[c].WeaponTypeFilter=ICON_LIST[CHAR_MASTER[d].WeaponType],a>Number(CHAR_RANK[c].size)&&(a=Number(CHAR_RANK[c].size),b=Number(c)+1),CHAR_RANK[c].rank=b);drawTable(CHAR_RANK);$(".initialHide").removeClass("d-none");$(".initialShow").slideUp();""!==location.search&&(e=location.search.substr(3),f=e.split("&"),void 0!==CHAR_MASTER[f[0]]&&(dispRanking(f[0]),$("html,body").animate({scrollTop:$("#RANKKING_TABLE").offset().top},500,"swing")));g.jumpToEnd()})}
$(".filterList").click(function(){$(this).parent().toggleClass("filterActive");void 0!==table&&(filter(),gtag("event","clickFilter",{event_category:"ourchar",event_label:$(this).attr("href").substr(1),value:1}))});var rand=Math.floor(5*Math.random());$(".dotBackground").addClass("bg"+(rand+1));
function filter(){var a=[],b=[],c=[],d=[];$(".filterList").each(function(){var e=$(this).attr("data-type"),f=$(this).attr("href").substr(1);$(this).parent().hasClass("filterActive")&&("WeaponTypeFilter"===e?(a.push({field:e,type:"=",value:f}),c.push($(this).attr("data-label"))):(b.push({field:e,type:"=",value:f}),d.push(f)))});var e="";table.clearFilter();var f=[{field:"MAXSUM",type:">",value:0}];0<a.length&&(f.push(a),e+="\u6b66\u5668\u7a2e:"+c.join(","));0<b.length&&(f.push(b),""!==e&&(e+=" & "),
e+=d.join(","));""!==e&&(e+="<br>");$("#label1").html(e);table.setFilter(f);changeId2Dot()}$(document).on("click",".tabulator-header, .tabulator-footer, .tabulator-page",function(){changeId2Dot()});
$(document).on("click",".tabulator-cell",function(){$(this).parent().find(".tabulator-cell").each(function(){var a=this,b,c;return $jscomp.asyncExecutePromiseGeneratorProgram(function(d){b=$(a).text();c=$(a).attr("tabulator-field");-1<b.indexOf("ID")?dispRanking(b):"Name"===c&&gtag("event","clickChar",{event_category:"ourchar",event_label:b,value:1});d.jumpToEnd()})});$("html,body").animate({scrollTop:$("#badge").offset().top},500,"swing")});
function dispRanking(a){var b,c,d,e,f,g,n,x,u,J,z,T,K,U,q,r,V,W,A,L,ea,fa,y,F,X,G,h,B,C,Y,v,ha,p,m,H,k,M,t,I,N,D,w,ia,O,Z,P,aa,ba,Q,ca,E,R,da,ja,l,ka,la,ma,na;return $jscomp.asyncExecutePromiseGeneratorProgram(function(S){if(1==S.nextAddress){$("#STYLE_LINK").attr("href","./style.html?s="+CHAR_MASTER[a].Holders[0]);$("#initialHide").removeClass("d-none");b={STR:0,VIT:0,DEX:0,AGI:0,INT:0,MND:0,AI:0,MI:0,SUM:0};c=$jscomp.makeIterator(PARAM_KEY);for(d=c.next();!d.done;d=c.next())e=d.value,b[e]=-99===
CHAR_MASTER[a]["MAX"+e]?"?":LIMIT_BASE+Number(CHAR_MASTER[a]["MAX"+e]);f=0;for(g in CHAR_RANK)if(CHAR_RANK[g].Id===a){n=$jscomp.makeIterator(PARAM_KEY);for(d=n.next();!d.done;d=n.next())x=d.value,$(".MAX"+x).text(CHAR_RANK[g]["MAX"+x]);f=CHAR_RANK[g].MAXHP;$(".MAXSUM").text(CHAR_RANK[g].MAXSUM);$("#RANK_COUNT").text(CHAR_RANK[g].rank);$("#INPUT_COUNT").text(CHAR_RANK[g].size);break}J=u="";z="%0D%0A";$(".STYLE_ROW").remove();u=CHAR_MASTER[a].Name;$(".charName").text(u);T=$jscomp.makeIterator(CHAR_MASTER[a].Holders);
for(K=T.next();!K.done;K=T.next()){U=K.value;q=STYLE_MASTER[U];r=$("#STYLE_TEMPLATE").clone();r.removeAttr("id");r.addClass("STYLE_ROW");r.removeClass("d-none");r.find(".rare").attr("src","./img/icon/icon_"+q.Rarity+".png");r.find(".icn").attr("src","./img/style_icon/"+U+".png");V=0;console.log(q);W=$jscomp.makeIterator(PARAM_KEY);for(d=W.next();!d.done;d=W.next())A=d.value,L=LIMIT_BASE+Number(q["Limit"+A]),ea=void 0!==q["Ind"+A]?q["Ind"+A]:1,fa='<img class="d-none d-md-inline" src="./img/icon/icon_ind_'+
ea+'.png" width=15>',99>q["Limit"+A]?V+=L:L="?",r.find("."+A).html(L+" "+fa);r.find(".SUM").text(V);$("#styleLabelRow").after(r)}$(".STYLE_ROW").each(function(){for(var a=$jscomp.makeIterator(PARAM_KEY),c=a.next();!c.done;c=a.next()){c=c.value;var d=$(this).find("."+c);d.text()==b[c]&&d.css("background-color","lightgreen")}});y=$("#STYLE_TEMPLATE").clone();y.removeAttr("id").addClass("STYLE_ROW").removeClass("d-none").css("background-color","rgba(0,0,0, 0.2)");y.find(".IMG").html("\u6700\u5927\u5024");
F=0;X=$jscomp.makeIterator(PARAM_KEY);for(d=X.next();!d.done;d=X.next())G=d.value,F+="?"!==b[G]?b[G]:0,y.find("."+G).text(b[G]);y.find(".SUM").text(F);y.find(".SUM").addClass("STYLE_MAX");$("#styleLabelRow").after(y);h=null;return login?S.yield(readUserDataWithId("CHAR",a,function(a){h=a}),2):S.jumpTo(2)}B="MATCH";null===h&&(B="NONE",h={STR:0,VIT:0,DEX:0,AGI:0,INT:0,MND:0,AI:0,MI:0});C=0;Y=$jscomp.makeIterator(PARAM_KEY);for(d=Y.next();!d.done;d=Y.next())v=d.value,C+=Number(h[v]),$(".YOUR"+v).text(h[v]),
ha="?"===b[v]?"?":b[v]-h[v],$(".LIMIT"+v).text(ha);$(".YOURSUM").text(C);$(".LIMITSUM").text(0===F?"?":F-C);p=C;m=RANK_DETAIL[a];H="";k=1;M=999;t=0;$(".USER_RANK_DISP").remove();I=!1;N=0;for(D in m.list){w=0;for(ia in PARAM_KEY)w+=Number(m.list[D][ia]);N<w&&(N=w);M>w&&(M=w,t=Number(D)+1);M>p&&(k=t+1);!I&&p>=w&&0<p&&(I=!0,k=t,addRankRow(t,h,f,b,p,!0));D<OURSTYLE_LIMIT&&(void 0===UID||UID.substr(0,4)!==m.list[D].UID||!I)&&addRankRow(t,m.list[D],f,b,w,!1)}if(!I&&"NONE"!==B&&0<p){O=[];for(Z in m.RANK)O.push({p:Z,
s:m.RANK[Z]});O.sort(function(a,b){return-1});P=1;aa=!1;ba=$jscomp.makeIterator(O);for(Q=ba.next();!Q.done;Q=ba.next())if(ca=Q.value,p>=ca.p){k=P;aa=!0;break}else P+=Number(ca.s);aa||(k=P);addRankRow(k,h,f,b,p,!0)}void 0!==m.kyogiList&&$("#USER_RANK").before("<tr class='USER_RANK_DISP' style='background-color:red; color:white;'><td colspan=11>\u5354\u8b70\u4e2d</td></tr>");t="\u5354\u8b70\u4e2d";for(E in m.kyogiList){R=0;da=!1;for(ja in PARAM_KEY)R+=Number(m.kyogiList[E][ja]);void 0!==UID&&UID.substr(0,
4)===m.kyogiList[E].UID&&(B="KYOGI",da=!0);10>E&&(da?addRankRow(t,m.kyogiList[E],f,b,R,!0):addRankRow(t,m.kyogiList[E],f,b,R,!1))}k=1==k&&N>p?"\u8a08\u7b97\u4e2d":k+"\u4f4d";$(".rankingTweet").parent().removeClass("d-none");"KYOGI"===B?(J="\u66ab\u5b9a"+k+"\u4f4d",H=k+"("+p+"pt)<br>\u5165\u529b\u5185\u5bb9\u3092\u518d\u78ba\u8a8d\u3059\u308b\u304b\u753b\u50cf\u4ed8\u304d\u3067\u5831\u544a\u304a\u9858\u3044\u81f4\u3057\u307e\u3059"):"MATCH"===B?(J=k,H=k+"("+p+"pt)"):($(".rankingTweet").parent().addClass("d-none"),
H="\u767b\u9332\u304c\u3042\u308a\u307e\u305b\u3093");$("#MY_RANK").html(H);$("#charDotAruku").removeClass("char-utau").removeClass("char-aruku").removeClass("char-hashiri");1===Number(k)?$("#charDotAruku").addClass("char-utau"):10>=Number(k)?$("#charDotAruku").addClass("char-hashiri"):$("#charDotAruku").addClass("char-aruku");$("#charDot").html('<span class="char dot_mid dot char-winner" style="background: url(./img/dot/'+CHAR_MASTER[a].DotId+'.png) no-repeat; margin: 0 10px;"></span>');$("#charDotAruku").attr("style",
"background: url(./img/dot/"+CHAR_MASTER[a].DotId+".png) no-repeat; margin: 0 10px;");l=u+"\u3067\u30e9\u30f3\u30ad\u30f3\u30b0"+J+"!!"+z;l+="HP/\u8155/\u4f53/\u5668/\u901f/\u77e5/\u7cbe/\u611b/\u9b45/\u5408\u8a08"+z;l+=("0"+h.HP).slice(-3)+"/";l+=("0"+h.STR).slice(-2)+"/";l+=("0"+h.VIT).slice(-2)+"/";l+=("0"+h.DEX).slice(-2)+"/";l+=("0"+h.AGI).slice(-2)+"/";l+=("0"+h.INT).slice(-2)+"/";l+=("0"+h.MND).slice(-2)+"/";l+=("0"+h.AI).slice(-2)+"/";l+=("0"+h.MI).slice(-2)+"/";l+=("0"+C).slice(-3)+z;ka=
"\u80b2\u6210\u30e9\u30f3\u30ad\u30f3\u30b0 [\u30ed\u30de\u30b5\u30acRS\u4fbf\u5229\u30c4\u30fc\u30eb] "+z+l;la="https://twitter.com/intent/tweet?text="+ka+"&url=https://nao-romasaga.github.io/ourchar.html?c="+a+"&hashtags=\u30ed\u30de\u30b5\u30acRS\u4fbf\u5229\u30c4\u30fc\u30eb,\u30ed\u30de\u30b5\u30acRS\u80b2\u6210\u30e9\u30f3\u30ad\u30f3\u30b0";$(".rankingTweet").attr("href",la);ma="@nao_romasaga_rs \u80b2\u6210\u30e9\u30f3\u30ad\u30f3\u30b0 \u5354\u8b70\u89e3\u9664\u7533\u8acb "+z+l;na="https://twitter.com/intent/tweet?text="+
ma+"&url=https://nao-romasaga.github.io/ourchar.html?c="+a+"&hashtags=\u30ed\u30de\u30b5\u30acRS\u4fbf\u5229\u30c4\u30fc\u30eb,\u30ed\u30de\u30b5\u30acRS\u80b2\u6210\u30e9\u30f3\u30ad\u30f3\u30b0";$(".kaijoTweet").attr("href",na);S.jumpToEnd()})}
function addRankRow(a,b,c,d,e,f){var g="\u5354\u8b70\u4e2d"===a?"small":"";g=$("<tr>").addClass("text-center USER_RANK_DISP "+g);f&&g.addClass("bg-white");g.append("<td class='paramCell2'>"+a+" </td>");a=void 0===b.HP?"-":b.HP;c===a&&(a='<i class="fas fa-crown small">'+a+"</i>");g.append("<td class='paramCell2 small'>"+a+"</td>");for(var n in PARAM_KEY)c=PARAM_KEY[n],a=void 0===b[n]?b[c]:b[n],f="",0<d[c]&&a===d[c]&&(f=" background-color:lightgreen;"),0<d[c]&&a===d[c]+1?f=" background-color:yellow;":
0<d[c]&&a>d[c]&&(f=" background-color:red; color:white;"),g.append("<td class='paramCell2' style='"+f+"'>"+a+"</td>");Number($(".STYLE_MAX").text())-totalThreathold>e?g.append("<td class='paramCell2 small'>"+e+"</td>"):g.append("<td class='paramCell2' style='background-color:red; color:white;'>"+e+"</td>");$("#USER_RANK").before(g)}
function changeId2Dot(){$("#example-table").find(".tabulator-cell").each(function(){var a=$(this).text();-1<a.indexOf("Dot")?(a='<img src="./img/dot/'+a.substr(3)+'.png" style="object-position: -10px -10px">',$(this).html(a)):-1<a.indexOf("icon")&&(a='<span class="icon_mini_zokusei '+a+'"></span>',$(this).html(a))})}
function drawTable(a,b){var c=void 0===b?"desc":b;$("#example-table").remove();$("#example-table-display").append('<div id="example-table" style="width:100%"></div>');var d={align:"right",sortable:!0,sorter:"number",minWidth:30,width:30};table=new Tabulator("#example-table",{layout:"fitColumns",data:a,tooltips:!1,history:!0,pagination:"local",paginationSize:tableLimit,initialSort:[{column:"size",dir:c}],autoResize:!1,resizableRows:!1,resizableColumns:!1,responsiveLayout:!0,columns:[{title:"",field:"DotId",
width:30,frozen:!0},{title:"",field:"Id",visible:!1},{title:"",field:"UserId",visible:!1},{title:"",field:"SeriesFilter",visible:!1},{title:"",field:"WeaponTypeFilter",visible:!1},{title:"rank",field:"rank",visible:!1},{title:"\u540d\u524d",field:"Name",responsive:8},{title:"\u4f5c\u54c1",field:"Series",width:30,responsive:10},{title:"\u6b66\u5668",field:"WeaponType",width:30,responsive:9},{title:"HP",field:"MAXHP",align:"right",sortable:!0,sorter:"number",minWidth:30,width:40,responsive:7},Object.assign({title:"\u8155",
field:"MAXSTR"},d),Object.assign({title:"\u4f53",field:"MAXVIT"},d),Object.assign({title:"\u5668",field:"MAXDEX"},d),Object.assign({title:"\u901f",field:"MAXAGI"},d),Object.assign({title:"\u77e5",field:"MAXINT"},d),Object.assign({title:"\u7cbe",field:"MAXMND"},d),Object.assign({title:"\u611b",field:"MAXAI"},d),Object.assign({title:"\u9b45",field:"MAXMI"},d),{title:'<span class="hidden pcBlock">\u5408</span>\u8a08',field:"MAXSUM",sortable:!0,sorter:"number"},{title:"\u5e73\u5747",field:"AVG",sortable:!0,
sorter:"number",responsive:11},{title:"\u767b\u9332\u6570",field:"size",responsive:11}]});table.setFilter("MAXSUM",">",0);changeId2Dot()};