var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return c?c.call(a):$jscomp.arrayIterator(a)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,d){a!=Array.prototype&&a!=Object.prototype&&(a[c]=d.value)};
$jscomp.polyfill=function(a,c,d,b){if(c){d=$jscomp.global;a=a.split(".");for(b=0;b<a.length-1;b++){var e=a[b];e in d||(d[e]={});d=d[e]}a=a[a.length-1];b=d[a];c=c(b);c!=b&&null!=c&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:c})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function c(){this.batch_=null}function d(a){return a instanceof e?a:new e(function(b,c){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;c.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})}this.batch_.push(a)};var b=$jscomp.global.setTimeout;c.prototype.asyncExecuteFunction=function(a){b(a,0)};c.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var c=a[b];a[b]=null;try{c()}catch(l){this.asyncThrow_(l)}}}this.batch_=null};c.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var e=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(g){b.reject(g)}};e.prototype.createResolveAndReject_=function(){function a(a){return function(d){c||(c=!0,a.call(b,d))}}var b=this,c=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};e.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof e)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};e.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(g){this.reject_(g);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};e.prototype.reject_=function(a){this.settle_(2,a)};e.prototype.fulfill_=function(a){this.settle_(1,a)};e.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};e.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)f.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var f=new c;e.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};e.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(l){c.reject(l)}};e.prototype.then=function(a,b){function c(a,b){return"function"==typeof a?function(b){try{d(a(b))}catch(n){f(n)}}:b}var d,f,h=new e(function(a,b){d=a;f=b});this.callWhenSettled_(c(a,d),c(b,f));return h};
e.prototype["catch"]=function(a){return this.then(void 0,a)};e.prototype.callWhenSettled_=function(a,b){function c(){switch(d.state_){case 1:a(d.result_);break;case 2:b(d.result_);break;default:throw Error("Unexpected state: "+d.state_);}}var d=this;null==this.onSettledCallbacks_?f.asyncExecute(c):this.onSettledCallbacks_.push(c)};e.resolve=d;e.reject=function(a){return new e(function(b,c){c(a)})};e.race=function(a){return new e(function(b,c){for(var e=$jscomp.makeIterator(a),f=e.next();!f.done;f=
e.next())d(f.value).callWhenSettled_(b,c)})};e.all=function(a){var b=$jscomp.makeIterator(a),c=b.next();return c.done?d([]):new e(function(a,e){function f(b){return function(c){h[b]=c;g--;0==g&&a(h)}}var h=[],g=0;do h.push(void 0),g++,d(c.value).callWhenSettled_(f(h.length-1),e),c=b.next();while(!c.done)})};return e},"es6","es3");
$jscomp.polyfill("Promise.prototype.finally",function(a){return a?a:function(a){return this.then(function(c){return Promise.resolve(a()).then(function(){return c})},function(c){return Promise.resolve(a()).then(function(){throw c;})})}},"es9","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,c){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:c})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(d){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(d||"")+"_"+c++,d)}var c=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},c={};try{return c.__proto__=a,c.a}catch(d){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,c){a.__proto__=c;if(a.__proto__!==c)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype["return"]=function(a){this.abruptCompletion_={"return":a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,c){this.nextAddress=c;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,c){var d=$jscomp.makeIterator(a),b=d.next();$jscomp.generator.ensureIteratorResultIsObject_(b);if(b.done)this.yieldResult=b.value,this.nextAddress=c;else return this.yieldAllIterator_=d,this.yield(b.value,c)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,c){this.catchAddress_=a;void 0!=c&&(this.finallyAddress_=c)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,c){this.nextAddress=a;this.catchAddress_=c||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,c,d){d?this.finallyContexts_[d]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=c||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,c){var d=this.finallyContexts_.splice(c||0)[0];if(d=this.abruptCompletion_=this.abruptCompletion_||d){if(d.isException)return this.jumpToErrorHandler_();void 0!=d.jumpTo&&this.finallyAddress_<d.jumpTo?(this.nextAddress=d.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var c in a)this.properties_.push(c);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var c=this.context_.yieldAllIterator_;if(c)return this.yieldAllStep_("return"in c?c["return"]:function(a){return{value:a,done:!0}},a,this.context_["return"]);this.context_["return"](a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,c,d){try{var b=a.call(this.context_.yieldAllIterator_,c);$jscomp.generator.ensureIteratorResultIsObject_(b);if(!b.done)return this.context_.stop_(),b;var e=b.value}catch(f){return this.context_.yieldAllIterator_=null,this.context_.throw_(f),this.nextStep_()}this.context_.yieldAllIterator_=null;d.call(this.context_,e);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(c){this.context_.yieldResult=void 0,this.context_.throw_(c)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a["return"],done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(c){return a.next_(c)};this["throw"]=function(c){return a.throw_(c)};this["return"]=function(c){return a.return_(c)};$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,c){var d=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(c));$jscomp.setPrototypeOf&&$jscomp.setPrototypeOf(d,a.prototype);return d};
$jscomp.asyncExecutePromiseGenerator=function(a){function c(b){return a.next(b)}function d(b){return a["throw"](b)}return new Promise(function(b,e){function f(a){a.done?b(a.value):Promise.resolve(a.value).then(c,d).then(f,e)}f(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
var PARTY_DATA={quest_lv:"",quest:"",party:[],jinkei:"FreeFight"},USER_PARTY_LIST=[],SEARCH_DATA={quest_lv:"",quest:"",jinkei:"",mode:"",my:0},UID,dotStyle=" margin-left:0px; position: relative; bottom: -20px;",QUEST_NAME={G2:"\u5916\u4f1d2",G1:"\u5916\u4f1d1",VH12:"VH12",VH11:"VH11",VH10:"VH10",VH9:"VH9",VH8:"VH8",VH7:"VH7",CHALLANGE1:"\u6df1\u5965\u306e\u5bc6\u6797\u8abf\u67fb",CHALLANGE2:"\u87ba\u65cb\u56de\u5eca",CHALLANGE3:"\u30c4\u30f4\u30a1\u30a4\u30af\u30d0\u30c8\u30eb\u30d5\u30a7\u30b9",
DAILY1:"\u30b6\u30af\u30b6\u30af\u8ca1\u5b9d\u53ce\u96c6",DAILY2:"\u907a\u8de1-\u4e09\u5149\u77f3-",DAILY3:"\u907a\u8de1-\u65ac\u5149\u77f3-",DAILY4:"\u907a\u8de1-\u6253\u5149\u77f3-",DAILY5:"\u907a\u8de1-\u7a81\u5149\u77f3-",DAILY6:"\u907a\u8de1-\u6756\u5149\u77f3-",DAILY7:"\u907a\u8de1-\u93a7\u5149\u77f3-",DAILY8:"\u907a\u8de1-\u7532\u5149\u77f3-",EV2:"\u7384\u7adc\u3068\u306e\u6226\u3044",EV1:"\u30da\u30c3\u30c8\u6355\u7372\u5927\u4f5c\u6226"},QUEST={DAILY1:"10.\u5c64 9.\u5c64 8.\u5c64 7.\u5c64 6.\u5c64 5.\u5c64 4.\u5c64 3.\u5c64 2.\u5c64 1.\u5c64".split(" "),
DAILY2:"10.\u5c64 9.\u5c64 8.\u5c64 7.\u5c64 6.\u5c64 5.\u5c64 4.\u5c64 3.\u5c64 2.\u5c64 1.\u5c64".split(" "),DAILY3:"10.\u5c64 9.\u5c64 8.\u5c64 7.\u5c64 6.\u5c64 5.\u5c64 4.\u5c64 3.\u5c64 2.\u5c64 1.\u5c64".split(" "),DAILY4:"10.\u5c64 9.\u5c64 8.\u5c64 7.\u5c64 6.\u5c64 5.\u5c64 4.\u5c64 3.\u5c64 2.\u5c64 1.\u5c64".split(" "),DAILY5:"10.\u5c64 9.\u5c64 8.\u5c64 7.\u5c64 6.\u5c64 5.\u5c64 4.\u5c64 3.\u5c64 2.\u5c64 1.\u5c64".split(" "),DAILY6:"10.\u5c64 9.\u5c64 8.\u5c64 7.\u5c64 6.\u5c64 5.\u5c64 4.\u5c64 3.\u5c64 2.\u5c64 1.\u5c64".split(" "),
DAILY7:"10.\u5c64 9.\u5c64 8.\u5c64 7.\u5c64 6.\u5c64 5.\u5c64 4.\u5c64 3.\u5c64 2.\u5c64 1.\u5c64".split(" "),DAILY8:"10.\u5c64 9.\u5c64 8.\u5c64 7.\u5c64 6.\u5c64 5.\u5c64 4.\u5c64 3.\u5c64 2.\u5c64 1.\u5c64".split(" "),CHALLANGE1:"10.\u5c64 9.\u5c64 8.\u5c64 7.\u5c64 6.\u5c64 5.\u5c64 4.\u5c64 3.\u5c64 2.\u5c64 1.\u5c64".split(" "),CHALLANGE2:"40.\u968e 39.\u968e 38.\u968e 37.\u968e 36.\u968e 35.\u5c64 34.\u968e 33.\u968e 32.\u968e 31.\u968e".split(" "),CHALLANGE3:["8.\u56de\u6226","7.\u56de\u6226",
"6.\u56de\u6226","5.\u56de\u6226"],EV2:"10.\u56de\u6226 9.\u56de\u6226 8.\u56de\u6226 7.\u56de\u6226 6.\u56de\u6226 5.\u56de\u6226".split(" "),EV1:"20. \u30da\u30c3\u30c8\u6355\u7372\u5927\u4f5c\u6226;19. \u30da\u30c3\u30c8\u6355\u7372\u5927\u4f5c\u6226;18. \u30da\u30c3\u30c8\u6355\u7372\u5927\u4f5c\u6226;17. \u30da\u30c3\u30c8\u6355\u7372\u5927\u4f5c\u6226;16. \u30da\u30c3\u30c8\u6355\u7372\u5927\u4f5c\u6226;15. \u30da\u30c3\u30c8\u6355\u7372\u5927\u4f5c\u6226;14. \u30da\u30c3\u30c8\u6355\u7372\u5927\u4f5c\u6226;13. \u30da\u30c3\u30c8\u6355\u7372\u5927\u4f5c\u6226;12. \u30da\u30c3\u30c8\u6355\u7372\u5927\u4f5c\u6226;11. \u30da\u30c3\u30c8\u6355\u7372\u5927\u4f5c\u6226;10. \u30da\u30c3\u30c8\u6355\u7372\u5927\u4f5c\u6226;9. \u30da\u30c3\u30c8\u6355\u7372\u5927\u4f5c\u6226;8. \u30da\u30c3\u30c8\u6355\u7372\u5927\u4f5c\u6226;7. \u30da\u30c3\u30c8\u6355\u7372\u5927\u4f5c\u6226;6. \u30da\u30c3\u30c8\u6355\u7372\u5927\u4f5c\u6226;5. \u30da\u30c3\u30c8\u6355\u7372\u5927\u4f5c\u6226;4. \u30da\u30c3\u30c8\u6355\u7372\u5927\u4f5c\u6226;3. \u30da\u30c3\u30c8\u6355\u7372\u5927\u4f5c\u6226;2. \u30da\u30c3\u30c8\u6355\u7372\u5927\u4f5c\u6226;1. \u30da\u30c3\u30c8\u6355\u7372\u5927\u4f5c\u6226".split(";"),
VH7:"VH7-1-1. \u7826\u30fb\u5165\u308a\u53e3;VH7-1-2. \u7826\u30fb\u796d\u58c7\u306e\u9593;VH7-1-3. \u7826\u30fb\u5927\u5e83\u9593;VH7-1-4. \u7826\u30fb\u58c1\u753b\u306e\u9593;VH7-1-5. \u708e\u71b1\u5730\u7344;VH7-2-1. \u9003\u8d70;VH7-2-2. \u7826\u30fb\u96a0\u3057\u901a\u8def;VH7-2-3. \u5854\u30fb\u4e2d\u5c64;VH7-2-4. \u5854\u30fb\u4e0a\u5c64;VH7-2-5. \u51a5\u5e9c\u3088\u308a\u51fa\u3065".split(";"),VH8:"VH8-1-1. \u96ea\u4e0a\u3092\u99c6\u3051\u629c\u3051\u308b;VH8-1-2. \u30ab\u30e9\u30df\u30e4\u306e\u6d1e\u7a9f\u30fb\u5916;VH8-1-3. \u30ab\u30e9\u30df\u30e4\u306e\u6d1e\u7a9f\u30fb\u5165\u308a\u53e3;VH8-1-4. \u30ab\u30e9\u30df\u30e4\u306e\u6d1e\u7a9f\u30fb\u4e09\u53c9\u8def;VH8-1-5. \u30f4\u30a1\u30eb\u30c9\u30fc\u306e\u9053\u6848\u5185;VH8-2-1. \u30ab\u30e9\u30df\u30e4\u306e\u6d1e\u7a9f\u30fb\u7948\u308a\u306e\u8def;VH8-2-2. \u30ab\u30e9\u30df\u30e4\u306e\u6d1e\u7a9f\u30fb\u6c37\u67f1\u306e\u9593;VH8-2-3. \u9759\u3051\u3055\u306b\u6f5c\u3080;VH8-2-4. \u4e0d\u7a4f\u306a\u4e88\u611f;VH8-2-5. \u30af\u30b8\u30f3\u30b7\u30fc\u3068\u306e\u6226\u3044".split(";"),
VH9:"VH9-1-1. \u7b2c\u4e00\u5e55\u30fb\u5e8f\u7ae0;VH9-1-2. \u7b2c\u4e00\u5e55\u30fb\u5e7b\u60f3;VH9-1-3. \u7b2c\u4e00\u5e55\u30fb\u5948\u843d;VH9-1-4. \u7b2c\u4e00\u5e55\u30fb\u673d\u3061\u308b;VH9-1-5. \u5e55\u9593;VH9-2-1. \u7b2c\u4e8c\u5e55\u30fb\u6f14\u821e;VH9-2-2. \u7b2c\u4e8c\u5e55\u30fb\u843d\u4e0b;VH9-2-3. \u7b2c\u4e8c\u5e55\u30fb\u4e00\u5fc3;VH9-2-4. \u7b2c\u4e8c\u5e55\u30fb\u5fd8\u308b\u308b\u4e8b\u306a\u304b\u308c;VH9-2-5. \u904a\u622f".split(";"),VH10:"VH10-1-1. \u30ab\u30e9\u30df\u30e4\u306e\u6d1e\u7a9f\u30fb\u5165\u308a\u53e3;VH10-1-2. \u5a18\u305f\u3061;VH10-1-3. \u6c34\u97f3\u3092\u305f\u3069\u308b(\u5263);VH10-1-4. \u30ab\u30e9\u30df\u30e4\u306e\u6d1e\u7a9f\u30fb\u5206\u304b\u308c\u9053(\u5263);VH10-1-5. \u8fd1\u4ed8\u304f\u6c17\u914d(\u683c\u95d8);VH10-2-1. \u30ab\u30e9\u30df\u30e4\u306e\u6d1e\u7a9f\u30fb\u6c37\u67f1\u306e\u9593(\u683c\u95d8);VH10-2-2. \u6e80\u3061\u308b\u6bba\u6c17(\u69cd);VH10-2-3. \u3086\u305a\u308c\u306c\u6226\u3044(\u69cd);VH10-2-4. \u30ab\u30e9\u30df\u30e4\u306e\u6d1e\u7a9f\u30fb\u6df1\u90e8(\u5927\u5263);VH10-2-5. \u6c7a\u6226(\u5927\u5263)".split(";"),
VH11:"VH11-1-1. \u96a0\u308c\u91cc\u3092\u76ee\u6307\u3057\u3066;VH11-1-2. \u30a6\u30a3\u30eb\u30df\u30f3\u30c8\u30f3\u30fb\u897f\u306e\u68ee;VH11-1-3. \u53cb\u306e\u5143\u3078(\u65a7);VH11-1-4. \u6d6e\u304d\u5cf6\u3078\u30fb\u305d\u306e1(\u65a7);VH11-1-5. \u6d6e\u304d\u5cf6\u3078\u30fb\u305d\u306e2(\u68cd\u68d2\u30fb\u9283);VH11-2-1. \u96a0\u308c\u91cc\u3092\u76ee\u6307\u3057\u3066\u30fb\u518d\u3073(\u68cd\u68d2\u30fb\u9283);VH11-2-2. \u96a0\u308c\u91cc\u3078\u306e\u9053\u30fb\u305d\u306e1(\u68cd\u68d2\u30fb\u9283);VH11-2-3. \u96a0\u308c\u91cc\u3078\u306e\u9053\u30fb\u305d\u306e2(\u5c0f\u5263);VH11-2-4. \u9ec4\u8272\u3044\u30c1\u30e7\u30a6\u3092\u8ffd\u3063\u3066(\u5c0f\u5263);VH11-2-5. \u6771\u306e\u6d1e\u304f\u3064(\u5c0f\u5263)".split(";"),
VH12:"VH12-1-1. \u65b0\u3057\u3044\u4efb\u52d9\u3078;VH12-1-2. \u30d0\u30f3\u30ac\u30fc\u30c9\u8fd1\u9053\u30fb\u68ee;VH12-1-3. \u5c71\u5cb3\u30fb\u4e2d\u8179(\u5f13);VH12-1-4. \u30b7\u30ce\u30f3\u3078\u306e\u9053\u306e\u308a(\u5f13);VH12-1-5. \u660e\u304b\u308a\u3092\u983c\u308a\u306b(\u706b\u98a8\u6756);VH12-2-1. \u9b54\u7363\u306e\u7fa4\u308c(\u706b\u98a8\u6756);VH12-2-2. \u9003\u8d70(\u6c34\u571f\u6756);VH12-2-3. \u9b54\u7363\u3069\u3082\uff01\u899a\u609f\uff01(\u6c34\u571f\u6756);VH12-2-4. \u5171\u95d8(\u5149\u95c7\u6756);VH12-2-5. \u6df1\u6df5\u3092\u7387\u3044\u3066(\u5149\u95c7\u6756)".split(";"),
G1:["VH\u5916\u4f1d1-1. \u30e1\u30c3\u30b5\u30ea\u30fc\u30ca\u306e\u5730\u4e0b\u305d\u306e1(\u7dd1\u77f3)","VH\u5916\u4f1d1-2. \u30e1\u30c3\u30b5\u30ea\u30fc\u30ca\u306e\u5730\u4e0b\u305d\u306e2(\u6a59\u77f3)","VH\u5916\u4f1d1-3. \u30e1\u30c3\u30b5\u30ea\u30fc\u30ca\u306e\u5730\u4e0b\u305d\u306e3(\u5263)","VH\u5916\u4f1d1-4. \u843d\u3068\u3057\u7a74(\u5263)","VH\u5916\u4f1d1-5. \u30c0\u30a6\u30c9\u3092\u63a2\u3057\u3066(\u683c\u95d8)"],G2:["VH\u5916\u4f1d2-1. \u96a0\u308c\u5bb6\u3078\u306e\u9053\u30fb\u305d\u306e1(\u683c\u95d8)",
"VH\u5916\u4f1d2-2. \u8ffd\u3063\u624b\u304c\u6765\u308b\u524d\u306b(\u69cd)","VH\u5916\u4f1d2-3. \u96a0\u308c\u5bb6\u3078\u306e\u9053\u30fb\u305d\u306e2(\u69cd)","VH\u5916\u4f1d2-4. \u96a0\u308c\u5bb6\u3078\u306e\u9053\u30fb\u305d\u306e3(\u5927\u5263)","VH\u5916\u4f1d2-5. \u6700\u5f8c\u306e\u7f60(\u5927\u5263)"]};
function _noLoginInitial(){var a={signInSuccessUrl:"https://nao-romasaga.github.io/partylist.html",signInOptions:[firebase.auth.TwitterAuthProvider.PROVIDER_ID]};(new firebaseui.auth.AuthUI(firebase.auth(appUsers))).start("#firebaseui-auth-container",a)}
function _initial(){var a,c,d;return $jscomp.asyncExecutePromiseGeneratorProgram(function(b){$(".isLogin").removeClass("d-none");for(a in QUEST_NAME)$("#QUEST").append('<option value="'+a+'">'+QUEST_NAME[a]+"</option>"),$("#QUEST_SEARCH").append('<option value="'+a+'">'+QUEST_NAME[a]+"</option>");c=$("<img>").attr("src",USER.photoURL).attr("style","width:40px; heidht:40px;    border-radius: 50%;");d=USER.displayName+" \u3055\u3093:\u30ed\u30b0\u30a4\u30f3\u4e2d";$("#firebaseui-auth-container").addClass("bg-white kadomaru").append(c).append(d);
return b.yield(init(),0)})}MY_STYLE=[];
function init(){var a,c;return $jscomp.asyncExecutePromiseGeneratorProgram(function(d){if(1==d.nextAddress)return $(".noLogin").hide(),$("#INPUT_ZONE").slideUp(),$("#SEARCH_ZONE").slideUp(),$("#SAVE_SUCCESS").slideUp(300),dispChar(CHAR_MASTER),$("#charData").show(),$('[data-toggle="tooltip"]').tooltip(),a=readStyleCheckData(UID,function(a){$("#mySS").text((void 0!==a.SS?a.SS.length:0)+"\u4f53");$("#myS").text((void 0!==a.S?a.S.length:0)+"\u4f53");$("#myA").text((void 0!==a.A?a.A.length:0)+"\u4f53");
for(var b in a)for(var c=$jscomp.makeIterator(a[b]),d=c.next();!d.done;d=c.next())MY_STYLE.push(d.value)}),d.yield(Promise.all([a]),2);c=databaseUser.ref("quest_data/");c.orderByChild("time").limitToFirst(20).once("value",function(a){displayParty(a.val())});$(".initialHide").removeClass("d-none");$(".initialShow").slideUp();d.jumpToEnd()})}
$(document).on("click","#tabInput",function(){$(".setsumi").hide();$("#tabInput").removeClass("style-tab-disabled").addClass("style-tab-active");$("#tabSearch").addClass("style-tab-disabled").removeClass("style-tab-active");$("#SEARCH_ZONE").slideUp(300,function(){$("#INPUT_ZONE").slideDown(300)})});
$(document).on("click","#tabSearch",function(){$(".setsumi").hide();$("#tabSearch").removeClass("style-tab-disabled").addClass("style-tab-active");$("#tabInput").addClass("style-tab-disabled").removeClass("style-tab-active");$("#INPUT_ZONE").slideUp(300,function(){$("#SEARCH_ZONE").slideDown(300)})});function closeInput(a){$(".fukidashiInput").each(function(){$(this).slideUp(250)})}
function resetParty(a){var c=[],d=PARTY_DATA.party;a.each(function(){var a=$(this).attr("data-charId"),e;for(e in d)d[e]["char"]===a&&c.push(Object.assign({},d[e]))});PARTY_DATA.party=c;checkSave()}
function resetPartySort(){var a={};$("#JINKEI_VERTICAL").children().each(function(){a[$(this).find(".vertical").attr("data-charId")]=$(this).clone();$(this).remove()});for(var c=0;c<PARTY_DATA.party.length;c++){var d=PARTY_DATA.party[c]["char"],b=PARTY_DATA.jinkei,e=c+1;a[d].find(".JINKEI_IMG").attr("src","./img/icon/icon_jinkei_"+b+e+".png");$("#JINKEI_VERTICAL").append(a[d])}}
function resetJinkei(){var a={};$("#JINKEI").children().each(function(){a[$(this).find(".char").attr("data-charId")]=$(this).clone();$(this).remove()});for(var c=0;c<PARTY_DATA.party.length;c++){var d=PARTY_DATA.party[c]["char"];$("#JINKEI").append(a[d])}var b=1;$("#JINKEI").find(".series-button").each(function(){$(this).text(b++)})}
function displayParty(a){var c,d,b;return $jscomp.asyncExecutePromiseGeneratorProgram(function(e){1==e.nextAddress&&(d=e.forIn(a));if(null==(c=d.getNext()))return e.jumpTo(0);b=a[c].party;try{a[c].party=JSON.parse(b)}catch(f){}return e.yield(setPartyList(c,a[c]),2)})}
$(document).ready(function(a){function c(b){var c=CHAR_MASTER[b];a(".charTmpl"+b).parents(".charTableParent").slideUp(500);selectDotReset(c);a("#PARTY").find(".charTmpl"+b).remove();a(".JINKEI"+b).remove();a(".JINKEI_VER"+b).remove();b=d(b);-1!==b&&PARTY_DATA.party.splice(b,1);checkSave()}function d(a){for(var b in PARTY_DATA.party)if(PARTY_DATA.party[b]["char"]===a)return b;return-1}a(".filterList").click(function(){a(".weaponList").addClass("d-none");var b=a(this).attr("href").substr(1);a(this).parent().hasClass("filterActive")?
(a(".SeriesChoise").removeClass("d-none"),a(".filterList").each(function(){a(this).parent().removeClass("filterActive")})):(a(".SeriesChoise").addClass("d-none"),a("#_"+b).removeClass("d-none"),a(".filterList").each(function(){a(this).parent().removeClass("filterActive")}),a(this).parent().toggleClass("filterActive"))});a(".JINKEI_CHOICE").click(function(){a(".jinkei_eq").each(function(){a(this).slideUp(300,function(){a(this).addClass("d-none")});a(this).slideDown(300)});var b=a(this).attr("data-id");
PARTY_DATA.jinkei=b;a("#JINKEI").children().slideUp(300,function(){a("#JINKEI").attr("class",b)});a("#JINKEI").children().slideDown(300);a(".JINKEI_IMG").each(function(c,d){var e=c+1;a(d).attr("src","./img/icon/icon_jinkei_"+b+e+".png")});a(this).parent().find(".jinkei_eq").slideUp(300,function(){a(this).removeClass("d-none")});a(this).parent().find(".jinkei_eq").slideDown(300)});Sortable.create(JINKEI,{animation:500,onChoose:function(b){a(".JINKEI_CHAR").each(function(){a(this).removeClass("char-damage").addClass("char-winner")});
a(b.item).find(".char").removeClass("char-winner").addClass("char-damage")},onEnd:function(b){a(b.item).find(".char").removeClass("char-damage").addClass("char-winner");resetParty(a("#JINKEI").find(".char"));resetPartySort();resetJinkei()},onSort:function(a){},onChange:function(a){}});Sortable.create(JINKEI_VERTICAL,{animation:500,onChoose:function(a){},onEnd:function(b){resetParty(a("#JINKEI_VERTICAL").find(".vertical"));resetPartySort();resetJinkei()},onSort:function(a){},onChange:function(a){}});
initialHide();a(".tab-content").on("click",function(){});a('[data-toggle="tooltip"]').tooltip();a(document).on("click",".openMenu, .nowData > td, .btn_close",function(){var b=a(this).parents(".charTable").attr("data-charId");a(".charTmpl"+b).find(".fukidashiInput").slideToggle(250)});a(document).on("click",".charUnset",function(){var b=a(this).attr("data-id");c(b);resetJinkei()});a(document).on("click",".tab-content .char, .weaponList  .char",function(){var b=this,e,f,h,k,g;return $jscomp.asyncExecutePromiseGeneratorProgram(function(l){e=
a(b).attr("data-id");f=d(e);if(5<=PARTY_DATA.party.length||-1!==f){for(;5<PARTY_DATA.party.length;)h=PARTY_DATA.party.length,k=PARTY_DATA.party[h-1]["char"],c(k),PARTY_DATA.party.pop();a(b).removeClass("char-aruku").addClass("char-loser");return l["return"]()}g=CHAR_MASTER[e].Holders[0];PARTY_DATA.party.push({"char":e,style:g});selectDotHensei(CHAR_MASTER[e]);readUserDataWithId("CHAR",e,function(b){return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){if(1==c.nextAddress)return c.yield(displayCharInfo(CHAR_MASTER[e],
b),2);if(3!=c.nextAddress)return c.yield(displayStyleInfo(CHAR_MASTER[e].Id,g),3);a("html,body").animate({scrollTop:a(".charTmpl"+e).offset().top},500,"swing");c.jumpToEnd()})});a('[data-toggle="tooltip"]').tooltip();checkSave();l.jumpToEnd()})});a(document).on("click",".style",function(){var b=this,c,f,h;return $jscomp.asyncExecutePromiseGeneratorProgram(function(e){if(1==e.nextAddress)return c=a(b).attr("data-id"),f=a(b).parents(".charTable").attr("data-charId"),e.yield(displayStyleInfo(f,c),2);
h=d(f);PARTY_DATA.party[h].style=c;checkSave();e.jumpToEnd()})});a("#QUEST").change(function(){var b=a("#QUEST option:selected").val();PARTY_DATA.quest_lv=b;a("#QUEST_CHOICE option").remove();a("#QUEST_CHOICE").append('<option value="0">\u30af\u30a8\u30b9\u30c8\u9078\u629e</option>');PARTY_DATA.quest="";checkSave();if("0"!==b){b=$jscomp.makeIterator(QUEST[b]);for(var c=b.next();!c.done;c=b.next()){c=c.value;var d=c.split(".");a("#QUEST_CHOICE").append('<option value="'+d[0]+'">'+c+"</option>")}}});
a("#QUEST_CHOICE").change(function(){var b=a("#QUEST_CHOICE option:selected").val();PARTY_DATA.quest=b;checkSave()});a("#BATTLE_MODE").change(function(){var b=a("#BATTLE_MODE option:selected").val();PARTY_DATA.mode=b;checkSave()});a("#SAVE").click(function(){if(a(this).hasClass("icon_btn_on")){var b=Object.assign({},PARTY_DATA);b.party=JSON.stringify(PARTY_DATA.party);b.time=-1*Math.floor((new Date).getTime()/1E3);b.text=encodeURI(a("#FREE_TEXT").val());b.quest=encodeURI(PARTY_DATA.quest);b.quest_lv=
encodeURI(PARTY_DATA.quest_lv);b.mode=void 0===PARTY_DATA.mode?0:Number(PARTY_DATA.mode);addData("quest_data",b);a(this).removeClass("icon_btn_on").addClass("icon_btn_off");a("#SAVE_SUCCESS").slideDown(300)}});a("#DISP_CHANGE").click(function(){a("#DISP_LIST").slideUp(200,function(){a("#DISP_LIST").toggleClass("d-none");a("#DISP_LIST").slideDown(200)});a("#DISP_DOT").slideUp(200,function(){a("#DISP_DOT").toggleClass("d-none");a("#DISP_DOT").slideDown(200)})});a("#FREE_TEXT").keyup(function(){a("#nowtext").text(a("#FREE_TEXT").val().length)});
a(document).on("keyup",".battle",function(){var b=a(this).parents(".charTable"),c=b.attr("data-charId"),d=Number(a(this).val());!isNaN(d)&&0<d?(d=9999<d?9999:d,b.find(".battlePower").html(' / <img src="./img/icon/icon_battle.png" width=20>'+d.toLocaleString())):(d=0,b.find(".battlePower").text(""));for(b=0;b<PARTY_DATA.party.length;b++)if(c===PARTY_DATA.party[b]["char"]){PARTY_DATA.party[b].battle=d;break}});a(document).on("click",".DELETE_BTN",function(){var b=a(this).attr("data-id");a(".row"+b).each(function(){a(this).remove()});
databaseUser.ref("quest_data/"+b).remove()});a(".JINKEI_SEARCH").click(function(){var b=a(this).attr("data-id"),c=a(this).hasClass("on")?1:.5;SEARCH_DATA.jinkei=a(this).hasClass("on")?"":b;a(".JINKEI_SEARCH").each(function(){a(this).removeClass("on");a(this).css("opacity",c)});a(this).hasClass("on")?a(this).removeClass("on"):a(this).addClass("on");a(this).css("opacity",1)});a("#QUEST_SEARCH").change(function(){var b=a("#QUEST_SEARCH option:selected").val();SEARCH_DATA.quest_lv=b;a("#QUEST_CHOICE_SEARCH option").remove();
a("#QUEST_CHOICE_SEARCH").append('<option value="0">\u30af\u30a8\u30b9\u30c8\u9078\u629e</option>');SEARCH_DATA.quest="";if("0"!==b){b=$jscomp.makeIterator(QUEST[b]);for(var c=b.next();!c.done;c=b.next()){c=c.value;var d=c.split(".");a("#QUEST_CHOICE_SEARCH").append('<option value="'+d[0]+'">'+c+"</option>")}}});a("#QUEST_CHOICE_SEARCH").change(function(){var b=a("#QUEST_CHOICE_SEARCH option:selected").val();SEARCH_DATA.quest="0"===b?"":b});a("#BATTLE_MODE_SEARCH").change(function(){var b=a("#BATTLE_MODE_SEARCH option:selected").val();
SEARCH_DATA.mode="0"===b?"":b});a("#ALLSTYLE_SEARCH").click(function(){SEARCH_DATA.my=0});a("#MYSTYLE_SEARCH").click(function(){SEARCH_DATA.my=1});a("#BATTLE_MODE_SEARCH").change(function(){var b=a("#BATTLE_MODE_SEARCH option:selected").val();SEARCH_DATA.mode=b});a("#SEARCH").click(function(){if(0===USER_PARTY_LIST.length)databaseUser.ref("quest_data/").once("value",function(a){USER_PARTY_LIST=a.val();reDrawParty()});else reDrawParty()})});
function reDrawParty(){var a=USER_PARTY_LIST,c=[],d;for(d in a)if(""==SEARCH_DATA.quest||0==SEARCH_DATA.quest||a[d].quest==SEARCH_DATA.quest)if(""==SEARCH_DATA.quest_lv||0==SEARCH_DATA.quest_lv||a[d].quest_lv==SEARCH_DATA.quest_lv)if(""==SEARCH_DATA.mode||0==SEARCH_DATA.mode||a[d].mode==SEARCH_DATA.mode)if(""==SEARCH_DATA.jinkei||0==SEARCH_DATA.jinkei||a[d].jinkei==SEARCH_DATA.jinkei){if(1===SEARCH_DATA.my){var b=a[d].party;try{a[d].party=JSON.parse(b)}catch(h){}b=!1;for(var e=$jscomp.makeIterator(a[d].party),
f=e.next();!f.done;f=e.next())-1===MY_STYLE.indexOf(f.value.style)&&(b=!0);if(b)continue}c.push(a[d])}$("#PARTY_TABLE").html("");displayParty(c)}
function checkSave(){PARTY_DATA.uid=UID;void 0!==PARTY_DATA.uid&&""!==PARTY_DATA.quest_lv&&"0"!==PARTY_DATA.quest_lv&&""!==PARTY_DATA.quest&&"0"!==PARTY_DATA.quest&&""!==PARTY_DATA.jinkei&&5===PARTY_DATA.party.length&&55>=$("#FREE_TEXT").val().length?$("#SAVE").addClass("icon_btn_on").removeClass("icon_btn_off"):$("#SAVE").addClass("icon_btn_off").removeClass("icon_btn_on")}function initialHide(){}
function displayCharInfo(a,c){var d,b,e,f,h,k,g,l,q,v,p,u,m,n,x,w,r,t,y,A,B,z,C,D,E,F,G,H,I,J,K;return $jscomp.asyncExecutePromiseGeneratorProgram(function(L){d=a.Id;b=$("#CHAR_TEMPLATE").clone().removeClass("d-none").removeAttr("id").addClass("charTmpl"+d).attr("data-charId",d);b.find(".charName").html(a.Name);b.find(".icon_btn_on").attr("data-id",d);b.find(".charUnset").attr("data-id",d);b.find(".openMenu").attr("data-id",d);b.find(".char").parent().attr("data-id",d);e=a.DotId;f="ID4e2c8"!==e?e:
"ID4e2c9";h=getImgUrl("dot/"+f+".png")+dotStyle;b.find(".dot_mid").attr("style",h);if(null!==c)for(k=$jscomp.makeIterator(PARAM_KEY_HP),g=k.next();!g.done;g=k.next())l=g.value,a["NOW"+l]=Number(c[l]);else if(null===c)for(q=$jscomp.makeIterator(PARAM_KEY),g=q.next();!g.done;g=q.next())v=g.value,a["NOW"+v]=0;p=b.find(".nowData");p.attr("data-id",d);u=$jscomp.makeIterator(PARAM_KEY_HP);for(g=u.next();!g.done;g=u.next())m=g.value,b.find(".char"+m).removeClass("char"+m).addClass("charInput"+m+d).val(a["NOW"+
m]),p.find("."+m).removeClass("char"+m).addClass("char"+m+d).text(a["NOW"+m]);n="";x=ICON_LIST[a.WeaponType];w=$jscomp.makeIterator(a.Holders);for(r=w.next();!r.done;r=w.next())t=r.value,y=STYLE_MASTER[t],""==n&&(n=y.Rarity),A=$("<button>").addClass("style").addClass(getStyleIconClass(y.Rarity)).attr("style",getImgUrl("style_icon/"+t+".png")).attr("data-id",t),B=$("<span>").addClass(getStyleIconBgClass(y.Rarity)).append(A),b.find(".STYLE_ICON").append(B);z=b.find(".DISP_ICON");z.find(".icn").attr("src",
"./img/style_icon/"+a.Holders[0]+".png");z.find(".cin").attr("src","./img/style_cutin/"+a.Holders[0]+".png");C=$("#JINKEI").children().length+1;D='<p class="JINKEI_POS series-button text-center jinkei_pos">'+C+"</p>";E='<span class="JINKEI_CHAR char-winner char dot_mid dot" style="'+getImgUrl("dot/"+f+".png")+"\" data-charId='"+d+"' data-dotId='"+f+"' data-styleId=''></span>";F=PARTY_DATA.jinkei;G=Number($("#JINKEI_VERTICAL").children().length)+1;$("#JINKEI").append($("<div>").addClass("JINKEI"+d).append(D+
E));H='<img class="1 rare'+d+'" src="./img/icon/icon_'+n+'.png" width=45 style="position: absolute;">';I='<img class="2" src="./img/icon/'+x+'.png" width=45 style="position: absolute; left:20px;">';J='<img class="vertical ver'+d+'" data-charId="'+d+'" src="./img/style_vertical/'+a.Holders[0]+'.png" height=260 style="border: solid 2px gold; border-radius: 6px;">';$("#JINKEI_VERTICAL").append('<div class="JINKEI_VER'+d+'" data-charId="'+d+"\" style='position: relative;'>"+H+I+J+'<br><img class="JINKEI_IMG" src="./img/icon/icon_jinkei_'+
F+G+'.png" width=63>');K=$("<div class='charTableParent'>").append(b);$("#PARTY").append(K);L.jumpToEnd()})}
function setPartyList(a,c){var d,b,e,f,h,k,g,l,q,v,p,u,m,n,x,w,r;return $jscomp.asyncExecutePromiseGeneratorProgram(function(t){if(0<$("#"+a).length)return t["return"]();d=decodeURI(c.text);d=void 0===d?"":d;b=decodeURI(c.quest);e=decodeURI(c.quest_lv);f=b;void 0!==QUEST_NAME[e]&&(f=QUEST_NAME[e]+" / "+b);h=["","[\u5168\u529b\u30aa\u30fc\u30c8]","[\u624b\u52d5]","[\u624b\u52d5+\u30aa\u30fc\u30c8]"];k=void 0!==c.mode?Number(c.mode):0;$row1=$("#TMPL_ROW1").clone().attr("id",a).addClass("row"+a);$row2=
$("#TMPL_ROW2").clone().attr("id","").addClass("row"+a);$row3=$("#TMPL_ROW3").clone().attr("id","").addClass("row"+a);g=0;for(l in c.party)q=Number(l)+1,v=c.party[l].style,p=void 0!==c.party[l].battle?Number(c.party[l].battle):0,g+=p,u=STYLE_MASTER[v],m=u.Rarity,n="gold","S"===m?n="silver":"A"===m&&(n="coral"),x='<img src="./img/style_icon/'+v+'.png" width="40" style="border: 2px solid '+n+'; border-radius: 5px;">',w='<img src="./img/icon/icon_jinkei_'+c.jinkei+q+'.png" width="40">',r=0<p?'<br><img src="./img/icon/icon_battle.png" class="hidden pcBlock" width="22">'+
p.toLocaleString():"",$row2.find(".char"+q).append(x).append(w).append(r);f+=0<k?"<br>"+h[k]:"";0<g&&(f+=0<k?"":"<br>",f+='<img src="./img/icon/icon_battle.png" width="22">'+g.toLocaleString());$row1.find(".TMPL_QUEST").html(f);$row2.find(".TMPL_QUEST").html(f);$row2.find(".TMPL_ADVICE").text(d);$row3.find(".TMPL_ADVICE").text(d);$row2.find(".DELETE_BTN").attr("data-id",a);$row3.find(".DELETE_BTN").attr("data-id",a);c.uid!==UID&&($row2.find(".DELETE_BTN").addClass("d-none").attr("data-id",a),$row3.find(".DELETE_BTN").addClass("d-none").attr("data-id",
a));$("#PARTY_TABLE").prepend($row3);$("#PARTY_TABLE").prepend($row2);$("#PARTY_TABLE").prepend($row1);t.jumpToEnd()})}
function displayStyleInfo(a,c){var d,b,e,f,h,k;return $jscomp.asyncExecutePromiseGeneratorProgram(function(g){d=STYLE_MASTER[c];if(null===d)return g["return"]();$(".charTmpl"+a).attr("data-styleId",c);$(".charTmpl"+a).find(".style").each(function(){var a=$(this).attr("data-id");$(this).parent().addClass("opacity_nocheck");c===a&&$(this).parent().removeClass("opacity_nocheck")});b=d.DotId;e=d.Id;f=$(".charTmpl"+a).find(".DISP_ICON");h=$(".ver"+a);k=$(".rare"+a);k.slideUp(100);h.slideUp(300,function(){h.attr("src",
"./img/style_vertical/"+e+".png");k.attr("src","./img/icon/icon_"+d.Rarity+".png")});h.slideDown(300);k.slideDown(300);f.find(".toggle").slideUp(300,function(){f.find(".icn").attr("src","./img/style_icon/"+e+".png");f.find(".cin").attr("src","./img/style_cutin/"+e+".png")});f.find(".toggle").slideDown(300);$(".JINKEI"+a).find("span").attr("style",getImgUrl("dot/"+b+".png"));g.jumpToEnd()})}
function getSmallIcon(a){var c=$("<button>").addClass(getStyleIconClass(a.Rarity)+"_small").attr("style",getImgUrl("style_icon/"+a.Id+".png"));return $("<span>").addClass(getStyleIconBgClass(a.Rarity)).attr("style","height: 30px;").append(c)}function selectDotReset(a){$(".dot"+a.DotId).removeClass("char-winner").addClass("char-aruku").find(".series-button").text(a.Series)}
function selectDotHensei(a){$(".dot"+a.DotId).removeClass("char-aruku").removeClass("char-loser").addClass("char-winner").find(".series-button").text("\u7de8\u6210\u4e2d")};