var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){a!=Array.prototype&&a!=Object.prototype&&(a[b]=d.value)};
$jscomp.polyfill=function(a,b,d,e){if(b){d=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var f=a[e];f in d||(d[f]={});d=d[f]}a=a[a.length-1];e=d[a];b=b(e);b!=e&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function b(){this.batch_=null}function d(a){return a instanceof f?a:new f(function(b,d){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;b.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})}this.batch_.push(a)};var e=$jscomp.global.setTimeout;b.prototype.asyncExecuteFunction=function(a){e(a,0)};b.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var d=a[b];a[b]=null;try{d()}catch(m){this.asyncThrow_(m)}}}this.batch_=null};b.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var f=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(l){b.reject(l)}};f.prototype.createResolveAndReject_=function(){function a(a){return function(f){d||(d=!0,a.call(b,f))}}var b=this,d=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};f.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof f)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};f.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(l){this.reject_(l);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};f.prototype.reject_=function(a){this.settle_(2,a)};f.prototype.fulfill_=function(a){this.settle_(1,a)};f.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};f.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)g.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var g=new b;f.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};f.prototype.settleSameAsThenable_=function(a,b){var d=this.createResolveAndReject_();try{a.call(b,d.resolve,d.reject)}catch(m){d.reject(m)}};f.prototype.then=function(a,b){function d(a,b){return"function"==typeof a?function(b){try{e(a(b))}catch(n){g(n)}}:b}var e,g,h=new f(function(a,b){e=a;g=b});this.callWhenSettled_(d(a,e),d(b,g));return h};
f.prototype["catch"]=function(a){return this.then(void 0,a)};f.prototype.callWhenSettled_=function(a,b){function d(){switch(e.state_){case 1:a(e.result_);break;case 2:b(e.result_);break;default:throw Error("Unexpected state: "+e.state_);}}var e=this;null==this.onSettledCallbacks_?g.asyncExecute(d):this.onSettledCallbacks_.push(d)};f.resolve=d;f.reject=function(a){return new f(function(b,d){d(a)})};f.race=function(a){return new f(function(b,e){for(var f=$jscomp.makeIterator(a),g=f.next();!g.done;g=
f.next())d(g.value).callWhenSettled_(b,e)})};f.all=function(a){var b=$jscomp.makeIterator(a),e=b.next();return e.done?d([]):new f(function(a,f){function g(b){return function(d){h[b]=d;k--;0==k&&a(h)}}var h=[],k=0;do h.push(void 0),k++,d(e.value).callWhenSettled_(g(h.length-1),f),e=b.next();while(!e.done)})};return f},"es6","es3");
$jscomp.polyfill("Promise.prototype.finally",function(a){return a?a:function(a){return this.then(function(b){return Promise.resolve(a()).then(function(){return b})},function(b){return Promise.resolve(a()).then(function(){throw b;})})}},"es9","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,b){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:b})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(d){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(d||"")+"_"+b++,d)}var b=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},b={};try{return b.__proto__=a,b.a}catch(d){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype["return"]=function(a){this.abruptCompletion_={"return":a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,b){this.nextAddress=b;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,b){var d=$jscomp.makeIterator(a),e=d.next();$jscomp.generator.ensureIteratorResultIsObject_(e);if(e.done)this.yieldResult=e.value,this.nextAddress=b;else return this.yieldAllIterator_=d,this.yield(e.value,b)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,b){this.catchAddress_=a;void 0!=b&&(this.finallyAddress_=b)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,b){this.nextAddress=a;this.catchAddress_=b||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,b,d){d?this.finallyContexts_[d]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=b||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,b){var d=this.finallyContexts_.splice(b||0)[0];if(d=this.abruptCompletion_=this.abruptCompletion_||d){if(d.isException)return this.jumpToErrorHandler_();void 0!=d.jumpTo&&this.finallyAddress_<d.jumpTo?(this.nextAddress=d.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var b in a)this.properties_.push(b);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var b=this.context_.yieldAllIterator_;if(b)return this.yieldAllStep_("return"in b?b["return"]:function(a){return{value:a,done:!0}},a,this.context_["return"]);this.context_["return"](a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,b,d){try{var e=a.call(this.context_.yieldAllIterator_,b);$jscomp.generator.ensureIteratorResultIsObject_(e);if(!e.done)return this.context_.stop_(),e;var f=e.value}catch(g){return this.context_.yieldAllIterator_=null,this.context_.throw_(g),this.nextStep_()}this.context_.yieldAllIterator_=null;d.call(this.context_,f);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(b){this.context_.yieldResult=void 0,this.context_.throw_(b)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a["return"],done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(b){return a.next_(b)};this["throw"]=function(b){return a.throw_(b)};this["return"]=function(b){return a.return_(b)};$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,b){var d=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(b));$jscomp.setPrototypeOf&&$jscomp.setPrototypeOf(d,a.prototype);return d};
$jscomp.asyncExecutePromiseGenerator=function(a){function b(b){return a.next(b)}function d(b){return a["throw"](b)}return new Promise(function(e,f){function g(a){a.done?e(a.value):Promise.resolve(a.value).then(b,d).then(g,f)}g(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
var SKILL_MASTER,STYLE_MASTER,ABILITY_MASTER,CHAR_MASTER,skillTypeList={},NOW_LIST,optionList={"\u5263":"skill_ken","\u5927\u5263":"skill_dken","\u65a7":"skill_ono","\u5c0f\u5263":"skill_sken","\u69cd":"skill_yari","\u5f13":"skill_yumi","\u68cd\u68d2":"skill_kon","\u4f53\u8853":"skill_tai","\u9283":"skill_ju","\u6756":"skill_tsue","\u8fd1":"skill_kin","\u9060":"skill_en","\u65ac":"skill_zan","\u7a81":"skill_totsu","\u6253":"skill_da","\u71b1":"skill_netsu","\u51b7":"skill_rei","\u96f7":"skill_rai",
"\u9670":"skill_in","\u967d":"skill_yo","\u6575\u5358\u4f53":"skill_tantai","\u6575\u7e26\u4e00\u5217":"skill_tate","\u6575\u6a2a\u4e00\u5217":"skill_yoko","\u76f4\u63a5":"skill_cyoku","\u9593\u63a5":"skill_kan","\u6575\u5168\u4f53":"skill_zentai","\u81ea\u8eab":"skill_jishin","\u5473\u65b9\u5358\u4f53":"skill_mikata","\u6575\u30e9\u30f3\u30c0\u30e0":"skill_random","\u30d5\u30a1\u30b9\u30c8":"skill_fast","\u30c7\u30a3\u30ec\u30a4":"skill_delay","\u706b\u8853":"skill_hi","\u6c34\u8853":"skill_mizu",
"\u98a8\u8853":"skill_kaze","\u571f\u8853":"skill_tsuchi","\u5149\u8853":"skill_hikari","\u95c7\u8853":"skill_yami","\u30b9\u30bf\u30f3":"skill_sutan","\u30de\u30d2":"skill_mahi","\u5373\u6b7b":"skill_sokushi","\u6bd2":"skill_doku","\u77f3\u5316":"skill_sekika","\u9b45\u4e86":"skill_miryo","\u7720\u308a":"skill_nemuri","\u6df7\u4e71":"skill_konran","\u72c2\u6226\u58eb":"skill_kyosenshi","\u6697\u95c7":"skill_kurayami","\u8155\u529b":"skill_deb_wan","\u4f53\u529b":"skill_deb_tai","\u5668\u7528\u3055":"skill_deb_kiyo",
"\u7d20\u65e9\u3055":"skill_deb_suba","\u77e5\u529b":"skill_deb_chi","\u7cbe\u795e":"skill_deb_sei",E:"skill_iryoku_e",D:"skill_iryoku_d",C:"skill_iryoku_c",B:"skill_iryoku_b",A:"skill_iryoku_a",S:"skill_iryoku_s",SS:"skill_iryoku_ss",SSS:"skill_iryoku_sss","-":"skill_iryoku_none","\u6d6e\u904a":"skill_crit_fuyu","\u4e0d\u6b7b":"skill_crit_fushi","\u6c34\u68f2":"skill_crit_suise","\u690d\u7269":"skill_crit_shoku","\u866b":"skill_crit_mushi","\u9aa8":"skill_crit_hone","\u5ca9\u77f3":"skill_crit_gan",
"\u4eba\u9593":"skill_crit_nin","\u5973\u6027":"skill_crit_jo","\u30ab\u30a8\u30eb":"skill_crit_kaeru","\u7363":"skill_crit_kemo","\u706b\u7cbe":"skill_crit_fire","\u9b5a":"skill_crit_fish","\u60aa\u9b54":"skill_crit_devil"},color="black blue green orange purple red yellow white".split(" "),color2="\u9ed2\u9752\u7dd1\u6a59\u7d2b\u8d64\u9ec4\u767d".split(""),SKILL_NAME_LABEL={ken:"\u5263",dken:"\u5927\u5263",ono:"\u65a7",yari:"\u69cd",sken:"\u5c0f\u5263",yumi:"\u5f13",kon:"\u68cd\u68d2",tai:"\u4f53\u8853",
ju:"\u9283",hi:"\u706b\u8853",mizu:"\u6c34\u8853",kaze:"\u98a8\u8853",tsuchi:"\u571f\u8853",hikari:"\u5149\u8853",yami:"\u95c7\u8853",zan:"\u65ac\u5c5e\u6027",da:"\u6253\u5c5e\u6027",totsu:"\u7a81\u5c5e\u6027",netsu:"\u71b1\u5c5e\u6027",rei:"\u51b7\u5c5e\u6027",rai:"\u96f7\u5c5e\u6027","in":"\u9670\u5c5e\u6027",you:"\u967d\u5c5e\u6027",doku:"\u6bd2\u4ed8\u4e0e",mahi:"\u30de\u30d2\u4ed8\u4e0e",kurayami:"\u6697\u95c7\u4ed8\u4e0e",sutan:"\u30b9\u30bf\u30f3\u4ed8\u4e0e",nemuri:"\u7761\u7720\u4ed8\u4e0e",
sekika:"\u77f3\u5316\u4ed8\u4e0e",konran:"\u6df7\u4e71\u4ed8\u4e0e",miryo:"\u9b45\u4e86\u4ed8\u4e0e",kyosenshi:"\u72c2\u6226\u58eb\u4ed8\u4e0e",sokushi:"\u5373\u6b7b",deb_wan:"\u8155\u529b\u6e1b\u5c11\u4ed8\u4e0e",deb_tai:"\u4f53\u529b\u6e1b\u5c11\u4ed8\u4e0e",deb_kiyo:"\u5668\u7528\u3055\u6e1b\u5c11\u4ed8\u4e0e",deb_suba:"\u7d20\u65e9\u3055\u6e1b\u5c11\u4ed8\u4e0e",deb_chi:"\u77e5\u529b\u6e1b\u5c11\u4ed8\u4e0e",deb_sei:"\u7cbe\u795e\u6e1b\u5c11\u4ed8\u4e0e",zentai:"\u5168\u4f53\u653b\u6483",tate:"\u7e26\u4e00\u5217\u653b\u6483",
yoko:"\u6a2a\u4e00\u5217\u653b\u6483",mikata:"\u5473\u65b9\u5358\u4f53\u5bfe\u8c61",kin:"\u8fd1\u63a5\u653b\u6483",en:"\u9060\u8ddd\u96e2\u653b\u6483",jishin:"\u81ea\u8eab\u304c\u5bfe\u8c61",fast:"\u30d5\u30a1\u30b9\u30c8\u52b9\u679c",delay:"\u30c7\u30a3\u30ec\u30a4\u52b9\u679c",iryoku_e:"\u6280\u5a01\u529b[E]",iryoku_d:"\u6280\u5a01\u529b[D]",iryoku_c:"\u6280\u5a01\u529b[C]",iryoku_b:"\u6280\u5a01\u529b[B]",iryoku_a:"\u6280\u5a01\u529b[A]",iryoku_s:"\u6280\u5a01\u529b[S]",iryoku_ss:"\u6280\u5a01\u529b[SS]",
iryoku_sss:"\u6280\u5a01\u529b[SSS]",kan:"\u9593\u63a5\u653b\u6483",cyoku:"\u76f4\u63a5\u653b\u6483",crit_fuyu:"\u6d6e\u904a\u7279\u52b9",crit_fushi:"\u4e0d\u6b7b\u7279\u52b9",crit_suise:"\u6c34\u68f2\u7279\u52b9",crit_shoku:"\u690d\u7269\u7279\u52b9",crit_mushi:"\u866b\u7279\u52b9",crit_hone:"\u9aa8\u7279\u52b9",crit_gan:"\u5ca9\u77f3\u7279\u52b9",crit_nin:"\u4eba\u9593\u7279\u52b9",crit_jo:"\u5973\u6027\u7279\u52b9",crit_kaeru:"\u30ab\u30a8\u30eb\u7279\u52b9",crit_kemo:"\u7363\u7279\u52b9",crit_fire:"\u706b\u7cbe\u7279\u52b9",
crit_fish:"\u9b5a\u7279\u52b9",crit_devil:"\u60aa\u9b54\u7279\u52b9"},SKILL_NAME_SEARCH={ken:"\u5263",dken:"\u5927\u5263",ono:"\u65a7",yari:"\u69cd",sken:"\u5c0f\u5263",yumi:"\u5f13",kon:"\u68cd\u68d2",tai:"\u4f53\u8853",ju:"\u9283",hi:"\u706b\u8853",mizu:"\u6c34\u8853",kaze:"\u98a8\u8853",tsuchi:"\u571f\u8853",hikari:"\u5149\u8853",yami:"\u95c7\u8853",zan:"\u65ac",da:"\u6253",totsu:"\u7a81",netsu:"\u71b1",rei:"\u51b7",rai:"\u96f7","in":"\u9670",yo:"\u967d",doku:"\u6bd2",mahi:"\u30de\u30d2",kurayami:"\u6697\u95c7",
sutan:"\u30b9\u30bf\u30f3",nemuri:"\u7720\u308a",sekika:"\u77f3\u5316",konran:"\u6df7\u4e71",miryo:"\u9b45\u4e86",kyosenshi:"\u72c2\u6226\u58eb",sokushi:"\u5373\u6b7b",deb_wan:"\u8155\u529b",deb_tai:"\u4f53\u529b",deb_kiyo:"\u5668\u7528\u3055",deb_suba:"\u7d20\u65e9\u3055",deb_chi:"\u77e5\u529b",deb_sei:"\u7cbe\u795e",zentai:"\u6575\u5168\u4f53",tate:"\u6575\u7e26\u4e00\u5217",yoko:"\u6575\u6a2a\u4e00\u5217",mikata:"\u5473\u65b9\u5358\u4f53",kin:"\u8fd1",en:"\u9060",jishin:"\u81ea\u8eab",iryoku_e:"E",
iryoku_d:"D",iryoku_c:"C",iryoku_b:"B",iryoku_a:"A",iryoku_s:"S",iryoku_ss:"SS",iryoku_sss:"SSS",crit_fuyu:"\u6d6e\u904a",crit_fushi:"\u4e0d\u6b7b",crit_suise:"\u6c34\u68f2",crit_shoku:"\u690d\u7269",crit_mushi:"\u866b",crit_hone:"\u9aa8",crit_gan:"\u5ca9\u77f3",crit_nin:"\u4eba\u9593",crit_jo:"\u5973\u6027",crit_kaeru:"\u30ab\u30a8\u30eb",crit_kemo:"\u7363",crit_fire:"\u706b\u7cbe",crit_fish:"\u9b5a",crit_devil:"\u60aa\u9b54"},i;
for(i in color){var c=color[i];optionList[c+"1"]="skill_"+c+"1";optionList[c+"2"]="skill_"+c+"2";optionList[c+"3"]="skill_"+c+"3";SKILL_NAME_LABEL[c+"1"]=color2[i]+"\u7802";SKILL_NAME_LABEL[c+"2"]=color2[i]+"\u77f3";SKILL_NAME_LABEL[c+"3"]=color2[i]+"\u5b9d\u77f3"}for(var i$2=1;20>=i$2;i$2++)optionList["bp"+i$2]="skill_bp"+i$2,SKILL_NAME_SEARCH["bp"+i$2]=i$2;for(var key$3 in optionList)skillTypeList[optionList[key$3]]=[];read();var SKILL_MASTER_LIST=[];
function read(){var a,b,d,e;return $jscomp.asyncExecutePromiseGeneratorProgram(function(f){if(1==f.nextAddress)return a=readFile("Char",function(a){CHAR_MASTER=a}),b=readFile("Skill",function(a){SKILL_MASTER=a;createSkillMasterList(SKILL_MASTER);countSkill(SKILL_MASTER)}),d=readFile("Style",function(a){STYLE_MASTER=a}),e=readFile("Ability",function(a){ABILITY_MASTER=a}),f.yield(Promise.all([a,b,d,e]),2);firebase.database().goOffline();firebase.database(appUsers).goOffline();f.jumpToEnd()})}
function filterList(a,b,d){var e=-1<["BattleType","PowerGrade","ConsumeBp"].indexOf(d)?!0:!1;if("AttackKansetsu"===d){for(var f in b)b[f]="kan"===b[f]?!0:!1;e=!0}f=[];for(var g in a)for(var h=$jscomp.makeIterator(b),k=h.next();!k.done;k=h.next())k=k.value,e&&a[g][d]===k?f.push(a[g]):!e&&-1<a[g][d].indexOf(k)&&f.push(a[g]);return f}
$(document).ready(function(a){a(".selectJoken").hide();a("._FilterLink").click(function(){a(".selectJoken").hide();a(this).toggleClass("filterActive");a("table#skill_holder_table tbody *").remove();a("#skill_holder_list").html("");var b=SKILL_MASTER_LIST.concat(),d={},e=[],f=!1;a("._FilterLink").each(function(){if(a(this).hasClass("filterActive")){f=!0;a(this).attr("href").substr(1);var b=a(this).attr("href").substr(7);e.push(SKILL_NAME_LABEL[b]);var g=a(this).attr("data-col");void 0===d[g]&&(d[g]=
[]);d[g].push(void 0!==SKILL_NAME_SEARCH[b]?SKILL_NAME_SEARCH[b]:b)}});for(var g in d)b=filterList(b,d[g],g);countSkill(b);NOW_LIST=b;a("#skill_name_label").text(e.join("&"));a("#skillList").hide();a("#skillList").html("");a("#skill_damage_ranking").html("");a("#SKILL_NAME").html("");a("#SKILL_TEXT").html("");if(f){a(".selectJoken").show();g="bp";var h=!0;a("#SORT_IRYOKU").hasClass("icon_btn_on")?(g="iryoku",h=a("#SORT_IRYOKU").hasClass("desc")):h=a("#SORT_BP").hasClass("desc");"bp"===g?sortSkillBP(b,
h):sortSkillIryoku(b,h)}});a(document).on("click",".skill_select",function(){var b=a(this).attr("data-id");displaySkillHolders(b)});a(".sortButton").click(function(){a(".sortButton").removeClass("icon_btn_on").addClass("icon_btn_off");a(this).removeClass("icon_btn_off").addClass("icon_btn_on");var b=!1;a(this).hasClass("asc")?(b=!0,a(this).removeClass("asc").addClass("desc")):a(this).removeClass("desc").addClass("asc");"bp"===a(this).attr("data-id")?(a("#BP_SORT_ASC").toggleClass("d-none"),a("#BP_SORT_DESC").toggleClass("d-none"),
sortSkillBP(NOW_LIST,b)):(a("#IRYOKU_SORT_ASC").toggleClass("d-none"),a("#IRYOKU_SORT_DESC").toggleClass("d-none"),sortSkillIryoku(NOW_LIST,b))})});
function skillLabelDiplay(a){var b=$("#SKILL_TEMPLATE").clone().attr("id","").attr("data-id",a.Id).removeClass("d-none");b.find(".skillNameClass").append($("<span>").addClass("icon_sm").addClass(ICON_LIST[a.BattleType]).text("\u3000")).append(a.Name);var d=KAKUSEI_COLOR[a.KakuseiSozai]+KAKUSEI_ICON[a.Kakusei];b.find(".skillKakuseiArea").append("\u899a\u9192:"+a.Kakusei).append(' <span class="fukidashi" style="display: inline-block"><span class="icon_'+d+'" style="width:25px;height:25px; display: inline-block;background-size: contain;">\u3000</span></span>');
var e=b.find(".iconArea");a.AttackAttributes.split(",").forEach(function(a){e.append($("<span>").addClass("icon_sm").addClass(ICON_LIST[a]).text("\u3000"))});""!=a.BadStatus&&e.append($("<span>").addClass("").addClass("icon_sm").addClass(ICON_LIST[a.BadStatus]).text("\u3000"));""!=a.Buff&&("HP"===a.Buff?e.append("[HP\u56de\u5fa9]"):(d=$("<span>").addClass("icon_sm").addClass(ICON_LIST[a.Buff+"\u4e0a\u6607"]).text("\u3000"),e.append(d)));""!=a.DeBuff&&e.append($("<span>").addClass("icon_sm").addClass(ICON_LIST[a.DeBuff+
"\u4f4e\u4e0b"]).text("\u3000"));"\u8fd1"!==a.AttackDistance&&"\u6575\u5168\u4f53"!==a.AttackArea&&e.append("["+a.AttackDistance+"]");"\u6575\u5358\u4f53"!==a.AttackArea&&e.append("["+AREA_SHORT[a.AttackArea]+"]");a.AttackKansetsu&&e.append("[\u9593\u63a5]");a.Fast&&e.append("[\u30d5\u30a1\u30b9\u30c8]");a.Delay&&e.append("[\u30c7\u30a3\u30ec\u30a4]");d=0===a.SkillIryoku?IRYOKU_LIST[a.PowerGrade]:a.SkillIryoku;b.find(".iryokuArea").append("BP:"+a.ConsumeBp).append(" \u5a01\u529b:"+a.PowerGrade+"("+
d+")");d=b.find(".holderStyleArea");for(var f in a.Holders){var g=a.Holders[f],h=STYLE_MASTER[g];g=$("<div>").addClass("style").addClass(getStyleIconClass(h.Rarity)).attr("style",getImgUrl("style_icon/"+g+".png")+"; width:35px;height:35px; background-size: 35px !important;").attr("data-id",g);h=$("<span>").attr("style","width:35px;height:35px;").addClass(getStyleIconBgClass(h.Rarity)).append(g);d.append(h)}return b}var STYLE_ICON_BG_SIZE="70px !important;",STYLE_ICON_SIZE="width:70px;height:70px;";
function createStyleIcon(a,b){var d=a.Id;d=$("<div>").addClass("style").addClass(getStyleIconClass(a.Rarity)).attr("style",getImgUrl("style_icon/"+d+".png")+"; "+STYLE_ICON_SIZE+" background-size: "+STYLE_ICON_BG_SIZE).attr("data-id",d);d=$("<span>").attr("style",STYLE_ICON_SIZE).addClass(getStyleIconBgClass(a.Rarity)).append(d);d=$("<div>").addClass("col-3 col-sm-2 text-center").append(d);"-"!==b.SkillIryoku&&d.append("<p class='pad0 damage-label'>\u30c0\u30e1\u30fc\u30b8 "+a.culcDamage+"</p>").append("<div class='style-label'>"+
a.Name+"</div>");return d}
function displaySkillHolders(a){$("html,body").animate({scrollTop:$("#SKILL_NAME").offset().top});a=SKILL_MASTER[a];$("#SKILL_NAME").html('<h5 style="padding:top: 5px;">'+a.Name+"</h5>");$("#SKILL_TEXT").html(""+a.FlavorText);$("table#skill_holder_table tbody *").remove();$("#skill_holder_list").html("");var b=[];for(key in a.Holders){var d=STYLE_MASTER[a.Holders[key]],e=culcSkillDamageWithStyleBase(CHAR_MASTER[d.CharacterId],d,a);e=Object.assign(e,d);b.push(e)}b.sort(function(a,b){return a.culcDamage>
b.culcDamage?-1:1});for(key in b)d=createStyleIcon(b[key],a),$("#skill_holder_list").append(d);d=[];e=[];for(key in a.Holders){var f=CHAR_MASTER[STYLE_MASTER[a.Holders[key]].CharacterId];for(key in f.Holders){var g=STYLE_MASTER[f.Holders[key]];if(!(-1<e.indexOf(g.Id))){e.push(g.Id);var h=culcSkillDamageWithStyleBase(f,g,a);h=Object.assign(h,g);d.push(h)}}}d.sort(function(a,b){return a.culcDamage>b.culcDamage?-1:1});$("#skill_damage_ranking").html("");for(key in d)e=createStyleIcon(d[key],a),$("#skill_damage_ranking").append(e);
for(key in b){e=b[key];h=e.Id;f=getStyleBgColor(e.Rarity);d=$("<tr>").addClass(f).addClass("darkButton").attr("style","border:initial;");g=$("<td>").addClass("text-center");"-"!==a.SkillIryoku&&(g.append("<b>"+e.culcDamage.toLocaleString()+"</b>"),g.append('<button class="icon_info" data-toggle="tooltip" data-placement="top" title="\u30a2\u30d3\u30ea\u30c6\u30a3\u500d\u7387:'+e.ability+"% "+e.culcKey+":"+e.culcValue+'"></button>'));d.append(g);d.append("<td colspan=2>"+e.Name+" <small>"+e.AnotherName+
"</small></td>");f=$("<tr>").addClass(f);g=$("<td>").addClass("text-center");h=$("<div>").addClass("style").addClass(getStyleIconClass(e.Rarity)).attr("style",getImgUrl("style_icon/"+h+".png")).attr("data-id",h);h=$("<span>").addClass(getStyleIconBgClass(e.Rarity)).attr("style","width:80px").attr("style","justify-content: space-between;").append(h);g.append(h);h=$("<td>").addClass("small");h.append(e.Skill.join("<br>"));var k=[],l;for(l in e.StyleAbility)k.push(e.StyleAbility[l]);e=$("<td>").addClass("small");
e.append(k.join("<br>"));f.append(g);f.append(h);f.append(e);$("table#skill_holder_table tbody").append(d).append(f)}$('[data-toggle="tooltip"]').tooltip()}function createSkillMasterList(a){for(var b in a)a[b].FastDelay=a[b].Fast?"fast":a[b].Delay?"delay":"",a[b].KakuseiSearch=a[b].KakuseiSozai+a[b].Kakusei,void 0!==a[b].Holders&&SKILL_MASTER_LIST.push(a[b])}
function countSkill(a){var b={};for(d in optionList)b[optionList[d]]=[];var d={};for(var e in a){d.$jscomp$loop$prop$row$23=a[e];if(void 0!==d.$jscomp$loop$prop$row$23.Holders){b["skill_bp"+d.$jscomp$loop$prop$row$23.ConsumeBp].push(d.$jscomp$loop$prop$row$23);b[optionList[d.$jscomp$loop$prop$row$23.BattleType]].push(d.$jscomp$loop$prop$row$23);b[optionList[d.$jscomp$loop$prop$row$23.AttackArea]].push(d.$jscomp$loop$prop$row$23);b[optionList[d.$jscomp$loop$prop$row$23.AttackDistance]].push(d.$jscomp$loop$prop$row$23);
b[optionList[d.$jscomp$loop$prop$row$23.KakuseiSozai+d.$jscomp$loop$prop$row$23.Kakusei]].push(d.$jscomp$loop$prop$row$23);if(""!==d.$jscomp$loop$prop$row$23.CriticalTargets){var f=d.$jscomp$loop$prop$row$23.CriticalTargets.split(",");f=$jscomp.makeIterator(f);for(var g=f.next();!g.done;g=f.next())b[optionList[g.value]].push(d.$jscomp$loop$prop$row$23)}b[optionList[d.$jscomp$loop$prop$row$23.PowerGrade]].push(d.$jscomp$loop$prop$row$23);d.$jscomp$loop$prop$row$23.Fast&&b[optionList["\u30d5\u30a1\u30b9\u30c8"]].push(d.$jscomp$loop$prop$row$23);
d.$jscomp$loop$prop$row$23.Delay&&b[optionList["\u30c7\u30a3\u30ec\u30a4"]].push(d.$jscomp$loop$prop$row$23);""!=d.$jscomp$loop$prop$row$23.BadStatus&&b[optionList[d.$jscomp$loop$prop$row$23.BadStatus]].push(d.$jscomp$loop$prop$row$23);""!=d.$jscomp$loop$prop$row$23.DeBuff&&b[optionList[d.$jscomp$loop$prop$row$23.DeBuff]].push(d.$jscomp$loop$prop$row$23);b[d.$jscomp$loop$prop$row$23.AttackKansetsu?"skill_kan":"skill_cyoku"].push(d.$jscomp$loop$prop$row$23);d.$jscomp$loop$prop$row$23.AttackAttributes.split(",").forEach(function(a){return function(d){b[optionList[d]].push(a.$jscomp$loop$prop$row$23)}}(d))}d=
{$jscomp$loop$prop$row$23:d.$jscomp$loop$prop$row$23}}for(var h in optionList)a=optionList[h],$("#count_"+a).text(("  "+b[a].length).slice(-3))}
function sortSkillIryoku(a,b){b=void 0===b?!0:b;$("#skillList").html("");var d=a.slice(0,a.length);d.sort(function(a,d){return"-"===a.SkillIryoku?b?1:-1:a.SkillIryoku>d.SkillIryoku?b?-1:1:a.SkillIryoku<d.SkillIryoku?b?1:-1:a.ConsumeBp<d.ConsumeBp?b?-1:1:a.ConsumeBp>d.ConsumeBp?b?1:-1:a.AttackAttributes>d.AttackAttributes?b?-1:1:0});for(var e in d)$("#skillList").append(skillLabelDiplay(d[e]));$("#skillList").slideDown(300)}
function sortSkillBP(a,b){b=void 0===b?!0:b;$("#skillList").html("");var d=a.slice(0,a.length);d.sort(function(a,d){if(a.ConsumeBp>d.ConsumeBp)return b?-1:1;if(a.ConsumeBp<d.ConsumeBp)return b?1:-1;if("-"===d.SkillIryoku||a.SkillIryoku>d.SkillIryoku)return b?-1:1;if("-"===a.SkillIryoku||a.SkillIryoku<d.SkillIryoku)return b?1:-1;if(a.Holders.length>d.Holders.length)return b?-1:1});for(var e in d)$("#skillList").append(skillLabelDiplay(d[e]));$("#skillList").slideDown(300)}
$(function(){var a=!1,b=$("#PageTopBtn");b.css("bottom","-200px");a=!1;$(window).scroll(function(){100<$(this).scrollTop()?0==a&&(a=!0,b.stop().animate({bottom:"-10px"},200)):a&&(a=!1,b.stop().animate({bottom:"-200px"},200))});b.click(function(){$("html,body").animate({scrollTop:$("#weponLabel").offset().top});return!1})});
