var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var c="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return c?c.call(a):$jscomp.arrayIterator(a)};
$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,d){a!=Array.prototype&&a!=Object.prototype&&(a[c]=d.value)};
$jscomp.polyfill=function(a,c,d,b){if(c){d=$jscomp.global;a=a.split(".");for(b=0;b<a.length-1;b++){var f=a[b];f in d||(d[f]={});d=d[f]}a=a[a.length-1];b=d[a];c=c(b);c!=b&&null!=c&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:c})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function c(){this.batch_=null}function d(a){return a instanceof f?a:new f(function(b,d){b(a)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;c.prototype.asyncExecute=function(a){if(null==this.batch_){this.batch_=[];var b=this;this.asyncExecuteFunction(function(){b.executeBatch_()})}this.batch_.push(a)};var b=$jscomp.global.setTimeout;c.prototype.asyncExecuteFunction=function(a){b(a,0)};c.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var a=
this.batch_;this.batch_=[];for(var b=0;b<a.length;++b){var d=a[b];a[b]=null;try{d()}catch(m){this.asyncThrow_(m)}}}this.batch_=null};c.prototype.asyncThrow_=function(a){this.asyncExecuteFunction(function(){throw a;})};var f=function(a){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var b=this.createResolveAndReject_();try{a(b.resolve,b.reject)}catch(l){b.reject(l)}};f.prototype.createResolveAndReject_=function(){function a(a){return function(c){d||(d=!0,a.call(b,c))}}var b=this,d=!1;
return{resolve:a(this.resolveTo_),reject:a(this.reject_)}};f.prototype.resolveTo_=function(a){if(a===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(a instanceof f)this.settleSameAsPromise_(a);else{a:switch(typeof a){case "object":var b=null!=a;break a;case "function":b=!0;break a;default:b=!1}b?this.resolveToNonPromiseObj_(a):this.fulfill_(a)}};f.prototype.resolveToNonPromiseObj_=function(a){var b=void 0;try{b=a.then}catch(l){this.reject_(l);return}"function"==typeof b?
this.settleSameAsThenable_(b,a):this.fulfill_(a)};f.prototype.reject_=function(a){this.settle_(2,a)};f.prototype.fulfill_=function(a){this.settle_(1,a)};f.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b+"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};f.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=0;a<this.onSettledCallbacks_.length;++a)e.asyncExecute(this.onSettledCallbacks_[a]);
this.onSettledCallbacks_=null}};var e=new c;f.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};f.prototype.settleSameAsThenable_=function(a,b){var d=this.createResolveAndReject_();try{a.call(b,d.resolve,d.reject)}catch(m){d.reject(m)}};f.prototype.then=function(a,b){function d(a,b){return"function"==typeof a?function(b){try{c(a(b))}catch(p){e(p)}}:b}var c,e,g=new f(function(a,b){c=a;e=b});this.callWhenSettled_(d(a,c),d(b,e));return g};
f.prototype["catch"]=function(a){return this.then(void 0,a)};f.prototype.callWhenSettled_=function(a,b){function d(){switch(c.state_){case 1:a(c.result_);break;case 2:b(c.result_);break;default:throw Error("Unexpected state: "+c.state_);}}var c=this;null==this.onSettledCallbacks_?e.asyncExecute(d):this.onSettledCallbacks_.push(d)};f.resolve=d;f.reject=function(a){return new f(function(b,d){d(a)})};f.race=function(a){return new f(function(b,c){for(var f=$jscomp.makeIterator(a),e=f.next();!e.done;e=
f.next())d(e.value).callWhenSettled_(b,c)})};f.all=function(a){var b=$jscomp.makeIterator(a),c=b.next();return c.done?d([]):new f(function(a,f){function e(b){return function(d){g[b]=d;h--;0==h&&a(g)}}var g=[],h=0;do g.push(void 0),h++,d(c.value).callWhenSettled_(e(g.length-1),f),c=b.next();while(!c.done)})};return f},"es6","es3");
$jscomp.polyfill("Promise.prototype.finally",function(a){return a?a:function(a){return this.then(function(d){return Promise.resolve(a()).then(function(){return d})},function(d){return Promise.resolve(a()).then(function(){throw d;})})}},"es9","es3");$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,c){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:c})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(d){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(d||"")+"_"+c++,d)}var c=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.underscoreProtoCanBeSet=function(){var a={a:!0},c={};try{return c.__proto__=a,c.a}catch(d){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(a,c){a.__proto__=c;if(a.__proto__!==c)throw new TypeError(a+" is not extensible");return a}:null;$jscomp.generator={};$jscomp.generator.ensureIteratorResultIsObject_=function(a){if(!(a instanceof Object))throw new TypeError("Iterator result "+a+" is not an object");};
$jscomp.generator.Context=function(){this.isRunning_=!1;this.yieldAllIterator_=null;this.yieldResult=void 0;this.nextAddress=1;this.finallyAddress_=this.catchAddress_=0;this.finallyContexts_=this.abruptCompletion_=null};$jscomp.generator.Context.prototype.start_=function(){if(this.isRunning_)throw new TypeError("Generator is already running");this.isRunning_=!0};$jscomp.generator.Context.prototype.stop_=function(){this.isRunning_=!1};
$jscomp.generator.Context.prototype.jumpToErrorHandler_=function(){this.nextAddress=this.catchAddress_||this.finallyAddress_};$jscomp.generator.Context.prototype.next_=function(a){this.yieldResult=a};$jscomp.generator.Context.prototype.throw_=function(a){this.abruptCompletion_={exception:a,isException:!0};this.jumpToErrorHandler_()};$jscomp.generator.Context.prototype["return"]=function(a){this.abruptCompletion_={"return":a};this.nextAddress=this.finallyAddress_};
$jscomp.generator.Context.prototype.jumpThroughFinallyBlocks=function(a){this.abruptCompletion_={jumpTo:a};this.nextAddress=this.finallyAddress_};$jscomp.generator.Context.prototype.yield=function(a,c){this.nextAddress=c;return{value:a}};$jscomp.generator.Context.prototype.yieldAll=function(a,c){var d=$jscomp.makeIterator(a),b=d.next();$jscomp.generator.ensureIteratorResultIsObject_(b);if(b.done)this.yieldResult=b.value,this.nextAddress=c;else return this.yieldAllIterator_=d,this.yield(b.value,c)};
$jscomp.generator.Context.prototype.jumpTo=function(a){this.nextAddress=a};$jscomp.generator.Context.prototype.jumpToEnd=function(){this.nextAddress=0};$jscomp.generator.Context.prototype.setCatchFinallyBlocks=function(a,c){this.catchAddress_=a;void 0!=c&&(this.finallyAddress_=c)};$jscomp.generator.Context.prototype.setFinallyBlock=function(a){this.catchAddress_=0;this.finallyAddress_=a||0};$jscomp.generator.Context.prototype.leaveTryBlock=function(a,c){this.nextAddress=a;this.catchAddress_=c||0};
$jscomp.generator.Context.prototype.enterCatchBlock=function(a){this.catchAddress_=a||0;a=this.abruptCompletion_.exception;this.abruptCompletion_=null;return a};$jscomp.generator.Context.prototype.enterFinallyBlock=function(a,c,d){d?this.finallyContexts_[d]=this.abruptCompletion_:this.finallyContexts_=[this.abruptCompletion_];this.catchAddress_=a||0;this.finallyAddress_=c||0};
$jscomp.generator.Context.prototype.leaveFinallyBlock=function(a,c){var d=this.finallyContexts_.splice(c||0)[0];if(d=this.abruptCompletion_=this.abruptCompletion_||d){if(d.isException)return this.jumpToErrorHandler_();void 0!=d.jumpTo&&this.finallyAddress_<d.jumpTo?(this.nextAddress=d.jumpTo,this.abruptCompletion_=null):this.nextAddress=this.finallyAddress_}else this.nextAddress=a};$jscomp.generator.Context.prototype.forIn=function(a){return new $jscomp.generator.Context.PropertyIterator(a)};
$jscomp.generator.Context.PropertyIterator=function(a){this.object_=a;this.properties_=[];for(var c in a)this.properties_.push(c);this.properties_.reverse()};$jscomp.generator.Context.PropertyIterator.prototype.getNext=function(){for(;0<this.properties_.length;){var a=this.properties_.pop();if(a in this.object_)return a}return null};$jscomp.generator.Engine_=function(a){this.context_=new $jscomp.generator.Context;this.program_=a};
$jscomp.generator.Engine_.prototype.next_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_.next,a,this.context_.next_);this.context_.next_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.return_=function(a){this.context_.start_();var c=this.context_.yieldAllIterator_;if(c)return this.yieldAllStep_("return"in c?c["return"]:function(a){return{value:a,done:!0}},a,this.context_["return"]);this.context_["return"](a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.throw_=function(a){this.context_.start_();if(this.context_.yieldAllIterator_)return this.yieldAllStep_(this.context_.yieldAllIterator_["throw"],a,this.context_.next_);this.context_.throw_(a);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.yieldAllStep_=function(a,c,d){try{var b=a.call(this.context_.yieldAllIterator_,c);$jscomp.generator.ensureIteratorResultIsObject_(b);if(!b.done)return this.context_.stop_(),b;var f=b.value}catch(e){return this.context_.yieldAllIterator_=null,this.context_.throw_(e),this.nextStep_()}this.context_.yieldAllIterator_=null;d.call(this.context_,f);return this.nextStep_()};
$jscomp.generator.Engine_.prototype.nextStep_=function(){for(;this.context_.nextAddress;)try{var a=this.program_(this.context_);if(a)return this.context_.stop_(),{value:a.value,done:!1}}catch(c){this.context_.yieldResult=void 0,this.context_.throw_(c)}this.context_.stop_();if(this.context_.abruptCompletion_){a=this.context_.abruptCompletion_;this.context_.abruptCompletion_=null;if(a.isException)throw a.exception;return{value:a["return"],done:!0}}return{value:void 0,done:!0}};
$jscomp.generator.Generator_=function(a){this.next=function(c){return a.next_(c)};this["throw"]=function(c){return a.throw_(c)};this["return"]=function(c){return a.return_(c)};$jscomp.initSymbolIterator();this[Symbol.iterator]=function(){return this}};$jscomp.generator.createGenerator=function(a,c){var d=new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(c));$jscomp.setPrototypeOf&&$jscomp.setPrototypeOf(d,a.prototype);return d};
$jscomp.asyncExecutePromiseGenerator=function(a){function c(b){return a.next(b)}function d(b){return a["throw"](b)}return new Promise(function(b,f){function e(a){a.done?b(a.value):Promise.resolve(a.value).then(c,d).then(e,f)}e(a.next())})};$jscomp.asyncExecutePromiseGeneratorFunction=function(a){return $jscomp.asyncExecutePromiseGenerator(a())};$jscomp.asyncExecutePromiseGeneratorProgram=function(a){return $jscomp.asyncExecutePromiseGenerator(new $jscomp.generator.Generator_(new $jscomp.generator.Engine_(a)))};
var BASE_SKILL_LIST=[],USE_SKILL_LIST=[],NOW_CHAR={},NOW_STYLE={},STYLE_LIMIT=Object.assign({},STYLE_SIMPLE);STYLE_MASTER={};var SKILL_MASTER,ABILITY_MASTER;
if(""!==location.search){var styleId=location.search.substr(3);if(void 0!==STYLE_SIMPLE[styleId]){document.title="\u3010\u30ed\u30de\u30b5\u30acRS\u3011"+STYLE_SIMPLE[styleId].Name+"["+STYLE_SIMPLE[styleId].Rarity+"]\u306e\u7d20\u30b9\u30c6\u3002\u30b9\u30c6\u30fc\u30bf\u30b9\u6700\u5927\u5024\u3001\u6280\u30fb\u30a2\u30d3\u30ea\u30c6\u30a3\u30fb\u8010\u6027\u4e00\u89a7";var desc=STYLE_SIMPLE[styleId].Name+" "+STYLE_SIMPLE[styleId].Rarity+" "+STYLE_SIMPLE[styleId].AnotherName+" \u306e\u6700\u65b0\u30af\u30a8\u30b9\u30c8\u3067\u306e\u7d20\u30b9\u30c6\u4e0a\u9650\u3001\u30b9\u30bf\u30a4\u30eb\u88dc\u6b63\u8fbc\u307f\u6700\u5927\u30b9\u30c6\u30fc\u30bf\u30b9\u5024\u3001\u5225\u30b9\u30bf\u30a4\u30eb\u3068\u306e\u6bd4\u8f03\u3092\u63b2\u8f09\u3057\u3066\u3044\u307e\u3059";
$("meta[name='description']").attr("content",desc)}}function _noLoginInitial(){console.log("_noLoginInitial");var a={signInSuccessUrl:"https://nao-romasaga.github.io/style.html",signInOptions:[firebase.auth.TwitterAuthProvider.PROVIDER_ID]};(new firebaseui.auth.AuthUI(firebase.auth(appUsers))).start("#firebaseui-auth-container",a);$(".noLogin").hide()}
function _initial(){console.log("initial");$("#loginInfo").hide();var a=$("<img>").attr("src",USER.photoURL).attr("style","width:40px; heidht:40px;    border-radius: 50%;"),c=USER.displayName+" \u3055\u3093:\u30ed\u30b0\u30a4\u30f3\u4e2d";$("#firebaseui-auth-container").addClass("bg-white kadomaru").append(a).append(c);var d=$("#PageTopBtn");d.css("bottom","-200px");var b=!1;$(window).scroll(function(){800<$(this).scrollTop()?0==b&&(b=!0,d.stop().animate({bottom:"-10px",right:"10px"},200)):b&&(b=
!1,d.stop().animate({bottom:"-200px"},200))});d.click(function(){$("html,body").animate({scrollTop:$("#FILTER").offset().top});return!1})}read();
function read(){var a,c,d,b,f;return $jscomp.asyncExecutePromiseGeneratorProgram(function(e){if(1==e.nextAddress)return a=readFile("Skill",function(a){SKILL_MASTER=a}),c=readFile("Style",function(a){STYLE_MASTER=a}),d=readFile("Ability",function(a){ABILITY_MASTER=a}),e.yield(Promise.all([a,d,c]),2);dispChar(CHAR_MASTER);createRanking();""!==location.search&&(b=location.search.substr(3),void 0!==STYLE_MASTER[b]&&(f=STYLE_MASTER[b].CharacterId,clickChar(f,b)));e.jumpToEnd()})}
$(document).ready(function(a){var c=Math.floor(5*Math.random());a(".dotBackground").addClass("bg"+(c+1));a("#PLUS_LIMIT").text(LIMIT_BASE);initialHide();setSlider();setSliderChart();a(".filterList").click(function(){a(".weaponList").addClass("d-none");var d=a(this).attr("href").substr(1);a(this).parent().hasClass("filterActive")?(a(".sp-slides-container").removeClass("d-none"),a(".filterList").each(function(){a(this).parent().removeClass("filterActive")})):(a(".sp-slides-container").addClass("d-none"),
a("#_"+d).removeClass("d-none"),a(".filterList").each(function(){a(this).parent().removeClass("filterActive")}),a(this).parent().toggleClass("filterActive"))});a(document).on("click",".char",function(){var d=this,b;return $jscomp.asyncExecutePromiseGeneratorProgram(function(c){b=a(d).attr("data-id");clickChar(b);gtag("event","clickChar",{event_category:"style",event_label:NOW_CHAR.Name,value:1});c.jumpToEnd()})});a(document).on("click",".style",function(){var d=a(this).attr("data-id");NOW_STYLE=STYLE_MASTER[d];
displayStyleInfo(d);gtag("event","clickStyle",{event_category:"auto",event_label:NOW_STYLE.Name+NOW_STYLE.AnotherName,value:1})});a(document).on("click","#MAX_STATUS",function(){a(".DISP_ST").html("\u7d20\u30b9\u30c6\u30fc\u30bf\u30b9\u6700\u5927");a(".ISMAX").html("\u6700\u5927");a(".charParam").slideUp(200,function(){for(var d=$jscomp.makeIterator(PARAM_KEY),b=d.next();!b.done;b=d.next())b=b.value,a(".char"+b).val(NOW_CHAR["MAX"+b]+LIMIT_BASE),a(".INPUT"+b).val(NOW_CHAR["MAX"+b]+LIMIT_BASE);a(".charParam").slideDown(200);
reCulcStyleParam()})});a(document).on("click","#MY_STATUS",function(){a(".DISP_ST").html("\u81ea\u5206\u306e\u30b9\u30c6\u30fc\u30bf\u30b9");a(".ISMAX").html("");readUserDataWithId("CHAR",NOW_CHAR.Id,function(d){a(".myst").slideUp(200,function(){for(var b=$jscomp.makeIterator(PARAM_KEY),c=b.next();!c.done;c=b.next())c=c.value,a(".char"+c).val(null===d?NOW_CHAR[c]:d[c]),a(".INPUT"+c).val(null===d?NOW_CHAR[c]:d[c]);a(".myst").slideDown(200);reCulcStyleParam()})})});a(document).on("change",".charParam1",
function(){a(".DISP_ST").html("\u81ea\u5206\u306e\u30b9\u30c6\u30fc\u30bf\u30b9");a(".ISMAX").html("");a(".charParam1").each(function(){key=a(this).attr("data-param");val=a(this).val();a(".char"+key).val(val);a(".INPUT"+key).val(val)});reCulcStyleParam()});a(document).on("change",".charParam2",function(){a(".DISP_ST").html("\u81ea\u5206\u306e\u30b9\u30c6\u30fc\u30bf\u30b9");a(".ISMAX").html("");a(".charParam2").each(function(){key=a(this).attr("data-param");val=a(this).val();a(".char"+key).val(val);
a(".INPUT"+key).val(val)});reCulcStyleParam()});a(document).on("change",".MY_STYLE_LV",function(){lv=a(this).val();lv=1>lv?1:50<lv?50:lv;NOW_LV=Number(lv);a(".DISP_LV").html(lv);reCulcStyleParam()})});
function reCulcStyleParam(){$(".STYLE_VAL_ROW").each(function(){var a=$(this).attr("data-id");if(void 0===a)return!0;var c=$(this),d=null;$(".STYLE_PER_ROW").each(function(){var b=$(this).attr("data-id");if(a===b)return d=$(this),!1});if(null===d)console.log("\u4f55\u304b\u304a\u304b\u3057\u3044");else for(var b=getStyleStatusWithLV(STYLE_MASTER[a],NOW_LV),f=$jscomp.makeIterator(PARAM_KEY),e=f.next();!e.done;e=f.next()){e=e.value;var g=b[e].val,h=b[e].per;c.find("."+e).html(isNaN(g)?"<small>\u8abf\u67fb\u4e2d</small>":
g);d.find("."+e).find(".per").html('<span class="d-sm-inline d-none">'+h+'</span><span class="d-sm-none">'+Math.round(h)+"</span>");d.find("."+e).find(".bonus").html("+"+b[e].bonus)}})}function initialHide(){$("#STYLE_DATA").hide();$(".styleInfoArea").hide();$(".styleChoiceArea").hide()}
function displayStyleInfo(a){$("#styleGachaMessage").addClass("d-none");$("#styleDot").show();$(".style").each(function(){var b=$(this).attr("data-id");$(this).parent().addClass("opacity_nocheck");a===b&&$(this).parent().removeClass("opacity_nocheck")});for(var c=STYLE_MASTER[a],d=$jscomp.makeIterator("Zan Da Totsu Netsu Rei Rai Inn You".split(" ")),b=d.next();!b.done;b=d.next()){b=b.value;setTaisei($(".taisei_"+b),c["Resist"+b]);setTaisei($(".bairitsu_"+b),c["Resist"+b]);var f=1/(1+.008*Number(c["Resist"+
b]));f=Math.round(100*f)/100;$(".bairitsu_"+b).html(f+"\u500d")}d=$("<p>").attr("style","font-size:10px; margin-bottom:0px;").append(c.AnotherName);b=$("<p>").attr("style","font-size:18px; margin-bottom:0px;").append(c.Name);f=$("<div>").addClass("icon_rare_large float-left").attr("style",getImgUrl("icon/icon_"+c.Rarity+".png"));f.html('<span id="styleDot" class="char dot_mid dot char-aruku"></span>');$("#styleNameLabel").html("").append(f).append(d).append(b);$("#styleBgImg").attr("style",getImgUrl("style_all/"+
c.IllustId+".png")+" background-size: cover;");$("#styleBgImg").attr("style-img","background: url(./img/bg_gacha.png) no-repeat; background-size: cover;");$("#styleGachaMessage").html(c.GachaText);$("#styleBgImg").off("click");""!==c.GachaText&&$("#styleBgImg").click(function(){var a=$("#styleBgImg").attr("style"),b=$("#styleBgImg").attr("style-img");$("#styleBgImg").attr("style",b+" transition: opacity 50ms 200ms,transform 300ms;");$("#styleBgImg").attr("style-img",a);$("#styleGachaMessage").toggleClass("d-none")});
d=c.DotId;d="ID4e2c8"!==d?d:"ID4e2c9";$("#styleDot").attr("style",getImgUrl("dot/"+d+".png")+" margin-left:40px; margin-top: -5px;");d=getStyleStatusWithLV(c,NOW_LV);for(var e in PARAM_KEY){b=PARAM_KEY[e];f='<span class="hidden pcBlock">'+PARAM_NAME[e]+'</span><span class="hidden spBlock">'+PARAM_NAME_ONE[e]+"</span> ";var g=d[b].val,h='<img src="./img/icon/icon_ind_'+c["Ind"+b]+'.png" width=10>',l=d[b].per+"%";0<d[b].bonus&&(l+="+"+d[b].bonus);$("#label"+b).html(f);$("#style"+b).html(g);$("#styleBonus"+
b).html(h+l)}$("#abilityList1").html("");$("#abilityList2").html("");e=[];for(var m in c.StyleAbilityIds)b=ABILITY_MASTER[c.StyleAbilityIds[m]],d=$("<span>").append(b.Name),createInfoButton().attr("style","margin-left:10px").attr("title",b.FlavorText),b=$("<span>").addClass("small").html(b.FlavorText),d.append(":<br class='hidden pcBlock'>").append(b),e.push(d.html());$("#abilityList1").append(e.join("<br>"));$("#abilityList2").append(e.join("<br>"));$("#skillList1").html("");$("#skillList2").html("");
for(var k in c.SkillIds)m=SKILL_MASTER[c.SkillIds[k]],e=createSkillModule(m),2!=k&&e.addClass(" char-bottom"),$("#skillList1").append(e.clone()),$("#skillList2").append(e.clone()),$(".flv"+m.Id).slideUp();displaySkillTable(NOW_CHAR,50,c);$('[data-toggle="tooltip"]').tooltip()}
function createSkillModule(a){var c=$("<div>").addClass("row no-gutters "),d=$("<div>").addClass("col-8");d.append($("<span>").addClass("icon_sm").addClass(ICON_LIST[a.BattleType]).append("\u3000"));d.append(a.Name);a.AttackAttributes.split(",").forEach(function(a){a=$("<span>").addClass("icon_sm").addClass(ICON_LIST[a]).append("\u3000");d.append(a)});d.append("<br>");if(""!==a.BadStatus){var b=$("<span>").addClass("").addClass("icon_sm").addClass(ICON_LIST[a.BadStatus]).append("\u3000");d.append(b);
d.append(":<span class='small'>"+a.BadStatusPer+"</span>")}""!=a.Buff&&("HP"===a.Buff?d.append("[HP\u56de\u5fa9]"):(b=$("<span>").addClass("icon_sm").addClass(ICON_LIST[a.Buff+"\u4e0a\u6607"]).text("\u3000"),d.append(b)));""!==a.DeBuff&&(b=$("<span>").addClass("icon_sm_buf").addClass(ICON_LIST[a.DeBuff+"\u4f4e\u4e0b"]).append("\u3000"),d.append(b),d.append(":<span class='small'>"+a.DeBuffPer+"</span>"));"\u8fd1"!==a.AttackDistance&&-1===["\u6575\u5168\u4f53","\u5473\u65b9\u5358\u4f53","\u81ea\u8eab"].indexOf(a.AttackArea)&&
d.append("["+a.AttackDistance+"]");a.AttackKansetsu&&d.append("[\u9593\u63a5]");"\u6575\u5358\u4f53"!==a.AttackArea&&d.append("["+AREA_SHORT[a.AttackArea]+"]");a.Fast&&d.append("[\u30d5\u30a1\u30b9\u30c8]");a.Delay&&d.append("[\u30c7\u30a3\u30ec\u30a4]");c.append(d);b="BP:"+a.ConsumeBp;0<a.ConsumeLp&&(b+="/LP:"+a.ConsumeLp);b+=' <span class="fukidashi" style="display: inline-block"><span class="icon_'+(KAKUSEI_COLOR[a.KakuseiSozai]+KAKUSEI_ICON[a.Kakusei])+'" style="width:25px;height:25px; display: inline-block;background-size: contain;">\u3000</span></span><br>';
b=0===a.SkillIryoku?b+("<span class='small'>\u5a01\u529b:"+a.PowerGrade+"("+IRYOKU_LIST[a.PowerGrade]+")</span>"):b+("\u5a01\u529b:"+a.PowerGrade+"("+a.SkillIryoku+")");b=$("<div>").addClass("col-4 text-nowrap").append(b);c.append(b);b=$("<div>").addClass("col-12 border-top small flv"+a.Id).append(a.FlavorText);c.append(b);c.attr("onclick",'$(".flv'+a.Id+'").slideToggle();');return c}
function getStyleStatusWithLV(a,c){var d=culcStyleAddintional(a),b={},f;for(f in PARAM_KEY){var e=$(".INPUT"+PARAM_KEY[f]).val(),g=d[PARAM_NAME[f]][c].Per,h=d[PARAM_NAME[f]][c].Bonus;e=addBonus(e,g,h);b[PARAM_KEY[f]]={val:e,per:g,bonus:h}}return b}var STATUS_TABLE="<table class='table table-sm width-100 small'>";STATUS_TABLE+="<tr class='char-bottom text-nowrap'><td>\u8155\u529b</td><td id='tdStr' class='text-right'></td><td>\u4f53\u529b</td><td id='tdVit' class='text-right'></td></tr>";
STATUS_TABLE+="<tr class='char-bottom text-nowrap'><td>\u5668\u7528\u3055</td><td id='tdDex' class='text-right'></td><td>\u7d20\u65e9\u3055</td><td id='tdAgi' class='text-right'></td></tr>";STATUS_TABLE+="<tr class='char-bottom text-nowrap'><td>\u77e5\u529b</td><td id='tdInt' class='text-right'></td><td>\u7cbe\u795e</td><td id='tdMnd' class='text-right'></td></tr>";STATUS_TABLE+="<tr class='char-bottom text-nowrap'><td>\u611b</td><td id='tdAi' class='text-right'></td><td>\u9b45\u529b</td><td id='tdMi' class='text-right'></td></tr>";
STATUS_TABLE+="</table>";var NOW_LV=50;
function displayStyleList(){var a,c,d,b,f,e,g,h,l,m,k,n,q,v,r,p,w,t,x,y,z,u;return $jscomp.asyncExecutePromiseGeneratorProgram(function(A){$(".styleChoiceArea").show();$("#styleChoice").html("");$(".STYLE_ROW").remove();a=NOW_CHAR;c=!0;a.Holders.sort(function(a,b){return a>b?1:-1});d=$jscomp.makeIterator(a.Holders);for(b=d.next();!b.done;b=d.next()){f=b.value;e=STYLE_MASTER[f];g=$("<button>").addClass("style").addClass(getStyleIconClass(e.Rarity)).attr("style",getImgUrl("style_icon/"+f+".png")).attr("data-id",
f);h=$("<span>").addClass(getStyleIconBgClass(e.Rarity)).append(g);$("#styleChoice").append(h);l=getStyleStatusWithLV(e,50);m=c?"opacity":"";c=!c;k=$("#STYLE_TABLE_TEMPLATE").clone().attr("id","").removeClass("d-none").addClass("STYLE_ROW STYLE_VAL_ROW "+m).attr("data-id",f);n=$("#STYLE_TABLE_PER_TEMPLATE").clone().attr("id","").removeClass("d-none").addClass("STYLE_ROW STYLE_PER_ROW small "+m).attr("data-id",f);q=$("#STYLE_TABLE_TEMPLATE").clone().attr("id","").removeClass("d-none").addClass("STYLE_ROW "+
m);v=$jscomp.makeIterator(PARAM_KEY);for(r=v.next();!r.done;r=v.next())p=r.value,w=l[p].val,t=STYLE_LIMIT[f]["Limit"+p],x="<small class='d-none d-lg-inline'>\u8abf\u67fb\u4e2d</small><small class='d-lg-none'>?</small>",99!==t&&(t==NOW_CHAR["MAX"+p]&&q.find("."+p).attr("style","background-color: lightgreen;"),x=t+LIMIT_BASE),k.find("."+p).html(isNaN(w)?"<small>\u8abf\u67fb\u4e2d</small>":w),n.find("."+p).find(".per").html(l[p].per),n.find("."+p).find(".bonus").html("+"+l[p].bonus),y=x+('<br><img src="./img/icon/icon_ind_'+
e["Ind"+p]+'.png" width=17>'),q.find("."+p).html(y),$(".char"+p).val(NOW_CHAR["MAX"+p]+LIMIT_BASE);$rareImg='<img src="./img/icon/icon_'+e.Rarity+'.png" width=24 style="position: absolute;">';z=$("<button>").addClass("style").addClass(getStyleIconClass(e.Rarity)+"_middle").attr("style",getImgUrl("style_icon/"+f+".png")).attr("data-id",f);u=$("<span>").addClass(getStyleIconBgClass(e.Rarity)+"_middle").append(z.clone());k.find(".IMG").append($rareImg).append(u.clone());n.find(".IMG").append($rareImg).append(u.clone());
q.find(".IMG").append($rareImg).append(u.clone());$("#STYLE_PER_ROW").after(n);$("#STYLE_VAL_ROW").after(k);$("#STYLE_ST_ROW").after(q)}$(".culcDamageResultClass").slideUp();return A["return"]($("#STYLE_PER_ROW"))})}
function displaySkillTable(a,c,d){$("#styleSkill1").html("");$("#styleSkill2").html("");c=d.Id;d=[c];a=$jscomp.makeIterator(a.Holders);for(var b=a.next();!b.done;b=a.next())b=b.value,c!==b&&d.push(b);d=$jscomp.makeIterator(d);for(b=d.next();!b.done;b=d.next()){a=b.value;b=$jscomp.makeIterator(STYLE_MASTER[a].SkillIds);for(var f=b.next();!f.done;f=b.next()){f=SKILL_MASTER[f.value];var e=createSkillModule(f),g=$('<div style="width:100%;height:100%;position: absolute;background: url(./img/style_cutin/'+
a+'.png) no-repeat; background-size: contain;opacity: 0.5;"></div>');e.prepend(g);e=$('<div class="col-12 col-md-4 style-skill-list" style="padding: 0px 5px;">').append(e);c!==a?$("#styleSkill2").append(e):$("#styleSkill1").append(e);$(".flv"+f.Id).slideUp()}}$('[data-toggle="tooltip"]').tooltip()}
function getSmallIcon(a){var c=$("<button>").addClass(getStyleIconClass(a.Rarity)+"_small").attr("style",getImgUrl("style_icon/"+a.Id+".png"));return $("<span>").addClass(getStyleIconBgClass(a.Rarity)).attr("style","height: 30px;").append(c)}var margin={top:30,right:50,bottom:30,left:50},width=200,height=200;function setSliderChart(){$("#slider-pro-chart").sliderPro({buttons:!0,startSlide:0,arrows:!0,width:"100%",height:300,autoplay:!1,loop:!0,visibleSize:"100%"})}
function createStyleValueChartData(a,c){var d=[30,50].filter(function(a,b,c){return c.indexOf(a)===b});d.sort(function(a,b){return a<b?-1:1});var b=[],f=culcStyleAddintional(a);d=$jscomp.makeIterator(d);for(var e=d.next();!e.done;e=d.next()){e=e.value;var g={name:e,axes:[]},h;for(h in PARAM_NAME){var l=PARAM_NAME[h],m=$("#char"+PARAM_KEY[h]).val();m=addBonus(m,f[l][e].Per,f[l][e].Bonus);g.axes.push({axis:l,value:m})}b.push(g)}return b}
var CHAR_ST_RANK={STR:{},VIT:{},DEX:{},AGI:{},INT:{},MND:{},AI:{},MI:{}},TYPE_RANK={"\u5168":{STR:{},VIT:{},DEX:{},AGI:{},INT:{},MND:{},AI:{},MI:{}},"\u5263":{STR:{},VIT:{},DEX:{},AGI:{},INT:{},MND:{},AI:{},MI:{}},"\u5927\u5263":{STR:{},VIT:{},DEX:{},AGI:{},INT:{},MND:{},AI:{},MI:{}},"\u65a7":{STR:{},VIT:{},DEX:{},AGI:{},INT:{},MND:{},AI:{},MI:{}},"\u5c0f\u5263":{STR:{},VIT:{},DEX:{},AGI:{},INT:{},MND:{},AI:{},MI:{}},"\u69cd":{STR:{},VIT:{},DEX:{},AGI:{},INT:{},MND:{},AI:{},MI:{}},"\u5f13":{STR:{},
VIT:{},DEX:{},AGI:{},INT:{},MND:{},AI:{},MI:{}},"\u68cd\u68d2":{STR:{},VIT:{},DEX:{},AGI:{},INT:{},MND:{},AI:{},MI:{}},"\u4f53\u8853":{STR:{},VIT:{},DEX:{},AGI:{},INT:{},MND:{},AI:{},MI:{}},"\u9283":{STR:{},VIT:{},DEX:{},AGI:{},INT:{},MND:{},AI:{},MI:{}},"\u6756":{STR:{},VIT:{},DEX:{},AGI:{},INT:{},MND:{},AI:{},MI:{}},"\u65ac":{STR:{},VIT:{},DEX:{},AGI:{},INT:{},MND:{},AI:{},MI:{}},"\u7a81":{STR:{},VIT:{},DEX:{},AGI:{},INT:{},MND:{},AI:{},MI:{}},"\u6253":{STR:{},VIT:{},DEX:{},AGI:{},INT:{},MND:{},
AI:{},MI:{}}},TYPE_MAP={"\u5263":"\u65ac","\u5927\u5263":"\u65ac","\u65a7":"\u65ac","\u5c0f\u5263":"\u7a81","\u69cd":"\u7a81","\u5f13":"\u7a81","\u68cd\u68d2":"\u6253","\u4f53\u8853":"\u6253","\u9283":"\u6253","\u6756":"\u6756"},CHAR_ST_RANK_TYPE={};function addRankParam(a){return void 0===a?1:Number(a)+1}
function calcRankMap(a){var c={},d=["SUM"].concat(PARAM_KEY);d=$jscomp.makeIterator(d);for(var b=d.next();!b.done;b=d.next()){b=b.value;c[b]={};var f=[],e;for(e in a[b])f.push(Number(e));f.sort(function(a,b){return a>b?-1:1});var g=1;f=$jscomp.makeIterator(f);for(var h=f.next();!h.done;h=f.next())h=h.value,c[b][h]=g,g+=Number(a[b][h]);c.ALL=g}return c}
function createRanking(){TYPE_RANK["\u5168"].SUM={};for(var a in CHAR_MASTER){var c=CHAR_MASTER[a].WeaponType,d=TYPE_MAP[c],b=0;void 0===TYPE_RANK[c].SUM&&(TYPE_RANK[c].SUM={});void 0===TYPE_RANK[d].SUM&&(TYPE_RANK[d].SUM={});for(var f=$jscomp.makeIterator(PARAM_KEY),e=f.next();!e.done;e=f.next()){e=e.value;var g=CHAR_MASTER[a]["MAX"+e];"-99"!=g&&(b+=Number(g)+LIMIT_BASE);void 0===TYPE_RANK["\u5168"][e][g]?TYPE_RANK["\u5168"][e][g]=1:TYPE_RANK["\u5168"][e][g]++;void 0===TYPE_RANK[c][e][g]?TYPE_RANK[c][e][g]=
1:TYPE_RANK[c][e][g]++;void 0===TYPE_RANK[d][e][g]?TYPE_RANK[d][e][g]=1:TYPE_RANK[d][e][g]++}void 0===TYPE_RANK["\u5168"].SUM[b]?TYPE_RANK["\u5168"].SUM[b]=1:TYPE_RANK["\u5168"].SUM[b]++;void 0===TYPE_RANK[c].SUM[b]?TYPE_RANK[c].SUM[b]=1:TYPE_RANK[c].SUM[b]++;void 0===TYPE_RANK[d].SUM[b]?TYPE_RANK[d].SUM[b]=1:TYPE_RANK[d].SUM[b]++}for(var h in TYPE_RANK)TYPE_RANK[h]=calcRankMap(TYPE_RANK[h])}
function clickChar(a,c){c=void 0===c?null:c;var d=CHAR_MASTER[a].DotId;NOW_CHAR=CHAR_MASTER[a];if(null===c||void 0===STYLE_MASTER[c])c=NOW_CHAR.Holders[0];NOW_STYLE=STYLE_MASTER[c];$("#displayDamage").removeClass("icon_btn_off");$("#displayDamage").addClass("icon_btn_on");$("#displayDamage").find("#msg").addClass("d-none");$(".culcDamageResultClass").slideDown();$("#STYLE_DATA").show();$(".styleInfoArea").show();$(".tabArea").show();$(".styleChoiceArea").show();$("html,body").animate({scrollTop:$("#CHAR_DATA").offset().top},
500,"swing");var b=CHAR_MASTER[a].WeaponType,f=TYPE_MAP[b];$(".TR_RANK").remove();for(var e=$("#RANK_TEMPLATE").clone().attr("id","ALL").removeClass("d-none").addClass("TR_RANK"),g=$("#RANK_TEMPLATE").clone().attr("id","ALL").removeClass("d-none").addClass("TR_RANK opacity"),h=$("#RANK_TEMPLATE").clone().attr("id","ALL").removeClass("d-none").addClass("TR_RANK"),l=0,m=$jscomp.makeIterator(PARAM_KEY),k=m.next();!k.done;k=m.next()){k=k.value;var n=NOW_CHAR["MAX"+k];NOW_CHAR[k]=Number(n)+LIMIT_BASE;
l+="-99"!=n?Number(n)+LIMIT_BASE:0;var q="-99"!=n?Number(n)+LIMIT_BASE:"?";$(".MAX"+k).html(q);$(".INPUT"+k).val(q);e.find("."+k).html("<span class='d-none d-md-inline'>"+TYPE_RANK["\u5168"][k][n]+"</span><p class=\"d-block d-md-none\" style='margin-bottom:0px;'>"+TYPE_RANK["\u5168"][k][n]+"</p><span class='small'>\u4f4d</span>");g.find("."+k).html("<span class='d-none d-md-inline'>"+TYPE_RANK[b][k][n]+"</span><p class=\"d-block d-md-none\" style='margin-bottom:0px;'>"+TYPE_RANK[b][k][n]+"</p><span class='small'>\u4f4d</span>");
h.find("."+k).html("<span class='d-none d-md-inline'>"+TYPE_RANK[f][k][n]+"</span><p class=\"d-block d-md-none\" style='margin-bottom:0px;'>"+TYPE_RANK[f][k][n]+"</p><span class='small'>\u4f4d</span>")}e.find(".SUM").text(TYPE_RANK["\u5168"].SUM[l]+"\u4f4d");g.find(".SUM").text(TYPE_RANK[b].SUM[l]+"\u4f4d");h.find(".SUM").text(TYPE_RANK[f].SUM[l]+"\u4f4d");$(".MAXSUM").text(l);e.find(".IMG").html("\u5168\u30ad\u30e3\u30e9<br>"+TYPE_RANK["\u5168"].ALL+"\u30ad\u30e3\u30e9\u4e2d");g.find(".IMG").html('<img src="./img/icon/'+
ICON_LIST[b]+'.png" width=30><br>'+TYPE_RANK[b].ALL+"\u30ad\u30e3\u30e9\u4e2d");h.find(".IMG").html('<img src="./img/icon/'+ICON_LIST[f]+'.png" width=30><br>'+TYPE_RANK[f].ALL+"\u30ad\u30e3\u30e9\u4e2d");"\u6756"!==b?$("#styleLabelRow").after(h).after(g).after(e):$("#styleLabelRow").after(g).after(e);$(".char-selected").each(function(){$(this).removeClass("char-winner");$(this).addClass("char-aruku")});$(".dot"+d).removeClass("char-aruku");$(".dot"+d).addClass("char-winner").addClass("char-selected").addClass("dot");
$(".CHAR_NAME").html(NOW_CHAR.Name);$("#RANK_LINK").attr("href","./ourchar.html?c="+NOW_CHAR.Id);d="ID4e2c8"!==d?d:"ID4e2c9";$("#charDot").attr("style",getImgUrl("dot/"+d+".png"));displayStyleList();displayStyleInfo(c)};
