var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};var allCount={SS:0,S:0,A:0},key;for(key in WEPON_ATTR)allCount[key]=0;
var myCount={SS:0,S:0,A:0},sslist=[],slist=[],alist=[],weponType=Object.assign({},WEPON_ATTR),key$8;for(key$8 in weponType)weponType[key$8]=[];var gachaList="2019.07.31.\u6c34\u7740\u30ac\u30c1\u30e3 2019.07.31.\u6c34\u7740\u914d\u5e03 \u6c4e\u7528 \u30d7\u30e9\u30c1\u30ca\u30ac\u30c1\u30e3\u9650\u5b9a \u30b9\u30c8\u30fc\u30ea\u30fc \u4e03\u82f1\u96c4\u8972\u6765 \u5e38\u8a2d\u30a4\u30d9\u30f3\u30c8 \u87ba\u65cb\u56de\u5eca\u30ac\u30c1\u30e3\u9650\u5b9a \u30ad\u30e3\u30f3\u30da\u30fc\u30f3\u914d\u5e03 \u521d\u671f\u914d\u5e03 2019.06.30.\u5357\u56fd\u306e\u697d\u5712\u30ac\u30c1\u30e3 2019.06.30.\u5357\u56fd\u306e\u697d\u5712\u914d\u5e03 2019.05.29.\u30cf\u30fc\u30d5\u30a2\u30cb\u30d0\u30fc\u30b5\u30ea\u30fc\u30a4\u30d9\u30f3\u30c8(\u30a8\u30df\u30ea\u30a2\u7de8) 2019.05.29.\u30cf\u30fc\u30d5\u30a2\u30cb\u30d0\u30fc\u30b5\u30ea\u30fc\u30a4\u30d9\u30f3\u30c8\u914d\u5e03 2019.06.21.\u30cf\u30fc\u30d5\u30a2\u30cb\u30d0\u30fc\u30b5\u30ea\u30fc\u30a4\u30d9\u30f3\u30c8(\u3088\u3046\u305b\u3044\u7de8) 2019.06.21.\u30cf\u30fc\u30d5\u30a2\u30cb\u30d0\u30fc\u30b5\u30ea\u30fc\u30a4\u30d9\u30f3\u30c8\u914d\u5e03 2019.06.09.\u30cf\u30fc\u30d5\u30a2\u30cb\u30d0\u30fc\u30b5\u30ea\u30fc\u30a4\u30d9\u30f3\u30c8(\u30a2\u30bb\u30eb\u30b9\u7de8) 201905.GW\u30a4\u30d9\u30f3\u30c8 201902.\u30d0\u30ec\u30f3\u30bf\u30a4\u30f3\u30c7\u30fc\u30a4\u30d9\u30f3\u30c8 201901.\u6b63\u6708\u30a4\u30d9\u30f3\u30c8 201812.\u30af\u30ea\u30b9\u30de\u30b9\u30a4\u30d9\u30f3\u30c82 201903.\u30db\u30ef\u30a4\u30c8\u30c7\u30fc\u30a4\u30d9\u30f3\u30c8 201904.\u4faf\u56fd\u5b66\u5712\u30a4\u30d9\u30f3\u30c8 201812.\u30af\u30ea\u30b9\u30de\u30b9\u30a4\u30d9\u30f3\u30c81".split(" ");
function _noLoginInitial(){var a={signInSuccessUrl:"https://nao-romasaga.github.io/stylecheck.html",signInOptions:[firebase.auth.TwitterAuthProvider.PROVIDER_ID]};(new firebaseui.auth.AuthUI(firebase.auth(appUsers))).start("#firebaseui-auth-container",a)}
function _initial(){$("#loginInfo").hide();var a=$("<img>").attr("src",USER.photoURL).attr("style","width:40px; heidht:40px;    border-radius: 50%;"),b=USER.displayName+" \u3055\u3093:\u30ed\u30b0\u30a4\u30f3\u4e2d";$("#firebaseui-auth-container").addClass("bg-white kadomaru").append(a).append(b);display()}var targetId;$(document).ready(function(a){""!==location.search&&(targetId=location.search.substr(1),a(".allOn , .allOff , .twitter-share-button").hide(),a(".myinput").removeClass("d-none"))});
$(document).on("click",".onlyDisable",function(){gtag("event","filter",{event_category:"stylecheck",event_label:"OnlyDisable",value:1});$(".style").each(function(){$(this).parent().hasClass("nocheck")||$(this).parent().addClass("d-none")})});$(document).on("click",".allType",function(){gtag("event","filter",{event_category:"stylecheck",event_label:"ALL",value:1});$(".style").each(function(){$(this).parent().removeClass("d-none")})});
$(document).on("click",".filterButton",function(){var a=$(this).attr("data-id");gtag("event","filter",{event_category:"stylecheck",event_label:a,value:1});$(".style").each(function(){$(this).parent().addClass("d-none");$(this).attr("data-type")===a&&$(this).parent().removeClass("d-none")})});function updateMyStyle(){void 0!==UID&&void 0===targetId&&updateData("STYLECHECK",{SS:sslist,S:slist,A:alist},!0)}
$(document).on("click",".style",function(){if(void 0===targetId){var a=$(this).parent().hasClass("nocheck"),b=$(this).attr("data-rare"),c=$(this).attr("data-id");styleClick(c,b,a);updateMyStyle()}});$(document).on("click",".allOn",function(){var a=$(this).attr("data-rare");$(".style").each(function(){if($(this).attr("data-rare")===a&&!$(this).hasClass("d-none")){var b=$(this).attr("data-rare"),c=$(this).attr("data-id");styleClick(c,b,!0)}});updateMyStyle()});
$(document).on("click",".allOff",function(){var a=$(this).attr("data-rare");$(".style").each(function(){if($(this).attr("data-rare")===a&&!$(this).hasClass("d-none")){var b=$(this).attr("data-rare"),c=$(this).attr("data-id");styleClick(c,b,!1)}});updateMyStyle()});
$(document).on("click","#tabRare",function(){gtag("event","tab",{event_category:"stylecheck",event_label:"Rarity",value:1});$("#tabRare").removeClass("style-tab-disabled").addClass("style-tab-active");$("#tabChar").addClass("style-tab-disabled").removeClass("style-tab-active");$("#tabGacha").addClass("style-tab-disabled").removeClass("style-tab-active");$("#styleAreaRare").removeClass("d-none");$("#styleAreaChar").parent().addClass("d-none");$("#styleAreaGacha").parent().addClass("d-none");$("#tabRare").attr("style",
"width:33%");$("#tabChar").attr("style","width:30%");$("#tabGacha").attr("style","width:30%")});
$(document).on("click","#tabChar",function(){gtag("event","tab",{event_category:"stylecheck",event_label:"Char",value:1});$("#tabChar").removeClass("style-tab-disabled").addClass("style-tab-active");$("#tabRare").addClass("style-tab-disabled").removeClass("style-tab-active");$("#tabGacha").addClass("style-tab-disabled").removeClass("style-tab-active");$("#styleAreaRare").addClass("d-none");$("#styleAreaChar").parent().removeClass("d-none");$("#styleAreaGacha").parent().addClass("d-none");$("#tabRare").attr("style",
"width:30%");$("#tabChar").attr("style","width:33%");$("#tabGacha").attr("style","width:30%")});
$(document).on("click","#tabGacha",function(){gtag("event","tab",{event_category:"stylecheck",event_label:"Gacha",value:1});$("#tabChar").addClass("style-tab-disabled").removeClass("style-tab-active");$("#tabRare").addClass("style-tab-disabled").removeClass("style-tab-active");$("#tabGacha").removeClass("style-tab-disabled").addClass("style-tab-active");$("#styleAreaRare").addClass("d-none");$("#styleAreaChar").parent().addClass("d-none");$("#styleAreaGacha").parent().removeClass("d-none");$("#tabRare").attr("style",
"width:30%");$("#tabChar").attr("style","width:30%");$("#tabGacha").attr("style","width:33%")});
$(document).on("click","#displaySummary",function(){var a="\u30b9\u30bf\u30a4\u30eb\u6240\u6301\u30c1\u30a7\u30c3\u30ab\u30fc [\u30ed\u30de\u30b5\u30acRS\u4fbf\u5229\u30c4\u30fc\u30eb] %0D%0A\u5168 "+(sslist.length+slist.length+alist.length+"\u4f53/"+(allCount.SS+allCount.S+allCount.A)+"\u4f53 ("+$(".allPer").first().text()+"\uff05\uff09%0D%0A");a+="SS "+sslist.length+"\u4f53/"+allCount.SS+"\u4f53 ("+$(".SSPer").first().text()+"\uff05\uff09%0D%0A";a+="S "+slist.length+"\u4f53/"+allCount.S+"\u4f53 ("+
$(".SPer").first().text()+"\uff05\uff09%0D%0A";a+="A "+alist.length+"\u4f53/"+allCount.A+"\u4f53 ("+$(".APer").first().text()+"\uff05\uff09%0D%0A";a="https://twitter.com/intent/tweet?text="+a+"&url=https://nao-romasaga.github.io/stylecheck.html"+(void 0!==UID?"?"+UID:"")+"&hashtags=\u30ed\u30de\u30b5\u30acRS\u4fbf\u5229\u30c4\u30fc\u30eb,\u30b9\u30bf\u30a4\u30eb\u6240\u6301\u30c1\u30a7\u30c3\u30ab\u30fc";$(".twitter-share-button").attr("href",a);$("#modal01").fadeIn();$("#modalInner").css("animation",
"modal 0.5s forwards");return!1});$(document).on("click",".modalClose",function(){$("#modal01").fadeOut();$("#modalInner").css("animation","modalClose 0.5s forwards");return!1});var MASTER_LEVEL=[0,2,4,6,8,10,12,14,16,19,22,25,28,31,35,39,43,48,53,58,64,70,76,83,90,98,106,115,124,134,144,155,166,178,190,203,216];function getMasterLevel(a){a=5*Number(a);var b=1,c;for(c in MASTER_LEVEL){if(a<MASTER_LEVEL[c])break;b=c}return Number(b)+1}function calcPer(a){return Math.round(1E4*a)/100}
function styleClick(a,b,c){var d=STYLE_MASTER[a].WeaponType,f=alist;"SS"===b?f=sslist:"S"===b&&(f=slist);$("."+a).each(function(){c?$(this).parent().removeClass("nocheck"):$(this).parent().addClass("nocheck")});c?(-1===f.indexOf(a)&&f.push(a),-1===weponType[d].indexOf(a)&&weponType[d].push(a)):(-1<weponType[d].indexOf(a)&&(weponType[d]=weponType[d].filter(function(b){return b!==a})),"SS"===b?sslist=f.filter(function(b){return b!==a}):"S"===b?slist=f.filter(function(b){return b!==a}):alist=f.filter(function(b){return b!==
a}));$(".myAll").text(sslist.length+slist.length+alist.length);$(".mySS").text(sslist.length);$(".myS").text(slist.length);$(".myA").text(alist.length);b=sslist.length+slist.length+alist.length;d=allCount.SS+allCount.S+allCount.A;$(".allPer").text(calcPer(b/d).toFixed(2));$(".SSPer").text(calcPer(sslist.length/allCount.SS).toFixed(2));$(".SPer").text(calcPer(slist.length/allCount.S).toFixed(2));$(".APer").text(calcPer(alist.length/allCount.A).toFixed(2));for(var e in WEPON_ATTR)b=Number(weponType[e].length),
$(".my"+e).text(b),d=getMasterLevel(b),$(".myMlv"+e).text(d),d=MASTER_LEVEL[d]-5*b,d=5<d?Math.floor(d/5)+1:1,$(".myNext"+e).text(d),$(".myPer"+e).text(calcPer(b/allCount[e]).toFixed(2))}
function display(){var a=[];for(g in CHAR_MASTER){var b=CHAR_MASTER[g];$("#styleAreaChar").append(b.Name+"<br>");b=$jscomp.makeIterator(b.Holders);for(var c=b.next();!c.done;c=b.next()){var d=c.value,f=STYLE_MASTER[d];c=f.Rarity;var e=""===f.gacha?"\u6c4e\u7528":f.gacha,k=STYLE_MASTER[d].WeaponType;allCount[c]++;allCount[k]++;d=$("<button>").addClass("style").addClass(getStyleIconClass(c)).addClass(d).attr("style",getImgUrl("style_icon/"+d+".png")).attr("data-id",d).attr("data-rare",c).attr("data-type",
f.WeaponType);d=$("<span>").addClass(getStyleIconBgClass(c)).addClass("nocheck").append(d);$("#styleAreaChar").append(d.clone());$("#"+c+"Area").append(d.clone());void 0===a[e]&&(a[e]={SS:[],S:[],A:[]});a[e][c].push(d.clone())}$("#styleAreaChar").append("<br>")}var g=$jscomp.makeIterator(gachaList);for(b=g.next();!b.done;b=g.next()){b=b.value;$("#styleAreaGacha").append(b+"<br>");e=$jscomp.makeIterator(a[b].SS);for(c=e.next();!c.done;c=e.next())c=c.value,$("#styleAreaGacha").append(c);e=$jscomp.makeIterator(a[b].S);
for(c=e.next();!c.done;c=e.next())c=c.value,$("#styleAreaGacha").append(c);b=$jscomp.makeIterator(a[b].A);for(c=b.next();!c.done;c=b.next())c=c.value,$("#styleAreaGacha").append(c);$("#styleAreaGacha").append("<br>")}$(".all").text(allCount.SS+allCount.S+allCount.A);$(".allSS").text(allCount.SS);$(".allS").text(allCount.S);$(".allA").text(allCount.A);for(var h in WEPON_ATTR)$(".all"+h).text(allCount[h]);a=void 0!==targetId?targetId:UID;console.log("readStyleCheckData start");readStyleCheckData(a,
function(a){console.log("readStyleCheckData end",a);if(null!==a){sslist=void 0!==a.SS?a.SS:[];slist=void 0!==a.S?a.S:[];alist=void 0!==a.A?a.A:[];var b=$jscomp.makeIterator(sslist);for(a=b.next();!a.done;a=b.next())styleClick(a.value,"SS",!0);b=$jscomp.makeIterator(slist);for(a=b.next();!a.done;a=b.next())styleClick(a.value,"S",!0);b=$jscomp.makeIterator(alist);for(a=b.next();!a.done;a=b.next())styleClick(a.value,"A",!0)}},!0)};
